### ISSUE TITLE
有时出厂列车与对向行驶的入厂列车会撞到一起而导致堵塞

### ISSUE THREAD

**Issue by SteveNotSet** [jonafanho/Minecraft-Transit-Railway#107]
**Expected Behaviour**
入厂列车应该等待出厂列车出厂后再入厂。

**Actual Behaviour**
A clear and concise description of what actually happened.
一列车（图中的K-train）出厂时，另一列车（图中的CAF）正在回厂，两车需要经过同一段铁路，两车均因为前面的区间有车而停下。
不久后，所有的列车都堵在正线上或车厂里。

**Reproduction Steps**
Steps to reproduce the behaviour:

1. 如图所示建造一个车厂并连接到正线。https://github.com/SteveNotSet/hello-world/blob/master/2021-08-10_17.27.54.png
2. 设置路线使列车开出正线运营。
3. 等待一段时间，可能需要几小时。
4. 重新刷新路线后，运营恢复正常，但几小时后会重新堵塞。

**Crash Report**
Attach a crash report to the issue.
游戏没有崩溃。

**Screenshots**
https://github.com/SteveNotSet/hello-world/blob/master/2021-08-10_17.27.54.png
https://github.com/SteveNotSet/hello-world/blob/master/%E5%A4%A7%E5%A1%9E%E8%BD%A6.png
https://github.com/SteveNotSet/hello-world/blob/master/%E5%A4%A7%E5%A1%9E%E8%BD%A6%EF%BC%88%E6%A0%87%E6%B3%A8%EF%BC%89.png

**Environment**

- Minecraft Version: 1.16.5
- Installed Mods: MTR-1.16-3.0.0-beta-7
- replaymod-1.16.4-2.5.2
- fabric-carpet-1.16.5-1.4.34+v210428
- BBOutlineReloaded-2.4-1.16.3-fabric

**Additional Information**
Anything else you want to add?
希望能改进信号系统

**Comment by jonafanho** [comment]
這是正常的，您可以使用單方向鐵軌。我也會改進信號系統，謝謝您的提議。
