### ISSUE TITLE
Rail connector/node that sends a redstone signal

### ISSUE THREAD

**Issue by DipekTheRabbit** [jonafanho/Minecraft-Transit-Railway#114]
**Is your feature request related to a problem? Please describe.**
I would like to add custom announcement through command blocks, the playsound command and a resource pack

**Describe the solution you'd like**
I would like for there to be a connector or a nodethat sends a redstone signal. When a train rides over the rail or node it sends a redstone signal.

**Additional Information**
I think that a node would be best because if its a connector it might be hard for the user to know where to put the redstone.

**Comment by linuxkettle** [comment]
Yay, like the discord suggestion. I wonder if you could make all rail nodes emit redstone signals? Or would that break stuff...

**Comment by cherbert** [comment]
I vote for this suggestion. This could provide a lot of possibilities in game.

**Comment by linuxkettle** [comment]
It would only work when the player is nearby however, redstone does nothing in unloaded chunks.

**Comment by cherbert** [comment]
> It would only work when the player is nearby however, redstone does nothing in unloaded chunks.

That is fine. I mainly need it for playing audio sounds when trains arrive. Audio only needs to be played if it's being heard.

**Comment by jonafanho** [comment]
Added train redstone sensor blocks, closing this issue
