### ISSUE TITLE
Make the platform connector turn around trains and add some sort of signalling system

### ISSUE THREAD

**Issue by funbuket9** [jonafanho/Minecraft-Transit-Railway#116]
**Is your feature request related to a problem? Please describe.**
It is frustrating when trains do not turn back around at the platform and, as a result, trains get delayed.

**Describe the solution you'd like**
I would like for you to make the platform track have it so trains back around without needing to build the turn back connector. Basically, a train stops at the platform connector and then turns around at the platform without needing to go forward to turn around. Also, i would really like a signalling system so, trains at the previous stop can wait until the train at the next stop has cleared.

**Additional Information**
This would benefit people who are trying to build mainline stations without the turnaround connector.

**Comment by SteveNotSet** [comment]
In my Minecraft, trains can use the platform track to turn back.
Now beta-7 has a simple signal system to make sure that one region of track has only one train, but it often makes my trains stuck in the depot. I think a better and customizable signal system is a good idea.

**Comment by SteveNotSet** [comment]
But in some busy subway systems, trains often wait for entering the station just behind the train in the station

**Comment by linuxkettle** [comment]
Double. Track. Everything.

Otherwise you get the smooshed train noses I posted in #off-topic.
