### ISSUE TITLE
Is there a MTR train ticket?

### ISSUE THREAD

**Issue by Eric28020** [jonafanho/Minecraft-Transit-Railway#12]
I know there is a ticket machine, but where’s the ticket itself? BTW, I had a concept.

The MTR ticket look like this:
![3DA69610-47D7-4219-8DDD-C93267DC9C27](https://user-images.githubusercontent.com/55635216/105571582-daae2e80-5d05-11eb-9114-87c83737c618.jpeg)

The ticket is used to enter and exit the paid areas of MTR train stations via the turnstile. To obtain it, use the ticket machine and select how many tickets to get (Max of 4 adult tickets and 4 concessionary tickets for each use).

**Comment by jonafanho** [comment]
Thank you for your suggestion! I've added your idea to my [todo list](https://github.com/jonafanho/Minecraft-Transit-Railway/wiki/Todo-List). Stay tuned for updates!

**Comment by Eric28020** [comment]
One more thing: The Octopus card has a variety of colors and don’t forget the first and second generation cards and the tourist version.

The First-Generation cards look like this:
![8BE1E43A-CF59-4C4F-A6DA-FDAEAD468E1F](https://user-images.githubusercontent.com/55635216/105626831-6b107000-5de7-11eb-8d62-0912b5ae0dab.jpeg)

The Second-Generation cards look like this:
![EE007D02-8CF2-4111-94E8-8DF98EC886F1](https://user-images.githubusercontent.com/55635216/105626825-5fbd4480-5de7-11eb-808f-dbf8b26e5a64.jpeg)

The tourist version look like this:
![EB542E5C-ABA3-4722-ABAA-386331F40884](https://user-images.githubusercontent.com/55635216/105627043-12da6d80-5de9-11eb-9728-79e29da7424d.jpeg)
