### ISSUE TITLE
站名（墻上）方塊文字自定義

### ISSUE THREAD

**Issue by ZiYueCommentary** [jonafanho/Minecraft-Transit-Railway#122]
添加一個給方塊“站名（墻上）”文字的自定義功能，這樣可以達到給終點站加一個”終點站“的標識
同時也可以給玩家自定義文字字體的功能，這樣對文字編輯會更加自由。將模組的自定字體內嵌至模組文件讓玩家選擇，也可以實現書法字體站名

**Comment by AIDA64S** [comment]
似乎設定站名後使用站內表示就會展示本站名
