### ISSUE TITLE
車輛需要受電弓Trains need Pantograph

### ISSUE THREAD

**Issue by AIDA64S** [jonafanho/Minecraft-Transit-Railway#123]
可以給電車添加受電弓嗎，以及接觸網，他們不需要有任何額外的功能，僅僅是裝飾，需要三個東西，受電弓(在部分車輛模型頂部增加)，接觸線，以及假設接觸線用的柱子(類似於柵欄，但是可以用接觸線將兩個柱子連起來)

**Comment by AIDA64S** [comment]
關於這個我的想法是，電網做成與鐵軌一致的那種，就是一個地方放一個節點，另一個地方再放一個節點，然後用一個“電網”item去分別點擊兩端完成連線，並且如果兩端節點的位置和防止軌道節點的位置一致，生成的接觸網彎曲程度就會和軌道一致

**Comment by jonafanho** [comment]
謝謝您的提議。Duplicate of #56
