### ISSUE TITLE
輕鐵門朝向選擇

### ISSUE THREAD

**Issue by ZiYueCommentary** [jonafanho/Minecraft-Transit-Railway#128]
![image](https://user-images.githubusercontent.com/63241389/130350305-b70e5aef-43d3-4dea-9ae8-d9a09ef3219b.png)
輕鐵的門的朝向看起來是固定的，導致輕鐵門的方向與我的月台位置相反
希望可以添加選擇門朝向的選項

**Comment by AIDA64S** [comment]
列車兩邊都有們，把站台內的軌道鋪設為站台軌道，把站台方塊放在你需要讓他開門的那一邊，比軌道高一格，它會自動開門

**Comment by 566666666666789** [comment]
@AIDA64S  你要是能在現實中製造一輛能自由切換車門方向的輕鐵列車，我就讓作者給你添加！

**Comment by 566666666666789** [comment]
@AIDA64S  你如果真的製造出來了，但是，你的列車投入運營，我就讓jonafanho立刻給你添加！

**Comment by ZiYueCommentary** [comment]
> @AIDA64S 你要是能在現實中製造一輛能自由切換車門方向的輕鐵列車，我就讓作者給你添加！

我的建議是讓列車在車廠時設置門的朝向，因為beta7里列車完成一次運營之後再次運營時車門會在上次門的反方向

**Comment by gdshu1337** [comment]
其實不是，無論側線在哪個方向放置，車門永遠在左邊

**Comment by ZiYueCommentary** [comment]
> 

我建设完一条轻轨铁路后确实有这个问题，虽然它的影响不大，但是会对一些可用占地小的站台影响美观。

**Comment by jonafanho** [comment]
RHT light rail trains have been added in the latest update.
