### ISSUE TITLE
渲染错误

### ISSUE THREAD

**Issue by code2828** [jonafanho/Minecraft-Transit-Railway#135]
当：
1. 玩家在水中
2. 轨道不在水中
3. 玩家视角角度与轨道基本平行/成10°角时

时，会出现渲染bug，导致站台铁轨不显示。

**Comment by AIDA64S** [comment]
这个bug无所谓

**Comment by code2828** [comment]
《无所谓》
指我发现铁轨没有渲染出来以为没连上，结果把整个水下部分重新连了一遍，然后发现重了，又都删掉

**Comment by AIDA64S** [comment]
渲染部分的bug太多了，但是没有对游戏的实际机制造成影响

**Comment by jonafanho** [comment]
這可能是Minecraft本身的bug，您有游戲載圖嗎？

**Comment by jonafanho** [comment]
沒有載圖 lol
