### ISSUE TITLE
未知贴图错误导致游戏当掉

### ISSUE THREAD

**Issue by qwertyuiop092** [jonafanho/Minecraft-Transit-Railway#138]
图片如下
![2021-08-22_14 46 48](https://user-images.githubusercontent.com/67501956/130755876-f2ec76e8-d50c-4bec-b4bd-605accb71ce9.png)

**Comment by jonafanho** [comment]
您有足夠的ram嗎？裝了什麽其他模組？

**Comment by qwertyuiop092** [comment]
我把畫質調整成了_極佳_，怪不得了

**Comment by jonafanho** [comment]
好的，那我關了這個issue吧
