### ISSUE TITLE
Custom Route Destination

### ISSUE THREAD

**Issue by cherbert** [jonafanho/Minecraft-Transit-Railway#143]
**Is your feature request related to a problem? Please describe.**
When you have a line that has multiple branches e.g The Northern Line in London has multiple branches and destinations. It's currently difficult to know what branch the train is taking.

**Describe the solution you'd like**
If when preparing a route you could have the ability to set a custom Destination Description and this could be used on the PIDS instead of the default last station. e.g on the Northern Line one of the final destinations is Edgware. If we could set the custom destination to Edgware via Bank then this would appear on the PIDS. We then can have other routes where the Custom Destination is Edgware via Charing Cross etc... Same destination just an alternative descriptor for the PIDS.

**Additional Information**
I think this could be a quick fix unless you have a more complex solution in mind.

**Comment by jonafanho** [comment]
Wow this was actually such an old suggestion. It's finally completed!
