### ISSUE TITLE
Train bewilderment

### ISSUE THREAD

**Issue by 566666666666789** [jonafanho/Minecraft-Transit-Railway#147]
**Expected Behaviour**

**Actual Behaviour**
A clear and concise description of what actually happened.
The criminal act of the train breaking into the down line to traverse the graph
**Reproduction Steps**
Steps to reproduce the behaviour:
1.Modified version
2.Construction depot
3.Accurately set the operation route of the depot [really, no error]
4.This scene has appeared!

**Crash Report**
Attach a crash report to the issue.

**Screenshots**
Want to take a screenshot? It's a pity that this screenshot can't be remarked at all
[I am from Beijing, so the screenshot standard is simplified Chinese! 】
**Environment**

- Minecraft Version:1.16.5
- Installed Mods:MTR-β8-U7,Creation God and other modules not related to this question!

**Additional Information**
Anything else you want to add?
There are also Open GL errors 1280 and 1281 caused by train running.

**Comment by 566666666666789** [comment]
@jonafanho This is just a mild bewilderment, and there are several severe bewilderment behaviors on the train here.

**Comment by jonafanho** [comment]
I'm sorry, I don't really understand what the issue is here.
