### ISSUE TITLE
Customize the content of the announcement and bring back the previous version of the Chinese announcement

### ISSUE THREAD

**Issue by Polish-ball-man** [jonafanho/Minecraft-Transit-Railway#149]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Example: I'm always frustrated when...

**Describe the solution you'd like**

**Additional Information**
Add Customize the content of the announcement and bring back the previous version of the Chinese announcement

**Comment by jonafanho** [comment]
Not sure what you mean here, feel free to elaborate more and we can reopen the issue if needed.
