### ISSUE TITLE
Train gets out from track after stopping

### ISSUE THREAD

**Issue by BoscoChung1234** [jonafanho/Minecraft-Transit-Railway#15]
**Expected Behaviour**
Follow the tracks and never get off

**Actual Behaviour**
The car is out of the track after stopping

**Screenshots**
https://drive.google.com/file/d/101s72nmEfQhhFEeJIaiJIpAmZsfa_5LF/view?usp=sharing
(Bug starts at 0:09)

**Comment by jonafanho** [comment]
Thanks for posting this! It is a known issue and can be temporarily resolved if the platform's length is increased to match the length of the train. I will work on a better fix in the future, so I'll keep this issue open for now.

**Comment by jonafanho** [comment]
This should be fixed in beta-5. Please let me know if you encounter other issues, thanks!
