### ISSUE TITLE
有關站點的X號停車區問題 The question about Zone X of the station

### ISSUE THREAD

**Issue by WNCX** [jonafanho/Minecraft-Transit-Railway#154]
我看見在beta-7版本中在儀表盤的站名下面出現了（X號停車區）的字樣，英文下是Zone X， 我看了wiki和youtube上的視頻沒有找到相應的注釋，但我發現這個停車區和站與站間的收費標準有關聯，我想問問這裏之間有有什麽算法嗎，這對於我控制站點閒的價錢很有用

**Comment by jonafanho** [comment]
您好，這條視頻應該有的：https://www.youtube.com/watch?v=6R1y-xt4nbc&ab_channel=JonathanHo 大約 1 分 24 秒
C = 2 + | Z1 - Z2 |
C = total cost
Z1 = entry zone
Z2 = exit zone

**Comment by WNCX** [comment]
> 您好，這條視頻應該有的：https://www.youtube.com/watch?v=6R1y-xt4nbc&ab_channel=JonathanHo 大約 1 分 24 秒
> C = 2 + | Z1 - Z2 |
> C = total cost
> Z1 = entry zone
> Z2 = exit zone

感謝您的解答，我已經知道如何去調整收費了，謝謝您
