### ISSUE TITLE
Light Rail trains issue with door side

### ISSUE THREAD

**Issue by nthnlws** [jonafanho/Minecraft-Transit-Railway#157]
**Expected Behaviour**
When train pulls into depot, it is flipped, since it is expected that the train will come in front first, the train is flipped so that it can leave front first again.

**Actual Behaviour**
On Light Rail train (and all variants, phase 1-5), the doors are only on one side. When using a turnback rail for the route, the train ends up going into the depot back first (instead of the expected front first, since it never actually completed a loop). This means that when it is flipped, it ends up leaving the depot "backwards", with the doors facing the wrong side. This is fine on all other trains since the doors are on both sides anyway. But not with Light Rail variants. What end up happening is the train car has doors on the opposite side every new route.

**Reproduction Steps**
Steps to reproduce the behaviour: Depot --> platform 1 --> turnback --> platform 2 --> turnback --> depot

Screenshots attached below of route that causes the issue
![2021-09-15_00 17 49](https://user-images.githubusercontent.com/88010944/133374984-0555f6af-2ee2-4031-8450-f96d40d18885.png)

Possible solution: Instead of just blindly flipping the train every time it enters the Depot, reset to a standard position (front facing), so that no matter if the train enters frontwards or backward, the output from depot is the same.

**Comment by jonafanho** [comment]
Actually I think this is a non-issue, since that's the expected behaviour.
