### ISSUE TITLE
Redstone integration with platform blocks

### ISSUE THREAD

**Issue by nthnlws** [jonafanho/Minecraft-Transit-Railway#158]
Similar to issue #114, create blocks (maybe special platform blocks) that create various Redstone signals such as reporting a train arrival, releasing a held train (as described below) etc. 
![2021-09-15_00 22 13](https://user-images.githubusercontent.com/88010944/133375624-5b125466-0050-44bf-bbc4-f31a81e238f1.png)

Create special platform blocks that look the same from above, but have a special texture/function. One could be sending a redstone signal when a train arrives (the red cross on the left), or sending a train that is currently being held (green cross) when that block is redstone powered (easiest method would be a redstone torch from underneath).

These new blocks could be integrated into the platform without being very obvious, especially from above. You could add as many or as few as you wanted to add functionality to the platform, such as multiple detectors or send-offs.

Suggestion part 2: Have the ability to have a train always stop at a platform unless the "send-off" block is powered. This block could be left on to keep standard platform behavior, or turned off so that a pulse would need to be sent to send the train away. This functionality in the platform menu would be unlocked when a "platform hold" block is detected as part of the platform (as described in the first paragraph).

**Comment by jonafanho** [comment]
Added train redstone sensor blocks, closing this issue
