### ISSUE TITLE
Rail nodes with more angles

### ISSUE THREAD

**Issue by Steve-xmh** [jonafanho/Minecraft-Transit-Railway#159]
I wanna place some long rail with slanted angle, but for now I can only place right angle rail nodes.

I would like we can place rail node and they will rotate to the direction the character is looking at. (Like sign)

**Comment by linuxkettle** [comment]
hmm,,, Signs have 16 different rotations, the old rail nodes in the 1.10 version of the mod have 8 but I don't know how that should be done. Also now that there's S-bends do we need diagonals?

**Comment by Steve-xmh** [comment]
> hmm,,, Signs have 16 different rotations, the old rail nodes in the 1.10 version of the mod have 8 but I don't know how that should be done. Also now that there's S-bends do we need diagonals?

Yes we need. Imagine if we want to make a station with non-straight platforms, we can't just use right angle rail or it might be strange. Or we need to have a switch rail between a diagonal rail, that's a lot of reason for rails with more angles. And the most important, to make rails more realistic.

If 16 directions aren't enough, can we use brush to set more angles?

(Using translation, reply if there's something confused)

**Comment by cherbert** [comment]
I don't understand what purpose angled rail nodes provides. I hope we aren't trying to turn this mod into a Rollercoaster mod!

**Comment by Steve-xmh** [comment]
> I don't understand what purpose angled rail nodes provides. I hope we aren't trying to turn this mod into a Rollercoaster mod!

Don't get overthinking, I just want to make some of rail system more realistic like this:

![An random example I picked](https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/JR-East-Tokyo-STA_Shinkansen-Home.jpg/1024px-JR-East-Tokyo-STA_Shinkansen-Home.jpg)

(This picture is from wikipedia)

As you see, the station rail is almost slightly curved, which is what the right rail can't build.

Also other mods also supports rails with more angles such as Immersive Railroading and Real Train Mod (It even support tilting rails!). So why not?

**Comment by cherbert** [comment]
I really don't understand what you are asking for. The current version of MTR has curved rails.

**Comment by cherbert** [comment]
Oh I think I do. You want the nodes to be able to have more than 4 angles

**Comment by Steve-xmh** [comment]
> Oh I think I do. You want the nodes to be able to have more than 4 angles

Yes that's what I need.

**Comment by kettle-7** [comment]
> > I don't understand what purpose angled rail nodes provides. I hope we aren't trying to turn this mod into a Rollercoaster mod!
> 
> Don't get overthinking, I just want to make some of rail system more realistic like this:
> 
> ![An random example I picked](https://camo.githubusercontent.com/f8a31525679abacc178448963aa586851bc9ba54e9e453719e816081578b3ef2/68747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f7468756d622f352f35372f4a522d456173742d546f6b796f2d5354415f5368696e6b616e73656e2d486f6d652e6a70672f3130323470782d4a522d456173742d546f6b796f2d5354415f5368696e6b616e73656e2d486f6d652e6a7067)
> 
> (This picture is from wikipedia)
> 
> As you see, the station rail is almost slightly curved, which is what the right rail can't build.
> 
> Also other mods also supports rails with more angles such as Immersive Railroading and Real Train Mod (It even support tilting rails!). So why not?

Yeah I made university with its curved platform and big gap, I used armour stands to rotate the blocks.

**Comment by kettle-7** [comment]
> > hmm,,, Signs have 16 different rotations, the old rail nodes in the 1.10 version of the mod have 8 but I don't know how that should be done. Also now that there's S-bends do we need diagonals?
> 
> Yes we need. Imagine if we want to make a station with non-straight platforms, we can't just use right angle rail or it might be strange. Or we need to have a switch rail between a diagonal rail, that's a lot of reason for rails with more angles. And the most important, to make rails more realistic.
> 
> If 16 directions aren't enough, can we use brush to set more angles?
> 
> (Using translation, reply if there's something confused)

Yes, I get what you mean. Any more than 16 rotations and lets just say I mightn't be able to use the mods anymore 😉

Also, you should join the discord @Steve-xmh

https://discord.gg/Minecraft-Transit-Railway

If anything you'll get replied to faster.

**Comment by Steve-xmh** [comment]
> > > hmm,,, Signs have 16 different rotations, the old rail nodes in the 1.10 version of the mod have 8 but I don't know how that should be done. Also now that there's S-bends do we need diagonals?
> > 
> > 
> > Yes we need. Imagine if we want to make a station with non-straight platforms, we can't just use right angle rail or it might be strange. Or we need to have a switch rail between a diagonal rail, that's a lot of reason for rails with more angles. And the most important, to make rails more realistic.
> > If 16 directions aren't enough, can we use brush to set more angles?
> > (Using translation, reply if there's something confused)
> 
> Yes, I get what you mean. Any more than 16 rotations and lets just say I mightn't be able to use the mods anymore 
> 
> Also, you should join the discord @Steve-xmh
> 
> https://discord.gg/Minecraft-Transit-Railway
> 
> If anything you'll get replied to faster.

Thank you. I've already in as SteveXMH#3394. Just watching inside cuz I would need to use a lot of translation for chatting in English. (Simplified Chinese is my mother language)

**Comment by jonafanho** [comment]
Solved with #219
