### ISSUE TITLE
Rails with configurable max speed

### ISSUE THREAD

**Issue by Steve-xmh** [jonafanho/Minecraft-Transit-Railway#160]
We now have some rails with different levels, but they are only in a fixed max speed.

Can we adjust them for different max speed? Like 0-20 km/h for wooden, 20-40 km/h for stone, and so on.

Like if we right click them, it will open an interface to set up the speed we need.

And we can also add a creative type of rail, which can define any speed we want.

**Comment by kettle-7** [comment]
What about netherite rails that can do up to 2,400kph...

**Comment by kettle-7** [comment]
Faster than Mach 2 :~)

**Comment by Polish-ball-man** [comment]
What will happen if 1024? ? ?

**Comment by kettle-7** [comment]
computer melt hole in table

**Comment by kettle-7** [comment]
Also customised rail speed used to exist in the forge version

**Comment by jonafanho** [comment]
Probably not gonna implement this as it will be less user-friendly. There are also more speed rails added into the latest version. Thanks for your suggestion!
