### ISSUE TITLE
「刷」shift+右鍵切換月台自動閘門顯示內容

### ISSUE THREAD

**Issue by ZiYueCommentary** [jonafanho/Minecraft-Transit-Railway#167]
有些閘門空間明顯無法寬鬆顯示路線，例如：
![image](https://user-images.githubusercontent.com/63241389/134916195-6905dc6f-6a83-4b7d-9983-482420a38f0a.png)
但有些閘門空間本應該顯示路線卻顯示前往方向，例如：
![image](https://user-images.githubusercontent.com/63241389/134916351-4139b3c9-589e-44ad-a2c5-7aa81b88d8ec.png)
如果添加一個“刷”對著閘門shift+右鍵即可在顯示路線和顯示前往方向，可自定義度會更高

另外，有些些站點所有的閘門都會顯示前往方向或都顯示路線，所以添加這樣的功能會更好

**Comment by jonafanho** [comment]
Duplicate / related to #196
