### ISSUE TITLE
“繁体中文（香港）”翻译缺失

### ISSUE THREAD

**Issue by BadHunyun** [jonafanho/Minecraft-Transit-Railway#173]
气  笑  香  港  人

**Comment by BadHunyun** [comment]
![image](https://user-images.githubusercontent.com/83549585/135966107-15558149-bf43-4e2f-a34c-73593eca3f74.png)
![image](https://user-images.githubusercontent.com/83549585/135966116-ad5638a7-30e5-4755-8ce8-80571616d71b.png)

**Comment by jonafanho** [comment]
Fixed with new Crowdin Translations
