### ISSUE TITLE
Rail render bug

### ISSUE THREAD

**Issue by NantaArthur** [jonafanho/Minecraft-Transit-Railway#174]
**Expected Behaviour**
the rail is not visible when the train is visible.

**Actual Behaviour**
the rail is floating, and I can see the rail through the train body, I personally think maybe it's because of Iris render

**Reproduction Steps**
1.  just walk

**Crash Report**
No crash log

**Video Link and screenshot**
https://youtu.be/0fPpY6EzbH4
![2021-10-05_18 59 58](https://user-images.githubusercontent.com/45324679/136024327-3265fc32-bb57-4d3f-9ff8-d55fbae2a0de.png)
![2021-10-05_19 12 24](https://user-images.githubusercontent.com/45324679/136024433-e3762cd4-c1bb-4e4a-b927-007d420ca605.png)
![2021-10-05_19 11 03](https://user-images.githubusercontent.com/45324679/136024556-93842dfc-3b88-475c-b40f-31ca9df42611.png)

**Environment**

- Minecraft Version: 1.17.1
- Installed Mods

>
    1.17-flesh2leather-1.0.2.jar
    1.17.1-additionalbars-2.1.1.jar
    AdditionalAdditions-2.1.3.jar
    Adorn-2.1.5+1.17.1-fabric.jar
    AdvancementPlaques-1.17.1-fabric-1.4.1.jar
    advancements-enlarger-0.2.4.jar
    adventurez-1.2.11.jar
    aether-1.17.1-1.5.0.jar
    AppleTreesRev-Fabric-1.17.1-v2.5.jar
    architects-palette-fabric-port-1.2.jar
    architectury-2.5.30-fabric.jar
    artifality-mc1.17.1-0.3.5.jar
    assembly-fabric-21w06a-1.0.0.jar
    attribute-fix-fabric-1.17.1-1.0.3.jar
    axolotl-item-fix-1.1.2.jar
    backslot-1.2.1.jar
    backslotaddon-1.0.6.jar
    bclib-0.3.1.jar
    BeaconOverhaul-1.4.2+1.17.jar
    better-end-0.11.0-pre.jar
    better-nether-5.1.3.jar
    BetterDungeons-Fabric-1.17-1.0.2.jar
    betterf3-1.1.5+1.17.jar
    BetterMineshafts-Fabric-1.17-1.0.1.jar
    BetterPingDisplay-Fabric-1.17.1-1.1.jar
    BetterStrongholds-Fabric-1.17-1.1.2.jar
    BetterThirdPerson-Fabric-1.17-1.5.0.jar
    BFAPI-V1-1-8.jar
    boatcontainer-1.0.0.jar
    boats-and-beeps-1.0.3.jar
    BOMD-1.2.3-1.17.1.jar
    BountifulFabric-1.0.0.jar
    caelus-fabric-0.0.17-1.17.jar
    caracal-1.17-1.3.2.jar
    Cardinal-Components-API-3.1.1.jar
    carrier-1.8.0.jar
    CavesAndCliffsAddOnForWilliamWythersOverhauledOverworld-1.3.jar
    charm-fabric-1.17-3.3.2.jar
    charmonium-fabric-1.17-3.3.0.jar
    cherishedworlds-fabric-2.0.1-1.17.1.jar
    cleancut-1.17-4.0-fabric.jar
    cloth-api-2.0.54.jar
    cloth-config-5.0.38-fabric.jar
    Clumps-fabric-1.17.1-7.0.8.jar
    colytra-fabric-2.0.0-1.17.jar
    comforts-fabric-0.0.6-1.17.1.jar
    companion-bats-fabric-1.17.9.jar
    Controlling-For-Fabric-1.2.0.jar
    cosmetic-armor-1.1.0.jar
    Couplings-1.5.1+1.17.jar
    crawl-0.9.3.jar
    Croptopia-1.17.1-FABRIC-1.6.3.jar
    custom-stars-0.5.jar
    dark-enchanting-0.5.0-1.17.1.jar
    DarkPaintings-fabric-1.17.1-4.0.2.jar
    dashloader-2.0.jar
    dawn-2.0.6.jar
    decorative-4.1.1.jar
    deepslatecutting-1.2.2.jar
    denseores-1.1+1.17.jar
    dragonloot-1.0.9.jar
    drippyloadingscreen_fabric_1.2.0_MC_1.17-1.17.1.jar
    DualRiders-1.17-1.0.5.jar
    DungeonsArise-1.17.1-2.1.47-fabric-release.jar
    dynamic-fps-2.0.5.jar
    Earth2Java-1.7.3+1.17.jar
    eating-animation-1.1.jar
    elytratrinket-fabric-2.0.1-1.17.jar
    enchantment-lore-1.2.1+MC1.17.1.jar
    EnchantmentDescriptions-fabric-1.17.1-4.0.1.jar
    enhancedcelestials-1.17.1-2.0.5.jar
    enhanced_attack_indicator-1.0.2+1.17.jar
    extended-armor-bars-1.1.0.jar
    fabric-api-0.40.1+1.17.jar
    fabric-language-kotlin-1.6.5+kotlin.1.5.31.jar
    fabric-seasons-1.3-BETA+1.17.jar
    fabric-tree-chopper-0.7.2.jar
    FabricSit-1.6.3.jar
    fallingleaves-1.7.3+1.17.1.jar
    fancymenu_fabric_2.3.3_MC_1.17-1.17.1.jar
    farmers-delight-fabric-1.17.1-0.1.2.jar
    ferritecore-3.0.3-fabric.jar
    flinty-tools-1.0.0.jar
    flytre-lib-1.3.9.jar
    forgottenrecipes-fabric-1.17.1-1.0.3.jar
    gate-of-babylon-1.5.1-1.17.1.jar
    geckolib-fabric-1.17-3.0.15.jar
    go-fish-1.3.0-beta-1.17.1.jar
    goldenhoppers-1.1.0.jar
    grass-pass-1.17-1.0.0.jar
    graves-1.1.0+1.17.1.jar
    grizzlybear-1.17-1.2.0.jar
    GuardiansGalore-1.17.1-2.1.jar
    Heartbond-1.17-1.1.0.jar
    icarus-1.3.jar
    illuminations-1.7.2.jar
    inmis-2.3.2-1.17.1.jar
    InventoryHUD-fabric-[1.17.x]-3.4.0.jar
    iris-and-sodium-mc1.17-1.1.2+build.9.jar
    just-end-anchor-1.0.0.jar
    Kambrik-1.1.0.jar
    kibe-1.9.2-BETA+1.17.jar
    konkrete_fabric_1.3.0_MC_1.17-1.17.1.jar
    krypton-0.1.4.jar
    kubejs-fabric-1605.3.10-build.9999.jar
    lazydfu-0.1.2.jar
    lovely_snails-1.0.3+1.17.jar
    mavm-1.0.5.jar
    mcda-1.7.11.jar
    mcdar-1.4.1.jar
    mcdw-3.5.3.jar
    megane-5.4.1.jar
    modmenu-2.0.14.jar
    morebannerfeatures-1.0.7.jar
    morerespawnanchors-1.0.2.jar
    MoreStructuresForWilliamWythersOverhauledOverworld-1.1.jar
    morevillagers-FABRIC-1.17-2.1.1.jar
    mostructures-1.3.0-pre1-1.17.1-fabric.jar
    mousewheelie-1.7.3+mc1.17.1-pre1.jar
    mythic-mounts-1.17.1-1.3.jar
    NaturesCompass-1.17.1-2.0.1-fabric.jar
    nears-1.17-1.1.2.jar
    nearsightedly-1.2.1.jar
    npc-variety-1.17.0-2.1.3.jar
    odysseyhud-fabric-1.17.1-1.1.jar
    onsoulfire-1.17-3.jar
    outvoted-2.0.0-alpha.13-fabric.jar
    oxidized-1.4.0.jar
    paintings-fabric-1.17.1-1.0.0.3.jar
    Patchouli-1.17-54-FABRIC.jar
    Paxi-Fabric-1.17-1.2.2.jar
    polymorph-fabric-0.0.13-1.17.1.jar
    Primordial Shores add-on for William Wythers Overhauled Overworld.jar
    promenade-2.1.2.jar
    quartz-elevator-1.2.5-1.17.1.jar
    repurposed_structures_fabric-2.3.4+1.17.1.jar
    reroll-1.3.0-1.17.1.jar
    rhino-fabric-1605.1.4-build.63.jar
    RoughlyEnoughItems-6.0.279-alpha-fabric.jar
    scorch-1.1.2.jar
    simple-rpc-1.17-2.4-fabric.jar
    sit-1.17.1-13.jar
    slotlink-3.1.5.jar
    snow-under-trees-fabric-mc1.17.0-1.0.0.jar
    spark-fabric.jar
    spirit-1.1.0.jar
    stoneholm-1.3.jar
    stonevaults-1.1.0.jar
    The_Graveyard_(FABRIC)_1.4_for_1.17-1.17.1.jar
    things-0.2.5.jar
    TransparentCosmetics-1.3.0.jar
    traverse-4.0.0.jar
    trinketofundying-fabric-2.0.0-1.17.jar
    trinkets-3.0.4.jar
    trinketshulkerboxes-fabric-2.0.0-1.17.jar
    twigs-1.0.2.jar
    universal_ores-1.0.jar
    upgradedechests-1.0.2-1.17.jar
    upgradedshulkers-1.0.2.-1.17.jar
    urns-mc1.17-1.0.1.jar
    vanilla_degus-1.17.1-v1.2.2-fabric.jar
    veinmining-fabric-0.0.10-1.17.jar
    villager-hats-mod-1.2.1.jar
    villagernames-1.17.1-2.0.0.jar
    visuality-mc1.17.1-0.1.3.jar
    voicechat-fabric-1.17.1-1.2.0.jar
    voidtotem-fabric-1.17.0-1.0.0.jar
    voidz-1.0.5.jar
    wanderingcollector-1.0.2+mc1.17.jar
    WilliamWythersOverhauledOverworld-1.6(1.17.x).jar
    wolves-with-armor-1.6.1-1.17.1.jar
    wraith-waystones-2.1.2.jar
    wthit-fabric-3.9.3.jar
    XaerosWorldMap_1.17.1_Fabric_1.17.1.jar
    Xaeros_Minimap_21.17.1_Fabric_1.17.1.jar
    YungsApi-1.17-Fabric-19.jar

**Comment by BadHunyun** [comment]
Picture 3...... I really want the Mod can do. (but the Mod can't do **:(**   )

**Comment by kettle-7** [comment]
Yeah, Iris as I discovered much less subtly than you, does not work with the mod at the moment. If you want shaders still, you can use optifabric, otherwise just use normal sodium.

**Comment by jonafanho** [comment]
This can be resolved by updating to the latest version of Iris and/or sodium.
