### ISSUE TITLE
Low Things

### ISSUE THREAD

**Issue by Ultimate-USA-YT** [jonafanho/Minecraft-Transit-Railway#175]
We should add Low Platform and Low Door Trains. This could be used for US Light Rail Systems, and US Railways. 

A Railway can have Metro and Hevey Rail.

**Comment by BadHunyun** [comment]
But I do not want to use it :)

**Comment by BadHunyun** [comment]
> Hevey Rail

The Metro/Subway/Tube is the kind of Hevey Rail :-(
:-1

**Comment by kettle-7** [comment]
Well, I'm considering submitting a PR that allows buried platforms so you can make the visible platform half height or a different block.
