### ISSUE TITLE
LED -> LCD

### ISSUE THREAD

**Issue by swoo5571** [jonafanho/Minecraft-Transit-Railway#179]
Hello. I'm Minecraft User.
First, thank you for create this minecraft mod and update. However, I found old things that need to be upgraded.

• Next train
Yeah, LED display is no longer found on MTR System. So, I suggest for change Next train system to LCD display like this:
[[https://zh.m.wikipedia.org/wiki/File:Trains_and_weather_information_display_on_MTR_platforms.JPG]]

Thank you for updating the mod.

**Comment by kettle-7** [comment]
Joestu Client Mod adds the new Tseung Kwan O Line Railway Vision PIDS.

**Comment by TingChangHang** [comment]
> Joestu Client Mod adds the new Tseung Kwan O Line Railway Vision PIDS.

But it not open source
