### ISSUE TITLE
There are new MTR trains in real life

### ISSUE THREAD

**Issue by Eric28020** [jonafanho/Minecraft-Transit-Railway#18]
One thing I found over the internet is there are new MTR trains around Hong Kong in real life and current ones too. Here's a concept and what they look like:

*= Train already in service

### R-Train:*
![R-Train 2-Door](https://user-images.githubusercontent.com/55635216/107108147-c6c8f900-67ea-11eb-9e56-432da2ffa914.png)
![image](https://user-images.githubusercontent.com/55635216/107108565-d0a02b80-67ed-11eb-8e3f-da86170838e4.png)
![image](https://user-images.githubusercontent.com/55635216/107108741-2cb77f80-67ef-11eb-8838-b11169efd980.png)

### MTR High Speed Train AKA Vibrant Express (CRH380A):*
![MTR High Speed Train](https://user-images.githubusercontent.com/55635216/107108153-d6484200-67ea-11eb-90d1-623e9dc3cbe3.png)

### TML C-Train (Similar to SP1900, but with some differences, Not to be confused with Urban Lines C-Train):*
![TML 1141A C-Train 2-Door](https://user-images.githubusercontent.com/55635216/107108164-eb24d580-67ea-11eb-99d2-91622b1617c9.png)
![image](https://user-images.githubusercontent.com/55635216/107108386-59b66300-67ec-11eb-8fbc-e63dd41dd75e.png)

### Q-Train (Similar to C-Train, but with Dynamic Route Map, different livery, & enhanced interior):

![EB6AD013-4467-4494-9FA1-D64FC2B5058B](https://user-images.githubusercontent.com/55635216/107113816-3e604d80-6816-11eb-972f-ce81f9e5bb1c.jpeg)
![image](https://user-images.githubusercontent.com/55635216/107108706-d34f5080-67ee-11eb-86d5-27ae01f23fc6.png)
Note: These trains will soon to replace all M-Trains except the Disneyland Resort Line trains.

### Light Rail Phase 5:*
![image](https://user-images.githubusercontent.com/55635216/107108257-8453ec00-67eb-11eb-9a3c-62ea1ddbec11.png)
![image](https://user-images.githubusercontent.com/55635216/107109801-09dd9900-67f8-11eb-967d-4ce8f7081232.png)![image](https://user-images.githubusercontent.com/55635216/107109821-27aafe00-67f8-11eb-8cd0-1053fa49923a.png)
![_2020111515061342973](https://user-images.githubusercontent.com/55635216/107111405-c2113e80-6804-11eb-9feb-c7888afff41f.jpg)
![image](https://user-images.githubusercontent.com/55635216/107111348-562ed600-6804-11eb-8b15-6e47c73290e4.png)

### Present trains:

*= Will soon to be replaced with new trains

### Light Rail Phase 1 Refurbished (Similar to Phase 4, but with plenty of differences):
![Light Rail 1 Refurbished](https://user-images.githubusercontent.com/55635216/107109532-27a9fe80-67f6-11eb-8171-26d524b7068b.png)
![image](https://user-images.githubusercontent.com/55635216/107110093-021ef400-67fa-11eb-8098-6d86d0732823.png)

### Light Rail Phase 2 (Interior similar to Original Phase 1):*
![Light Rail 2 copy](https://user-images.githubusercontent.com/55635216/107111514-85921280-6805-11eb-88b4-457e6977921e.png)
![image](https://user-images.githubusercontent.com/55635216/107110022-5d041b80-67f9-11eb-82b8-574c5b42956a.png)
![Untitled-1](https://user-images.githubusercontent.com/55635216/107110077-d734a000-67f9-11eb-8ea1-7d7a4a94612b.png)

### Light Rail Phase 3:
![Light Rail 3](https://user-images.githubusercontent.com/55635216/107109613-c2a2d880-67f6-11eb-94d0-66c4e2b12f9b.png)
![image](https://user-images.githubusercontent.com/55635216/107109857-545f1580-67f8-11eb-947a-6158e0126136.png)

### Light Rail Phase 4:
![Light Rail 4](https://user-images.githubusercontent.com/55635216/107109748-99cf1300-67f7-11eb-8863-ad88e25d3931.png)
![image](https://user-images.githubusercontent.com/55635216/107110003-30500400-67f9-11eb-8d14-fa8876939c72.png)

### K-Train:
![K-Train 2-Door](https://user-images.githubusercontent.com/55635216/107110117-3692b000-67fa-11eb-8312-309431de4519.png)
![image](https://user-images.githubusercontent.com/55635216/107110120-3b576400-67fa-11eb-984d-c5cf6d7795eb.png)

### A-Train (Tung Chung Line):
![A-Train 2-Door](https://user-images.githubusercontent.com/55635216/107110206-e1a36980-67fa-11eb-8ba1-45db8199bbe6.png)
![image](https://user-images.githubusercontent.com/55635216/107110410-693da800-67fc-11eb-97f0-2d5559b86d36.png)

### A-Train (Airport Express):
![Airport Express Train](https://user-images.githubusercontent.com/55635216/107110202-dcdeb580-67fa-11eb-8add-2d8860e442d3.png)
![image](https://user-images.githubusercontent.com/55635216/107110429-85414980-67fc-11eb-89d1-e125ace8c63b.png)

### Disneyland Resort Line Train:
Full length/3-Door:
![D-Train 3-Door set](https://user-images.githubusercontent.com/55635216/107110280-8625ab80-67fb-11eb-8cb8-052f3d84525b.png)
Mini Version/2-Door:
![D-Train 2-Door set (Original)](https://user-images.githubusercontent.com/55635216/107110294-976eb800-67fb-11eb-92aa-5ac792664c52.png)
Interior:
![image](https://user-images.githubusercontent.com/55635216/107110471-fd0f7400-67fc-11eb-9d23-2caa01a2ecf7.png)![image](https://user-images.githubusercontent.com/55635216/107110482-0bf62680-67fd-11eb-8c52-0d0cc123daa9.png)
![hong-kongmay-272018-inside-disneyland-260nw-1388767832](https://user-images.githubusercontent.com/55635216/107110527-62636500-67fd-11eb-8868-c0b4a8abac8f.png)

### Urban Lines C-Train:
![C-Train 2-Door](https://user-images.githubusercontent.com/55635216/107110267-6db59100-67fb-11eb-9e70-390ffaf11173.png)
![image](https://user-images.githubusercontent.com/55635216/107110308-b1a89600-67fb-11eb-905f-a21de9d9b4eb.png)

### East Rail Line Mid Life Refurbished (MLR) Train:*
![MLR Train 2-Door](https://user-images.githubusercontent.com/55635216/107110563-a35b7980-67fd-11eb-81be-49d57010d9c1.png)
![image](https://user-images.githubusercontent.com/55635216/107110826-dbfc5280-67ff-11eb-92be-fa71c309deb3.png)

### S-Train:
![s_train](https://user-images.githubusercontent.com/55635216/107108444-b0bc3800-67ec-11eb-9268-37708621ef33.png)![image](https://user-images.githubusercontent.com/55635216/107108524-7010ee80-67ed-11eb-99e4-f8e2722d127b.png)![image](https://user-images.githubusercontent.com/55635216/107110734-216c5000-67ff-11eb-9485-a407149d555d.png)

**Comment by Scwestbrook** [comment]
The mod is still being developed, more trains are already on the todo list.

**Comment by Scwestbrook** [comment]
Why?

**Comment by Scwestbrook** [comment]
It's just annoying for @jonafanho if you ask for more trains, he's working hard on the mod.

**Comment by Eric28020** [comment]
I was trying to tell him not to forget these trains.
