### ISSUE TITLE
Tabs for survival and server

### ISSUE THREAD

**Issue by ardentcrest** [jonafanho/Minecraft-Transit-Railway#186]
It would be nice if we also had the mod tabs that would come up when playing survival as they dont show up on the gui.

Also it would be nice to have this great mod, work just from a server, so the player does not have to have it in his client as some of my players dont want to use the fabric client.

**Comment by kettle-7** [comment]
> Also it would be nice to have this great mod, work just from a server, so the player does not have to have it in his client as some of my players dont want to use the fabric client.

oh no...

How would the client be able to show all the blocks in the crafting menu, the inventory, etc. and how would you be able to render everything (i.e. the block models) entirely server-side without massive lag and while allowing texture packs and shaders?

The answer is: you don't. Had anybody found a solution for this it would have been made. BUT, perhaps when spdfNerd finishes his Forge port then maybe we could set up compatibility between the two on servers with only the MTR mod. The reality is though it's a very optimistic goal to set.

**Comment by kettle-7** [comment]
Okay, that seems attainable. The second half of your suggestion however does not, but we can focus on the first half for now.
