### ISSUE TITLE
Customizable Escalator Speed

### ISSUE THREAD

**Issue by Scwestbrook** [jonafanho/Minecraft-Transit-Railway#19]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I'd like it if you could change the speed escalators go at

**Additional Information**

**Comment by 566666666666789** [comment]
作者可能不会更新这个了，现在作者正在研发beta-7里面的K-Train

**Comment by 566666666666789** [comment]
The author may not update this, now the author is developing K-Train in beta-7

**Comment by 566666666666789** [comment]
And other people’s train skins

**Comment by Eric28020** [comment]
Even the depot thing

**Comment by jonafanho** [comment]
Probably out of scope for this mod.
