### ISSUE TITLE
用刷更改屏蔽门下方箭头标识的方向

### ISSUE THREAD

**Issue by SteveNotSet** [jonafanho/Minecraft-Transit-Railway#190]
某些站台仅供上车/下车，默认的双向指示容易误导乘客。

**Comment by jonafanho** [comment]
Terminating platforms won't show the route map and destination, so hopefully this works for your use case.

**Comment by SteveNotSet** [comment]
> Terminating platforms won't show the route map and destination, so hopefully this works for your use case.

一个典型的例子是广州地铁公园前站。该站1、2号线均采用西班牙式站台。
Here's an example: Gongyuanqian Station of Guangzhou Metro.
![pic2](https://user-images.githubusercontent.com/30768639/203330403-8c17ee56-cb98-4511-bd76-aca939031e0a.jpg)
所有乘客均需从中间站台上车，外侧站台下车。
All passengers must get on the train in the middle platform and get off to the outside platform.
![pic1](https://user-images.githubusercontent.com/30768639/203330633-0d30112d-c2ca-40d9-84ad-b9e2c3ac1c10.jpg)
![pic3](https://user-images.githubusercontent.com/30768639/203330683-3162a784-8dbf-4453-9ba9-24759cd28fe1.jpg)
其他例子：广州地铁8号线彩虹桥站、深圳地铁1号线罗湖站、4号线福田口岸站、港铁东铁线罗湖站。
Other examples: Caihongqiao, Luo Hu(Shenzhen), Lo Wu(Hong Kong), Futian Checkpoint
