### ISSUE TITLE
Make Sidings & Platform track Silver/Grey

### ISSUE THREAD

**Issue by cherbert** [jonafanho/Minecraft-Transit-Railway#197]
**Is your feature request related to a problem? Please describe.**
Yellow and Red track is not very realistic

**Describe the solution you'd like**
Make Sidings and Platform track silver unless the player is holding the siding or platform track item in their hand

**Additional Information**
Similar to functionality found when handling speed rails.

**Comment by kettle-7** [comment]
I mean to say I like the idea.

Also hiding track nodes is another good idea.

**Comment by cherbert** [comment]
This has been added. Thank you.
