### ISSUE TITLE
Next Train Timer

### ISSUE THREAD

**Issue by Scwestbrook** [jonafanho/Minecraft-Transit-Railway#20]
**Is your feature request related to a problem? Please describe.**
People are always telling me they want to know when the train will arrive at the station.

**Describe the solution you'd like**
Could you add a "Next Train" field above the platform screen doors, and on the signs?

**Additional Information**

**Comment by jonafanho** [comment]
Thank you for your suggestion! This will actually be implemented with the Passenger Information Display System (PIDS) block in the future.

**Comment by Scwestbrook** [comment]
Ok.
