### ISSUE TITLE
列车走了他不该走的路线

### ISSUE THREAD

**Issue by BadHunyun** [jonafanho/Minecraft-Transit-Railway#200]
![image](https://user-images.githubusercontent.com/83549585/139521067-3fcad20e-bbd1-4bb4-b131-5c034a4da85b.png)
如图

**Comment by jonafanho** [comment]
您選錯了站台嗎？有沒有刷新路綫？

**Comment by BadHunyun** [comment]
没有选错，路线也已刷新

**Comment by jonafanho** [comment]
列車到分岔口的時候，會先選擇最快速度的路軌。如果所有路軌都是相同的速度，會選擇離終點最近的下一個節點。
