### ISSUE TITLE
I want you to add trains and platform doors that are not yet implemented in HKMTR.

### ISSUE THREAD

**Issue by ShimajiroOTS** [jonafanho/Minecraft-Transit-Railway#201]
**Is your feature request related to a problem? Please describe.**
I want you to add trains and platform doors that are not yet implemented in HKMTR.

**Describe the solution you'd like**
Currently, the following items are not implemented.
- [ ] M-Train (before renewal)
- [x] C-Train (Kwun Tong Line)
- [ ] S-Train (South Island Line)
- [ ] Q-Train
- [ ] R-Train (East Rail Line)
- [ ] CRH380
- [ ] PSD (Nabtesco, Faiveley Transport) 

Note: PSD / APG manufactured by Shenzhen Fangda Automatic System has not been installed yet, and the appearance is unconfirmed, so it is not included in the list.

**Comment by kettle-7** [comment]
as far as I know they've all been suggested and a few are being made. I think somebody finished the unrefined m train and Eric280 made a C train.

**Comment by ShimajiroOTS** [comment]
It seems that the C-train was completed by the pull request, so I checked the task.

**Comment by kettle-7** [comment]
Oh yeah somebody made an unrefurbished m train for centown and the s train has finished modelling and is now being textured. R train and Q train are being modelled.

**Comment by Eric28020** [comment]
You know you shouldn’t make an issue about trains.

**Comment by kettle-7** [comment]
everything except the psd is nearly finished

**Comment by jonafanho** [comment]
Duplicate / related to #196
