### ISSUE TITLE
why it crashed

### ISSUE THREAD

**Issue by jonathanqwq** [jonafanho/Minecraft-Transit-Railway#203]
**Expected Behaviour**
open the game

**Actual Behaviour**
it crashed

**Reproduction Steps**
Steps to reproduce the behaviour:

1.download mtr mod and it crashed

**Crash Report**

[crash-2021-11-04_15.17.52-client.txt](https://github.com/jonafanho/Minecraft-Transit-Railway/files/7472943/crash-2021-11-04_15.17.52-client.txt)

**Screenshots**

**Environment**

- Minecraft Version:1.16.5
- Installed Mods:mtr, fabric api

**Additional Information**
no

**Comment by jonathanqwq** [comment]
hello?

**Comment by Ultimate-USA-YT** [comment]
Have Java 6?

**Comment by jonathanqwq** [comment]
I am using Java 17(JDK)
It remind me to use Java 17(Jdk) when I open minecraft with Java 8(Jre)




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月5日(星期五) 晚上8:54
收件人: ***@***.***&gt;; 
抄送: "Jonathan ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jonafanho/Minecraft-Transit-Railway] why it crashed (Issue #203)





 
Have Java 6?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ultimate-USA-YT** [comment]
Hmmm. Ask in #bug reports

**Comment by jonathanqwq** [comment]
> Hmmm. Ask in #bug reports

how to add a Lable?
thanks

**Comment by jonathanqwq** [comment]
@jonafanho

**Comment by jonafanho** [comment]
Please install the Fabric API mod.
