### ISSUE TITLE
希望铁轨标记加入45度摆放以兼容斜线铁路建造(The rail sign can be placed at 45 degrees.)

### ISSUE THREAD

**Issue by sde111** [jonafanho/Minecraft-Transit-Railway#206]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Example: I'm always frustrated when...

**Describe the solution you'd like**

**Additional Information**

**Comment by kettle-7** [comment]
in progress I think

**Comment by Simba98** [comment]
done by #219

**Comment by sde111** [comment]
> done by #219 and even support 22.5 you can close it.

Thanks for your reply.
