### ISSUE TITLE
Eject player at terminating station rather than Depot

### ISSUE THREAD

**Issue by cherbert** [jonafanho/Minecraft-Transit-Railway#207]
**Is your feature request related to a problem? Please describe.**
Players are ejected from the train at sidings

**Describe the solution you'd like**
Eject the player at the final station on the route before the train leaves for the siding

**Additional Information**
Keep up the good work

**Comment by kettle-7** [comment]
hmm maybe make it an option

annoying when you wanna make through trains

**Comment by jonafanho** [comment]
Duplicate of #170
