### ISSUE TITLE
重新加入头等车厢

### ISSUE THREAD

**Issue by qwertyuiop092** [jonafanho/Minecraft-Transit-Railway#209]
在1.12.2及更早版本中，SP1900拥有头等车厢，而其在Beta 2被移除。
直到Beta 8加入MLR时，头等车厢还未重新加入。
建议重新加入头等车厢及可改动车厢类型的控制系统。

**Comment by BadHunyun** [comment]
Oh yes :(

**Comment by gdshu1337** [comment]
已經在做了
