### ISSUE TITLE
Light Rail Train doesn't show up

### ISSUE THREAD

**Issue by Scwestbrook** [jonafanho/Minecraft-Transit-Railway#21]
**Expected Behaviour**
I should have seen a light rail train

**Actual Behaviour**
Nothing, except it shows up in the dashboard

**Reproduction Steps**
Steps to reproduce the behaviour:
Create a light rail train with the track and a sample route

1.

**Crash Report**
Attach a crash report to the issue.

**Screenshots**

**Environment**

- Minecraft Version:
- Installed Mods: MTR

**Additional Information**
Anything else you want to add?

**Comment by jonafanho** [comment]
Hello, how long is your platform? You mentioned that "it shows up in the dashboard". Do you mean you see the light rail trains on the `Trains` tab?

**Comment by Scwestbrook** [comment]
It needs a 24 block length, the wiki said 9. would you mind updating the wiki?
