### ISSUE TITLE
一些建议 Some Suggestions

### ISSUE THREAD

**Issue by winup-zhou** [jonafanho/Minecraft-Transit-Railway#210]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
加入可自定义的轨旁标志（例如 限速XX公里 等）并可以自定义其样式和内容。
Add customizable trackside signs (e.g. speed limit XX km, etc.) and their style and content can be customized.
自定义的（WAV文件）列车接近，发车，列车车内广播。
Customized (WAV file) train approach, departure, train car announcements.

**Additional Information**
如果可以实现的话，我希望可以在之后的版本加入他们。
如果这些功能太难以实现的话，请忽略我的建议。
I hope to add them in a later version if it is possible to implement them.
If these features are too difficult to implement, please ignore my suggestion.

**Comment by kettle-7** [comment]
Your second suggestion can already be done with command blocks, a resource pack and OGG Vorbid media files.

**Comment by cherbert** [comment]
To be fair, so can the first.

**Comment by winup-zhou** [comment]
But I think these functions can be done more simply through the graphical interface of mod @cherbert @kettle-7

**Comment by winup-zhou** [comment]
But I think these functions can be done more simply through the graphical interface of mod @cherbert @kettle-7

**Comment by jonafanho** [comment]
This can be implemented as kettle and cherbert mentioned. Thanks for your suggestions!
