### ISSUE TITLE
Forge version for Minecraft Transit Railway.

### ISSUE THREAD

**Issue by Neon4UltraPlays** [jonafanho/Minecraft-Transit-Railway#211]
Hello Developers.

I want to have a forge version with all versions (Forge 1.16, 1.17, 1.18) because I usually play on Forge.
Please make the forge version.

**Comment by kettle-7** [comment]
gah we get that basically every day.

https://github.com/spdfNerd/Minecraft-Transit-Railway

he's working on forge 1.16 but do note this mod has taken 4 or 5 years to get to where it is now and the forge version basically needs to be written from scratch.

**Comment by cherbert** [comment]
> Please make the forge version.

Maybe you should make it. You make it sound so easy.

**Comment by Neon4UltraPlays** [comment]
4 to 5 years for the Forge version to release? That's gonna take a long time! I do have Fabric but the forge version will take a long time to build!

**Comment by Neon4UltraPlays** [comment]
Or... there is a better option. I could just use the Fabric Pro version!

**Comment by Ultimate-USA-YT** [comment]
We've got this 284x times!
x=9284

**Comment by cherbert** [comment]
> Or... there is a better option. I could just use the Fabric Pro version!

Never heard of Fabric Pro.

**Comment by chortle1** [comment]
fabric pro is a better version of fabric

**Comment by cherbert** [comment]
> fabric pro is a better version of fabric

Firstly, there is no such thing as Fabric Pro. Secondly you clearly saw this thread but still insisted on spamming another post requesting the exact same thing? Did this thread not suitably answer your question? Please stop spamming this git. There is not going to be a forge version.

**Comment by kettle-7** [comment]
> there is not going to be a forge version.

I'm sure there will, but not soon. It does take time. People don't seem to
notice what it takes to make stuff, as you said 1.17 was hard enough let
alone rewriting the entire mod for forge.
