### ISSUE TITLE
Will there be a Forge and the Easier Version for Transit Railway 1.16/1.17/1.18?

### ISSUE THREAD

**Issue by chortle1** [jonafanho/Minecraft-Transit-Railway#214]
**Hello developers**,

I want to suggest adding the forge version of **Transit Railway.** I usually play on Forge, not Fabric. Also, I would like you to add an easier version of Transit Railway, **Transit Railway Lite.** It is easier than the standard version, but the easier version also needs the Fabric and Forge versions. Transit Railway Lite also is for versions 1.16, 1.17, and 1.18.

Would you please make those versions.? I am not trying to be mean; I want to add it as a feature.

**Comment by chortle1** [comment]
People want the forge version, and the Transit Railway  #took **4 years** to make. Please make the **Lite** and **Forge** versions!

**Comment by cherbert** [comment]
Why don't you make it. And what the heck is a Lite version? Minecraft Transit Railway is already very easy.

**Comment by chortle3** [comment]
> Why don't you make it? And what the heck is a Lite version? Minecraft Transit Railway is already very easy and probably one of the easiest train mods available for Minecraft. Stop making generalised statements like "People want the forge version". Who are these people? The developer chose Fabric. Development currently has taken and still takes a considerable amount of time to develop in his spare time. He clearly states on the curseforge page that he will not be making a Forge version. The sourcecode is freely available for anyone else to do it themselves.

Maybe it's a great idea to make a Lite Version! The Lite version includes easier ways to use MTR mod, simple mechanics, very easy train modification.
