### ISSUE TITLE
When I execute a teleport command while on a train, it freezes. 

### ISSUE THREAD

**Issue by ShimajiroOTS** [jonafanho/Minecraft-Transit-Railway#218]
**Expected Behaviour**
I tried to run a teleport command to go home 8km away.

**Actual Behaviour**
The moment I executed the command described below, Minecraft stopped working.
By the way, the world data is not damaged and is safe. 

**Reproduction Steps**
Steps to reproduce the behaviour:

1.Enter the following command while on the train. (Coordinates are arbitrary. )
>/tp @p 801.93 74.00 4725.34 267.51 33.64

that's all 

**Crash Report**
None

**Screenshots**
None

**Environment**

- Minecraft Version:1.17.1
- Installed Mods:FabricAPI, Optifine
- OS : Windows 10 home(21H1)
- CPU: AMD Ryzen 3600
- GPU: GeForce GTX 1660 SUPER
- RAM: 8GB*2
- HDD+SSD : 2TB+500GB

**Comment by kettle-7** [comment]
Yeah, the train wants you to be in it until you get out. Push shift or get off the train at a station to do that.

**Comment by kettle-7** [comment]
Also despite the insanely fast computer you have, the trains aren't meant to handle people suddenly moving 8km away.

And @p is nearest player, to teleport yourself use @s.

**Comment by kettle-7** [comment]
Seems kinda like how I crashed Centown. Except I don't think I was on a
train.

**Comment by jonafanho** [comment]
Can you please confirm if this still happens in the latest version? Do you also have the logs and crash report?

**Comment by ShimajiroOTS** [comment]
I verified it in the same world with MTR-1.17.1-3.0.0-beta-8. 
Even if I executed it with the following command, it did not freeze. 
>/tp @p ~ ~ ~100000
However, when I executed it with the command copied by F4 + C, it temporarily froze. 
>/execute in minecraft:overworld run tp @s 4041.50 57.50 -4480.50 283.32 58.40
Also, it has not been teleported to the specified coordinates. 

There is no crash report because it was killed in Task Manager.

**Comment by jonafanho** [comment]
Can you please confirm if this happens in the latest version again? Thanks a lot!
