### ISSUE TITLE
Walk-off leaving method

### ISSUE THREAD

**Issue by Scwestbrook** [jonafanho/Minecraft-Transit-Railway#22]
**Is your feature request related to a problem? Please describe.**
No, more of an annoyance where you need to press LSHIFT and walk out the doors to get off the train

**Describe the solution you'd like**
When you walk out the doors, you get off the train without pressing LSHIFT
**Additional Information**

**Comment by isaaclao** [comment]
It has already implemented in the new Beta-5 unofficial releases

**Comment by Scwestbrook** [comment]
Where can I download those?

**Comment by BoscoChung1234** [comment]
> Where can I download those?

Join our Discord server for preview versions:
https://discord.gg/qPHTFvs3Kj

**Comment by jonafanho** [comment]
This is added in beta-5. Please let me know if you encounter issues, thanks!
