### ISSUE TITLE
添加一个增加钱的代码

### ISSUE THREAD

**Issue by jonathanqwq** [jonafanho/Minecraft-Transit-Railway#221]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
添加一个代码，以增加玩家在经过闸门时使用的钱数
代码可以叫：/ticket add 钱数

**Additional Information**
同时添加默认钱数和过闸门无需付钱功能
代码可以叫：/ticket set 默认钱数
/ticket enable off
恢复是：/ticket enable on

**Comment by jonathanqwq** [comment]
@jonafanho

**Comment by BadHunyun** [comment]
_minecraft:_**grass**

**Comment by jonathanqwq** [comment]
Just this is ok?or it's only in future
'set' means..
and 'add' means...




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "upside-down ***@***.***&gt;; 
发送时间: 2021年11月27日(星期六) 凌晨3:39
收件人: ***@***.***&gt;; 
抄送: "Jonathan ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jonafanho/Minecraft-Transit-Railway] 添加一个增加钱的代码 (Issue #221)





 /scoreboard players @p set mtr_balance 7553367
 /scoreboard players @p add mtr_balance 50
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
