### ISSUE TITLE
I accidentally throw the debug stick into the rubbish bin. 

### ISSUE THREAD

**Issue by ShimajiroOTS** [jonafanho/Minecraft-Transit-Railway#223]
**Expected Behaviour**
I accidentally throw the debug stick in the rubbish bin. 

**Actual Behaviour**
When I try to edit rubbish bin with a debug stick, it is thrown away and cannot be edited. 

**Reproduction Steps**
Just right click on the rubbish bin with the debug stick. 

**Environment**
Minecraft Version:1.17.1
Installed Mods:FabricAPI, Optifine
OS : Windows 10 home(21H1)
CPU: AMD Ryzen 3600
GPU: GeForce GTX 1660 SUPER
RAM: 8GB*2
HDD+SSD : 2TB+500GB

**Comment by HistoryButtsandCo10** [comment]
Ah ok, this is truly something. Do you mind joining our discord server? https://discord.gg/wj3HhUza. Thanks! 

Also keep in mind, that 1.17 version of the mod is not as optimized as compared to 1.16, so such bugs would eventually arise. Thank you for your understanding.

**Comment by ShimajiroOTS** [comment]
I participated earlier.
Wait for the role to be added.

**Comment by HistoryButtsandCo10** [comment]
Ah ok good, yeah I see your name in discord. For any more bugs, issues, or even suggestions for the mod itself (This also applies for the other issue you opened up), feel free to text and talk to the staff members and other players. Most of the people there now the mod inside and out, and hope you have fun using the mod. Thanks!

**Comment by jonafanho** [comment]
This can be resolved by shift right-clicking the rubbish bin. It applies to other Minecraft blocks as well, such as levers. If you don't shift right-click with the debug stick, it will activate the block, for example flip the lever.
