### ISSUE TITLE
Kana characters are displayed as horizontal characters. 

### ISSUE THREAD

**Issue by ShimajiroOTS** [jonafanho/Minecraft-Transit-Railway#224]
The way the station name is displayed in the following items is strange. 
- mtr:station_name_tall_wall
- mtr:station_name_tall_block

The station names are as follows.
>カラフル渓谷|Colorful Valley

**screenshot**
![2021-11-28_05 04 11](https://user-images.githubusercontent.com/68157163/143720754-8c43ef7f-2881-44f7-8087-feffccc80836.png)

Note: As a Japanese, this notation feels very strange.

**Comment by jonafanho** [comment]
Fixed in 3.1.0-unofficial-3
