### ISSUE TITLE
A one-way track in which trains travel in the opposite direction(Unofficial 13)

### ISSUE THREAD

**Issue by sde111** [jonafanho/Minecraft-Transit-Railway#229]
![image](https://user-images.githubusercontent.com/74589428/144255531-ee621685-31df-4844-81bc-fec17ca0ba6e.png)
![image](https://user-images.githubusercontent.com/74589428/144255559-8bba70cb-7531-4e19-92d8-e8f715a1097f.png)
![image](https://user-images.githubusercontent.com/74589428/144255581-02e5c33a-006a-4349-94cf-aceea0f85b72.png)
A one-way track in which trains travel in the opposite direction.
The version I'm using：MTR 1.16.5 Unofficial 14

**Comment by sde111** [comment]
> 
Oh,Sorry,I write it wrongly,it should be 13.

**Comment by kettle-7** [comment]
> How did you get Unofficial 14?

You can with GitHub though

**Comment by kettle-7** [comment]
And yes, this big does seem strange. Are you on discord? Or if not could you maybe upload the world zip here?

**Comment by sde111** [comment]
> And yes, this big does seem strange. Are you on discord? Or if not could you maybe upload the world zip here?

Would you mind telling my email address？

**Comment by jonafanho** [comment]
Is this with diagonal rail nodes? I might have broken something, not sure.

**Comment by sde111** [comment]
> Is this with diagonal rail nodes? I might have broken something, not sure.

I originally wanted to upload the map to github or discord, but the map is too large, and I can't find other ways to upload it, unless I send it to you by mail.

**Comment by kettle-7** [comment]
Don't worry I'm on it

**Comment by jonafanho** [comment]
@sde111 @kettle-7 Has this been resolved?

**Comment by sde111** [comment]
> @sde111 @kettle-7 Has this been resolved?

I solved it myself. Add another section of the one-way rail and it will return to normal
