### ISSUE TITLE
Add PSL(PSD Local Control Panel)&IBP(Integrated Backup Panel)&DTIS(Departure Time Indication System) and Manual driving mode

### ISSUE THREAD

**Issue by lonelyicer** [jonafanho/Minecraft-Transit-Railway#239]
**Is your feature request related to a problem? Please describe.**
I think the lack of manual driving has reduced the fun of the mod by at least half
So I suggest adding manual driving mode and related systems
Maybe it will make the mod more popular

**Describe the solution you'd like**
Add manual driving mode,PSL(PSD Local Control Panel),IBP(Integrated Backup Panel),DTIS(Departure Time Indication System)

**Additional Information**
The role of the PSL is to control the PSD manually by the driver on the inside of the end door (in reality this usually happens when the PSD and the Car door linkage fails)

IBP is a human-machine interface device that can control the main equipment controlled by SMCS (in reality, it is usually used as a backup device for SMCS (Station Main Control System) used in emergency situations)

And DTIS
DTIS is a device installed at the end to provide drivers with a countdown to departure

**Comment by HistoryButtsandCo10** [comment]
Damn, you seem to have quite an understanding of train systems. Though Traincraft is already a thing, in which manual driving is the focus of the mod; in which this mod more so focuses on automation of transportation. Basically the fastest way from going to Point A and Point B. It's cheap on survival mode also to do. Anyways, you could join our discord:  https://discord.gg/PVZ2nfUaTW

You could post a suggestion there, and if you could code, you could possibly make it as well. Though most future updates would surround on station functions, more trains, and different types of transportations (ex. buses). Thanks!

**Comment by HistoryButtsandCo10** [comment]
Also, if you ever join the discord. Please message me, I saw your website, and I believe it only runs on the web languages? I've also am in a similar project as well, and ive been looking for ways to make websites more modern. Thank you

**Comment by kettle-7** [comment]
This mod is focused on automated transport, I would in a way be disappointed if you had to manually drive.

DTIS is added in Joestu Client Mod, I'll get the link
(pretty sure I can send the link here, just not in mtr discord)

**Comment by Ultimate-USA-YT** [comment]
Manual driving would be good for things like Maintenance and Shunters
