### ISSUE TITLE
How am I supposed to fix this?

### ISSUE THREAD

**Issue by Eric28020** [jonafanho/Minecraft-Transit-Railway#24]
**Expected Behaviour**
Using the Railway Dashboard and placing station names, colored blocks & signs works fine.

**Actual Behaviour**
When I was adding the stations for the route, it requires zooming in, but when I tried to zoom in using the Railway Dashboard, it actually caused the game to crash with exit code of 0. Same thing happened when I was selecting colors for the stations, placing station names, station signs, selecting the trains tab with the Railway Dashboard, the brush, etc.

**Reproduction Steps**
Steps to reproduce the behaviour:

1. I have no idea

**Crash Report**
[Attempt to set up a train route](https://github.com/jonafanho/Minecraft-Transit-Railway/files/5937997/hs_err_pid10600.log)
[When placing station name signs](https://github.com/jonafanho/Minecraft-Transit-Railway/files/5938081/hs_err_pid7312.log)

**Environment**

- Minecraft Version: 1.16.5
- Installed Mods: MTR Mod 3.0.0 beta 4 only

**Additional Information**
I updated my Intel graphics so many times and it doesn’t work fixing it.

**Comment by jonafanho** [comment]
Thanks for pointing this out. It is a known issue with the custom fonts in the mod. You can try using this resourcepack to disable the fonts and I think it will prevent it from crashing.

[Disable_MTR_Fonts.zip](https://github.com/jonafanho/Minecraft-Transit-Railway/files/5939753/Disable_MTR_Fonts.zip)
