### ISSUE TITLE
Optifine completely breaks Minecraft Transit Railway for Forge

### ISSUE THREAD

**Issue by Ondeth** [jonafanho/Minecraft-Transit-Railway#250]
**Expected Behaviour**
When using 'Minecraft Transit Railway Forge Edition' and 'Optifine' together in Forge 39 (1.18.1), everything should work fine 

**Actual Behaviour**
Models (e.g trains, tracks) completely disappear (it first seemed like nothing works, which was very frustrating in the first place ;-),  animated textures/models don't work too (PID's for example-they simply stay black, even the animated "take the lift" one; signals stay black etc). Therefore Minecraft-Transit-Railway is unusable with Optifine at the moment.

When restarting Minecraft without Optifine in the mods folder, everything works.

**Reproduction Steps**
Install the latest version of the mod for Forge (3.0.0 Beta 8 for Forge) and the latest Architectury 3.2.56, while using the latest version of Optifine (Optifine HD H5_pre3 Ultra / pre2 Ultra or Optifine HD H4 Ultra) and use the latest Forge version (39.0.6)

**Crash Report**
N/A

**Screenshots**
![2021-12-21_17 12 45](https://user-images.githubusercontent.com/10685912/146962533-8276b26f-67ff-459b-9a36-50ac8496f5d5.png)

**Environment**

- Minecraft Version: 1.18.1 (Forge 39)
- Installed Mods: 
mtr-forge-1.18-3.0.0-beta-8.jar
architectury-3.2.56.jar
Optifine HD H5_pre3 Ultra.jar

**Comment by HistoryButtsandCo10** [comment]
Thanks for this, the forge port for the mod is pretty new, even then its not fully forge - you need a dependency for it to work. Either way, the bug is more optifine-related, so the issue might be fixed over time. Feel free to join our discord for more updates and faster response for bugs and issues.

**Comment by kettle-7** [comment]
close?

**Comment by jonafanho** [comment]
Fixed in the latest release
