### ISSUE TITLE
Rail not showing 1.18.1

### ISSUE THREAD

**Issue by UndeadMemegamer** [jonafanho/Minecraft-Transit-Railway#252]
About forge 1.18.1, I found a bug that it cant show rails in 1.18.1. I tried deleting the additional mods and it doesn't work.
Here are the following versions:
-Forge 39.0.6
-Optifine H5 Pre 2
-Architectury API v3.2.57
-Forge MTR Mod 1.18

Message from: PhilippinElevators#7877

**Comment by HistoryButtsandCo10** [comment]
This is more of an optifine problem, as of the moment the forge port for the mod is not fully compatible with it.

**Comment by kettle-7** [comment]
fixed in u3, can close probably

**Comment by jonafanho** [comment]
Fixed in the latest release
