### ISSUE TITLE
Forge版本垃圾桶透視問題

### ISSUE THREAD

**Issue by ZiYueCommentary** [jonafanho/Minecraft-Transit-Railway#253]
垃圾桶的透視關係有所問題，我能夠用垃圾桶透視看到下一層的建築
MC版本：Minecraft 1.16.5（有Optifine）
模組版本：FORGE-1.16.5-3.0.0-beta-8
FORGE版本：Forge 36.2.6
![image](https://user-images.githubusercontent.com/63241389/147351557-286f5820-6eca-40c0-92c7-55d4c0b80733.png)

**Comment by jonafanho** [comment]
Thank you, this will be fixed in the next update!
