### ISSUE TITLE
Route sign with numbers for branches

### ISSUE THREAD

**Issue by itzseven7** [jonafanho/Minecraft-Transit-Railway#256]
**Is your feature request related to a problem? Please describe.**
It's a bit unreadable when looking to a route sign for a route that has several branches

Let's say I have Line B:
- one branch at north
- a central branch
- two branches at south (one straight to south the other on south west)

Then I've created four routes (same name and color, reverse is to have a bidirectional line):
- Line B||South
- Line B||South Reverse
- Line B||South West
- Line B||South West Reverse

All these routes share a common "central" route where train stops at every station

But here what happens:
- If I look on a route sign that is on a station that is part of a specific branch (South or South west), then the sign shows one route which is expected
- Whereas, in a station that is on the "central" path (common), the sign displays two different routes (South and South West)

**Describe the solution you'd like**
It would be cool to "merge" the central branch of a route that can have several branches: when the central branch separate into the two branches, the lines on the sign would be split

We could also display the route number at the end of each branch for more clarity (see screenshots)

**Additional Information**

Here are two screenshots for the issue and what the solution could look like

On the mtr_route_solution, you can see that the line has two branches on the left and on the right.
The line share a central branch from "Aulnay sous bois" to "Bourg la reine" and you see that the branches are clearly visible
You can also see the "route number" at the end of each branch (B2, B3, B4, B5)

![mtr_route_issue](https://user-images.githubusercontent.com/15786509/147505129-584fa0e4-7552-4b77-9b7f-cedf9e1e0560.png)
![mtr_route_solution](https://user-images.githubusercontent.com/15786509/147505249-160c5d9e-1a99-4227-b738-8c3079cae330.png)

Another question: is there a way to make a donation with anything else than Patreon?

Thanks a lot for what you do, this mod is really amazing!

**Comment by itzseven7** [comment]
To have a better idea with the route sign object

![838_000_8l2fc](https://user-images.githubusercontent.com/15786509/147505973-ea7a028d-c72d-4e32-9542-34120c846bbc.jpg)

**Comment by jonafanho** [comment]
@itzseven7 Hello, I am actually working on this feature right now! It might take some time, but I hope to get it into beta-9. Also, is Patreon not working for you? I'm not sure if you're on the Discord server, we could perhaps talk a bit more about that.

**Comment by itzseven7** [comment]
@jonafanho Thanks for the quick answer, yeah I agree that it should not be that easy!

No, I only want to make a single donation for the moment :p

Will join the Discord soon :)

**Comment by jonafanho** [comment]
Sounds good! For Patreon, you can always just sign up and it will charge on the 1st of each month. After that, you can cancel right away.

**Comment by kettle-7** [comment]
close?
