### ISSUE TITLE
站名柱：当英文过长时，竖排的汉字不应随英文挤压

### ISSUE THREAD

**Issue by SteveNotSet** [jonafanho/Minecraft-Transit-Railway#257]
**Is your feature request related to a problem? Please describe.**
![2021-12-29_11 45 17](https://user-images.githubusercontent.com/30768639/147625600-d28db727-d99a-47d6-9dac-f432f799ef24.png)
如图所示，中文随英文一起被挤压

**Describe the solution you'd like**
中文和英文分开处理

**Additional Information**

**Comment by minecraftLYC** [comment]
建议英文换行解决。

**Comment by TingChangHang** [comment]
请问你想怎么样才能满足
