### ISSUE TITLE
Scriptivayeet

### ISSUE THREAD

**Issue by Ultimate-USA-YT** [jonafanho/Minecraft-Transit-Railway#258]
**Expected Behaviour**
Ride a Train in VR

**Actual Behaviour**
Yeeting the Passinger Into Space

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Ride a Train in VR

**Crash Report**
N/A

**Screenshots**
N/A

**Environment**

- Minecraft Version: 1.16.5
- Installed Mods: This Mod

**Additional Information**
Anything else you want to add?

**Comment by kettle-7** [comment]
w h a t        t h e

**Comment by HistoryButtsandCo10** [comment]
VR? like virtual reality? lol

**Comment by a160052** [comment]
Space vr ?????
lol

**Comment by jonafanho** [comment]
Fixed in the latest release
