### ISSUE TITLE
Train carriage disappears instead of moving along planned route

### ISSUE THREAD

**Issue by hapy2452354** [jonafanho/Minecraft-Transit-Railway#26]
**Expected Behaviour**
Train proceeds along planned route as in dashboard

**Actual Behaviour**
A clear and concise description of what actually happened.
Train repeatedly opens door then disappears

**Reproduction Steps**
Steps to reproduce the behaviour:
I am unsure about the reproduction of the behavior

**Crash Report**
Attach a crash report to the issue.
No crash report, just in-game issue

**Environment**
- Superflat world (if applicable)

- Minecraft Version:
- 1.16.5

- Installed Mods:
- ONLY fabric api 0.29.3 and current mod

**Additional Information**
Anything else you want to add?
Normally doors open 2~3 times before disappearing.

**Comment by jonafanho** [comment]
Hello, do you have tracks connecting the platforms on your route? The trains disappear because they are unable to find a valid path in the world. Also, are the stations on your route in the correct order?

**Comment by hapy2452354** [comment]
The tracks are connected and the stations are in correct order. I have checked the rails prior to posting.

**Comment by jonafanho** [comment]
Did you resolve the issue?

**Comment by hapy2452354** [comment]
yes, i think it's my client problem, i redownloaded mc and issue resolved
