### ISSUE TITLE
Game crash on beta-9-unofficial-1

### ISSUE THREAD

**Issue by funbuket9** [jonafanho/Minecraft-Transit-Railway#261]
**Expected Behaviour**
I expect my game to start properly 
**Actual Behaviour**
My game crashes

**Reproduction Steps**
1. Click "play"
2. Wait for the game to load
3. Game crashes

**Crash Report**
[crash-2022-01-01_16.11.20-client.txt](https://github.com/jonafanho/Minecraft-Transit-Railway/files/7797404/crash-2022-01-01_16.11.20-client.txt)
`
**Screenshots**
no screenshots

**Environment**

- Minecraft Version: 1.17.1
- Installed Mods:
![mods](https://user-images.githubusercontent.com/40572871/147844795-f57bb119-125f-4750-befd-dfa22246571d.PNG)

**Additional Information**
I have reported this issue on the Discord server. For now I will keep using the beta-8 version until there is a fix.

**Comment by kettle-7** [comment]
why would you close it?

**Comment by funbuket9** [comment]
> why would you close it?

Because i fixed the issue. I just had to update fabric api and the fabric loader

**Comment by kettle-7** [comment]
Ah, might be an idea to say :~)
