### ISSUE TITLE
404 Not found on LOCALHOST while running game

### ISSUE THREAD

**Issue by zjx2007** [jonafanho/Minecraft-Transit-Railway#265]
![Screenshot](https://user-images.githubusercontent.com/43273440/148745344-e672fa96-c5b0-43c3-bc3c-3cfa945d7c77.png)
I can't get to the route map localhost:8888 and it showed 404 error.
This only occurs while I am in the game.
When I quit, the webpage changes into 'connection refused'

Big thanks to help solving the problem!

**Comment by zjx2007** [comment]
by the way, I'm using Forge and Architectury

**Comment by HistoryButtsandCo10** [comment]
Ah yes, sorry; it is a bit different for the mod's forge port. 

Localhost:8888 is only for the fabric port; but for forge; place this - 

http://localhost:8888/index.html. 

index.html was added at the end. Thanks.

**Comment by zjx2007** [comment]
Thanks!
