### ISSUE TITLE
Trains skip stations in P9 U2

### ISSUE THREAD

**Issue by Ultimate-USA-YT** [jonafanho/Minecraft-Transit-Railway#267]
**Expected Behaviour**
rains stop at stations and appeir on PIDS

**Actual Behaviour**
Neither happen

**Reproduction Steps**

make route

1.

**Crash Report**
Attach a crash report to the issue.

**Screenshots**
Not Avable
My post in #bug-Reports
**Environment**

- Minecraft Version: 1.16.5
- Installed Mods:

**Additional Information**
Anything else you want to add?

**Comment by kettle-7** [comment]
have you assigned the route to the depot? hit refresh path? set time schedule? made sure the siding is on the depot?

**Comment by BadHunyun** [comment]
Where's your pictures? :<
