### ISSUE TITLE
Feature Request: Station announcement block

### ISSUE THREAD

**Issue by winup-zhou** [jonafanho/Minecraft-Transit-Railway#270]
**Is your feature request related to a problem? Please describe.**
In older versions of this mod, an announcement would play before the door closed, but this feature has been removed in the new version.

**Describe the solution you'd like**
This block is capable of broadcasting specified announcements to players within a set range in a set manner.
Examples include **_train approach, arrival, and door closing announcements_.**

_**The block setup page:**_
Platform: (select platform)
Train approach broadcast content: (text)
When this announcement will be made before the train arrives: (select the length of time 0s-5min)
Train arrival broadcast content: (text)
Whether to enable it: (check box)
Content of door closing announcement: (text)
When this announcement will be broadcast before the train departs: (select the length of time 0s-5min)
Broadcast range: (select range, e.g. 5*5)
Whether to display the broadcast content in the chat bar: (check box)

**Additional Information**
If voice is enabled in the settings, the block can play a voice synthesized with the specified text, just like the train announcements.
For example: "列车即将进站，请小心列车与站台之间的空隙，本次列车去往xxx及沿途各站。The train is arriving,please mind the gap between the train and the platform.This train will stop service at xxx station."
_(This is the Beijing MTR broadcast, the content of the broadcast in simplified Chinese and English is almost the same as MTR)_
My English is not very good, sorry.

**Comment by BadHunyun** [comment]
But...Sometimes Train schedule sensor can help you a lot...(doge)

**Comment by HistoryButtsandCo10** [comment]
Hello! You can join our discord and you can speak Chinese there as most of our staff can speak the language. This way your issue can get solved. Thanks! https://discord.gg/V5Ff5BXG.

Please go to #bug-reports.

**Comment by winup-zhou** [comment]
Thank you for your reply!
I've joined Discord and this is not a bug report, but I didn't find a place to submit a suggestion.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jonafanho/Minecraft-Transit-Railway"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月21日(星期五) 上午10:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jonafanho/Minecraft-Transit-Railway] Feature Request: Station announcement block (Issue #270)





 
Hello! You can join our discord and you can speak Chinese there as most of our staff can speak the language. This way your issue can get solved. Thanks! https://discord.gg/V5Ff5BXG.
 
Please go to #bug-reports.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jonafanho** [comment]
As people mentioned, you can use the train schedule sensor with command blocks.
