### ISSUE TITLE
[Enhancement]World time sync with real time & First/Last train setting with announcement

### ISSUE THREAD

**Issue by DreamUniverse843** [jonafanho/Minecraft-Transit-Railway#271]
**Is your feature request related to a problem? Please describe.**
I think the mod's automatic control is fantastic!However,I think it would be better to add a feature that the world time could be sync with the real world so that it would have a better experience in transit,especially in a scenery line.
What's more,the depot only have a train depart setting as time period without first/last train option.I think it would be awesome to have such an option,it would make the automatic control to be better and closer to the real transit.

**Describe the solution you'd like**
The world's time could be sync with the real time(for example,the system time is 8:00 GMT+8,so the world time is 8:00 as well.)
The depot setting could contain an option that control the first/last train with its announcement while passing each station(for example,the first train is 8:00 and the last train is 21:30,and while the last train passing each station,it would have an announcement like"The train service has already ended")

MTR may be the first mod to support these enhancements if it could be developed,tks:)

**Comment by kettle-7** [comment]
This is well beyond the scope of this mod, but I have heard of other mods that have done it.

**Comment by DreamUniverse843** [comment]
> This is well beyond the scope of this mod, but I have heard of other mods that have done it.

That's true in some previous Minecraft versions,however,there's few mods support it in high Minecraft versions(like 1.18+)
And I also suggest if a first/last train option could be added in the depot settings in the Dashboard.That would make the project awesome!
:)

**Comment by cherbert** [comment]
> This is well beyond the scope of this mod, but I have heard of other mods that have done it.

No it isn't. I've even requested this with Jonathan myself.

**Comment by cherbert** [comment]
> 

Please consider adding this to the Discord suggestions system so that I can upvote it lots.

**Comment by DreamUniverse843** [comment]
OK,I'll make it on Discord soon.
tks!

**Comment by jonafanho** [comment]
Added in #471
