### ISSUE TITLE
Bug and enhancement to the terminal station 对终点站的改进

### ISSUE THREAD

**Issue by code2828** [jonafanho/Minecraft-Transit-Railway#272]
**Expected Behaviour**
In the last station of a line, the doors will show "终点站/Terminus" in the place where it usually shows "往xxx/To xxx" and everything will be grey on a line map.

**Actual Behaviour**
The line map is completely empty and it does not show "终点站/Terminus" .

**Reproduction Steps**
Steps to reproduce the behaviour:
1. Create a line with at least 2 stations
2. Go to the last station, place the doors and use the brush on the doors.

**Screenshots**
Non-terminal stations:
![2022-01-25_17 51 09](https://user-images.githubusercontent.com/50510911/150954535-e7d05a69-8c94-4344-b89d-6a9143a6be7b.png)
![2022-01-25_17 51 12](https://user-images.githubusercontent.com/50510911/150954542-c2a03855-333f-48df-9919-9890cd302c6e.png)

Terminal Stations:
![2022-01-25_17 52 43](https://user-images.githubusercontent.com/50510911/150954547-dafb28c3-a0a4-49d6-a717-3e8936965f60.png)
![2022-01-25_17 52 46](https://user-images.githubusercontent.com/50510911/150954550-794666d5-a817-4698-ac74-e0285873c7e1.png)
![2022-01-25_17 52 54](https://user-images.githubusercontent.com/50510911/150954554-a63bb760-82be-4f2d-abb4-58b0c412603e.png)

**Environment**
Minecraft Version 1.18.1

**Additional Information**
Very great mod; keep going!

**Comment by code2828** [comment]
Something more: the train arrival projectors won't work either

**Comment by kettle-7** [comment]
This is intended behaviour, as seen on the MTR.

**Comment by kettle-7** [comment]
> Something more: the train arrival projectors won't work either

Why would you want to see when a train you shouldn't be getting on is going to arrive?

**Comment by zqtang10** [comment]
这不就是港铁的方式吗...如果真的想这么显示那需要自己做mod追加包了
This is MTR's style...if u want to show it you should make resoursepack

**Comment by jonafanho** [comment]
As mentioned, it's intentional.

**Comment by code2828** [comment]
Sorry, I live in Beijing and has just been to Hong Kong once when I was 6... In Beijing subway every terminal station has this "Terminus" thing.

**Comment by minecraftLYC** [comment]
呃…或许可以用单站台折返
