### ISSUE TITLE
Add new train新加入一些列车

### ISSUE THREAD

**Issue by xiaotang27** [jonafanho/Minecraft-Transit-Railway#274]
Please add some new train like East Rail Line R-Train,South Island Line S-Train
请加入一些新列车：比如东铁线R-Train南港岛线S-Train

**Comment by kettle-7** [comment]
Both of these trains are being made, I'm doing r-train and it should be done in the next month or so.

**Comment by a160052** [comment]
PLESE ADD Exterior of an unrefurbished M-Train EMU in 1979

**Comment by jonafanho** [comment]
Added in the latest release
