### ISSUE TITLE
Not showing up station name in some cases

### ISSUE THREAD

**Issue by TSStudio** [jonafanho/Minecraft-Transit-Railway#275]
Is there any differences the methods to getting station name among these places? The entrance station name and platform gate does not seem to display the station name correctly. Is there any more configurations needed, or is it a bug?  
这些地方的站名获取方式不同吗？进站口站名牌和站台门上站名均不能正确显示（仪表盘中的配置是正确的），但是部分地方（如墙上）却能正确显示。是这些地方的名字需要更多的配置吗（不过wiki上并没有提及），还是bug？
![2022-01-27_14 50 16](https://user-images.githubusercontent.com/30061150/151307427-9c7321d4-b64b-4605-b352-c9c5d1ffbf72.png)
上车后动作栏处似乎也不能正确显示。  
Neither in the actionbar.
![Clip_20220127_145131](https://user-images.githubusercontent.com/30061150/151307451-60e7590b-7b50-4519-a0c8-1f494ade3595.png)
然而列车广播却能正常播放。  
However, it seems the train announcement is correct.
![Clip_20220127_145331](https://user-images.githubusercontent.com/30061150/151307456-2758a47b-dad1-4495-9cd2-f1c0bd17da33.png)

Game ver:1.18.1  
Mod ver: 3.0.0 beta 8  
fabric ver: 0.12.12  
fabric api ver: 0.46.1  
  
other mods: worldedit 7.2.8

**Comment by TSStudio** [comment]
该问题似乎仅在 Minecraft 语言设定为简体中文时出现。语言设定为繁体中文（香港）或美国英语时均不会出现。  
The problem seems to appear only when the language of Minecraft is set to "Chinese Simplfied", either "Chinese Traditional" or "English (US)" will NOT cause the problem

**Comment by kettle-7** [comment]
I must admit not many people use simplified with the mod lol

**Comment by TSStudio** [comment]
> I must admit not many people use simplified with the mod lol

Actually there are.  
  
Addition:I tested a few languages:

Japanese 日语(BUG occurs)
Simplfied Chinese 简体中文(BUG occurs)
Traditional Chinese(TW) 繁体中文（TW）(BUG occurs)

Wenyan 文言(BUG DOES NOT occur)
English(US) 英语（US）(BUG DOES NOT occur)
Traditional Chinese(HK) 繁体中文（HK）(BUG DOES NOT occur)

**Comment by kettle-7** [comment]
Does it happen differently without mtr font?

**Comment by TSStudio** [comment]
> Does it happen differently without mtr font?

It doesn't change anything. The bug occurs no matter using the MTR font or not.  
Addition: When using the Wenyan, English(US) or Traditional Chinese(HK), in other words, languages that won't cause the bug, the mod always displays English.

**Comment by jonafanho** [comment]
Fixed in the latest release
