### ISSUE TITLE
添加列车优先级或轨道优先级

### ISSUE THREAD

**Issue by jonathanqwq** [jonafanho/Minecraft-Transit-Railway#276]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
当我在游戏中设置exp列车和普通线列车并线时，慢车总会挡住快车

**Additional Information**

**Comment by jonathanqwq** [comment]
@jonafanho

**Comment by BDark000** [comment]
四线化吧，都玩麦块了还用计较成本吗（）
不然，自己去算后面区间的快车通过所需时间，再把慢车停靠时间加长到可以让后面的快车过头。
另外，不要总圈模组作者，人家会看的，只是整个mtr mod社群非常大，mtr mod功能也越来越多，除了增加功能外还要修bug，那非bug类的自然优先级低一些。要么，你也可以学java，自己试着改程式码，看能不能成，至少显得有些进度。
