### ISSUE TITLE
I haven't train in game

### ISSUE THREAD

**Issue by SaberaVR** [jonafanho/Minecraft-Transit-Railway#280]
Hello, I have problem. I can't view my train. My train isn't exist, but I have configured rail, depot, stops, and it isn't working. Can you help me? [https://drive.google.com/drive/folders/1LZzUdLZavNKGtWYmFp98LqjNPbm33t_e?usp=sharing](url) There are video.

**Comment by saleem0915** [comment]
I think that you might have the hide train option on
