### ISSUE TITLE
Dynamic view distance recommended.

### ISSUE THREAD

**Issue by TSStudio** [jonafanho/Minecraft-Transit-Railway#281]
在多人游戏使用时，高速行驶的列车会导致大量的区块加载，进而导致服务器CPU、内存、网络资源占用严重。  
In multiplayer mod, high speed trains cause huge chunk load process, which lead to heavy load of CPU,memory and bandwidth.  
希望能根据列车速度、服务器当前资源占用情况和玩家数量自动减小加载和传输给玩家的区块数量。也可以留一个可以手动调节的参数。  
In this case, I'm thinking if it is possible to decrease the view distance, base on train speed, server load, and the player count. A manually adjustable parameter is possible.  
甚至在必要时，完全停止玩家的区块加载，仅在到站时再加载区块。
If needed, completely stop transmitting chunks to the players, restart the process when arriving.

**Comment by HistoryButtsandCo10** [comment]
Feel free to join our discord server if you wish to make a suggestion, in there more people would get to view your suggestion; thanks!

Discord: https://discord.gg/s352myaz

**Comment by jonafanho** [comment]
I think this is beyond the scope of this mod. There are also server settings that do the same thing.
