### ISSUE TITLE
There are something wrong when 1.17.1 update to 1.18.1

### ISSUE THREAD

**Issue by WNCX** [jonafanho/Minecraft-Transit-Railway#287]
**Expected Behaviour**
There are something missing when my save update from 1.17.1 to 1.18.1
![2022-02-05_13 50 23](https://user-images.githubusercontent.com/70813274/152630608-b18ce48b-19e1-46e3-a569-e668a6bb10a7.png)
![2022-02-05_13 50 28](https://user-images.githubusercontent.com/70813274/152630610-1569c75a-0f9d-45a9-9585-178843d84691.png)
`These are screenhots from 1.18.1`
![2022-02-05_13 55 49](https://user-images.githubusercontent.com/70813274/152630642-a12bfdab-f819-4f89-8175-ab7fc76e6389.png)
![2022-02-05_13 55 53](https://user-images.githubusercontent.com/70813274/152630645-8752900a-5957-4a15-9fd3-2a548ae22e41.png)
`These are the original appearance which taking screenhots in 1.17.1`

**Environment**

- Minecraft Version:1.17.1 to 1.18.1
- Installed Mods:

-1.17.1
![image](https://user-images.githubusercontent.com/70813274/152630757-d0ca2b2c-e0e0-4f25-98ed-c786289f22ba.png)

-1.18.1
![image](https://user-images.githubusercontent.com/70813274/152630792-3f1952ce-a525-48e7-bda5-fa4b89f274a8.png)

**I hope this bug can be fixed in the near future, because I really want to play in 1.18.1 with my save, thankU very much.**

**Comment by Ultimate-USA-YT** [comment]
Thanks for your Report

**Comment by kettle-7** [comment]
Yeah this is a bug in minecraft, nothing we can do about it except hope they fix it in 1.18.2

**Comment by jonafanho** [comment]
https://bugs.mojang.com/browse/MC-241670
https://github.com/FabricMC/fabric/issues/1837
