### ISSUE TITLE
Depot path not generating

### ISSUE THREAD

**Issue by Cerquaas** [jonafanho/Minecraft-Transit-Railway#289]
**Expected Behaviour**
Train depot says "Path generated successfully." and train spawns

**Actual Behaviour**
Nothing happens, and it still says "Path not generated"

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Follow the official tutorial (Ep1)
2. Click the path not generated button

**Screenshots**
_Main Screen_
<img width="1909" alt="image" src="https://user-images.githubusercontent.com/66092565/152812833-953a8cf1-f364-4a02-bda6-d308da233598.png">
_Train Instructions_
<img width="1653" alt="image" src="https://user-images.githubusercontent.com/66092565/152812895-910c1917-3974-4c99-a2c6-724bf6314278.png">

**Environment**

- Minecraft Version: 1.18.1 Forge
- Installed Mods: Quark, Quark Oddities, AutoRegLib, WorldEdit, MTR, Architectury API

**Additional Information**
I followed the official tutorial, and I have tried this also with just MTR and its dependencies on Fabric.

**Comment by HistoryButtsandCo10** [comment]
Ah yeah, sorry this is a bug and might be fixed in the next release. Feel free to join our discord server; https://discord.gg/5CZqyXWp if you wish to talk about it further. Please go to the respective channel for our bugs. Thank you!

**Comment by jonafanho** [comment]
Fixed in the latest release
