### ISSUE TITLE
Path Generation Status Bug

### ISSUE THREAD

**Issue by xEdziu** [jonafanho/Minecraft-Transit-Railway#290]
# **Expected Behaviour**
Text should be Path Generated Successfully and button "Refresh Path" should be clickable

# **Actual Behaviour**
Path indeed is generated successfully acording to the logs:
![image](https://user-images.githubusercontent.com/50357817/152997372-f0fa2e1b-0a25-4468-9ac6-c41274caf5d1.png)
But on Dashboard status is still visible as shown:
![image](https://user-images.githubusercontent.com/50357817/152997536-fd424ac5-2343-4c35-b140-134cebed6ba3.png)

# **Reproduction Steps**
Steps to reproduce the behaviour:

1. Reload minecraft
2. Did changes to route
3. Reloading the server

# **Environment**

## Minecraft Version: 
- Minecraft 1.18.1 Forge

## Installed Mods:
![image](https://user-images.githubusercontent.com/50357817/152998193-e9540164-e919-4e2b-b12f-a32e0d4261e7.png)

**Comment by xEdziu** [comment]
UPDATE: after few hours and editing route once again it started working normally - I don't really know what that mean

**Comment by Kiritow** [comment]
This problem happened on our server today too. A simple minecraft server restart fixed it. :)

**Comment by ValkyrieStella** [comment]
I have the same problem.
