### ISSUE TITLE
Trash Bin Bug

### ISSUE THREAD

**Issue by xEdziu** [jonafanho/Minecraft-Transit-Railway#291]
**Expected Behaviour**
Textures shouldn't be transparent

**Actual Behaviour**
Textures in block are transparent, allowing too see through walls

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Reload game
2. Reload mod

**Screenshots**
![image](https://user-images.githubusercontent.com/50357817/152999240-e7e82471-f55b-4c01-aa7f-8b64e3bcd819.png)

**Environment**

- Minecraft Version: 1.18.1 Forge
- Installed Mods:
![image](https://user-images.githubusercontent.com/50357817/152999311-f5d2e998-ce38-4fb2-9a78-2247eed3b8b4.png)

**Comment by HistoryButtsandCo10** [comment]
This is quite a texture bug, please join our discord for us to approach and fix this bug. Thanks. 

https://discord.gg/4bqA2Gu5

**Comment by kettle-7** [comment]
This is fixed in the previews on Discord, if you can for any reason not join then you will need to wait for the release of beta-9.

**Comment by xEdziu** [comment]
As said, repaired in preview
