### ISSUE TITLE
Getting kicked out of train

### ISSUE THREAD

**Issue by xEdziu** [jonafanho/Minecraft-Transit-Railway#297]
**Expected Behaviour**
Unbothered ride in a train

**Actual Behaviour**
While on ride, my screen in-game started to "shake" and "flare" and I got kicked out of train

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Restart game
2. Restart server
3. Update path

**Screenshots / Video**
I've got a video on that:
https://drive.google.com/file/d/1LaXaCJINfLtlIM6ccEDmletB3-mEQxOv/view?usp=sharing

**Environment**

- Minecraft Version: 1.18.1 Forge 39.0.66
- Installed Mods:
![img](https://user-images.githubusercontent.com/50357817/152999311-f5d2e998-ce38-4fb2-9a78-2247eed3b8b4.png)

**Comment by jonafanho** [comment]
Hmm, it looks like the chunks are not loading... is this on a server?

**Comment by xEdziu** [comment]
Yea, confirmed - it is server problem, sorry for bothering
