### ISSUE TITLE
[MTR-1.10.2-2.1.1] crash when placing trains.

### ISSUE THREAD

**Issue by BuckTheWeasel** [jonafanho/Minecraft-Transit-Railway#3]
hi here 

I think i have a crash with Minecraft-Transit-Railway with Hwyla mod.

crashlog here: https://pastebin.com/h6G8bgxB

**Comment by jonafanho** [comment]
Hello @jve22 
Have you tried just using the Minecraft Transit Railway mod without the Hwyla mod? I can't really figure out what the reason for the crash is from the crashlog. Let me look into it further.

**Comment by jve22** [comment]
yes i tried it and it works i think when it crash when you look at it.

**Comment by jonafanho** [comment]
Hi, a new version of the mod was just released. Can you try it and see if the issue persists?
