### ISSUE TITLE
  Why was the train stuck in the tunnel

### ISSUE THREAD

**Issue by 566666666666789** [jonafanho/Minecraft-Transit-Railway#30]
**Expected Behaviour**

**Actual Behaviour**
A clear and concise description of what actually happened.
The train is stuck in the tunnel. No other trains leave
**Reproduction Steps**
Steps to reproduce the behaviour:

1.The train got stuck in the tunnel after setting up the line

**Crash Report**
Attach a crash report to the issue.

**Screenshots**

**Environment**

- Minecraft Version:1.16.5
- Installed Mods:MTR[beta-6]

**Additional Information**
Anything else you want to add?
![Minecraft_ 1 16 5 2021_4_23 星期五 12_15_06](https://user-images.githubusercontent.com/80515666/115818490-6d5a8880-a42f-11eb-9a25-e2a9550b9668.png)
![Minecraft_ 1 16 5 2021_4_23 星期五 12_15_18](https://user-images.githubusercontent.com/80515666/115818494-6f244c00-a42f-11eb-8c97-c0506b46af25.png)

**Comment by 566666666666789** [comment]
What kind of BUG is that

**Comment by 566666666666789** [comment]
这个怎么解决

**Comment by 566666666666789** [comment]
How to solve this problem

**Comment by jonafanho** [comment]
Thanks for your bug report. Can you provide more information, screenshots, etc?

**Comment by Eric28020** [comment]
Or use this command: 
/gamerule doDaylightCycle true

**Comment by 566666666666789** [comment]
![Uploading Minecraft_ 1.16.5 2021_4_23 星期五 12_15_06.png…]()
![Uploading Minecraft_ 1.16.5 2021_4_23 星期五 12_15_18.png…]()

**Comment by 566666666666789** [comment]
I think my second picture is very strange, because he can't randomly train!

**Comment by jonathanqwq** [comment]
你的轨道不应该用 [这里](https://github.com/jonafanho/Minecraft-Transit-Railway/wiki/Rails) 的轨道吗？你怎么用自带的呢？

**Comment by jonathanqwq** [comment]
你能把存档也发出来吗？

**Comment by 566666666666789** [comment]
NO

**Comment by jonathanqwq** [comment]
> NO

对了，一个建议哈，就是你的隧道可以拓展成五格高
以及，我估计这是轨道的问题

**Comment by 566666666666789** [comment]
No, I just used the track you said! It's just that the distance between the two orbital endpoints is too long, and it happens to be in the middle of the two orbital endpoints when shooting!

**Comment by 566666666666789** [comment]
不，我就是用的你说的轨道呀！这只是两个轨道端点距离太长了，拍摄时恰好是两个轨道端点的中间！

**Comment by jonathanqwq** [comment]
那就让作者来看吧

**Comment by 566666666666789** [comment]
你不觉得第二张图片很奇怪吗！

**Comment by jonathanqwq** [comment]
> 你不觉得第二张图片很奇怪吗！

有吗？

**Comment by 566666666666789** [comment]
正常时有随机列车选项和?写列车编号啊！

**Comment by 566666666666789** [comment]
按照我的感觉因该是地图太卡了

**Comment by jonathanqwq** [comment]
或者你可以试试分配多一点的RAM给minecraft

**Comment by 566666666666789** [comment]
RAM是什么？、

**Comment by jonathanqwq** [comment]
虚拟内存，你用的是什么启动器？

**Comment by 566666666666789** [comment]
更改为5000都不行，怎么办！

**Comment by jonafanho** [comment]
Is your gamerule doDaylightCycle set to true? If not, try doing that

**Comment by 566666666666789** [comment]
What is doDaylightCycle? Where to change?

**Comment by Eric28020** [comment]
Use this command:
/gamerule doDaylightCycle true

**Comment by 566666666666789** [comment]
All right! However, the card is the same as .PPT!

**Comment by 566666666666789** [comment]
And it's stuck in its original position and it's stuck again!

**Comment by 566666666666789** [comment]
The dashboard is still the same, there is a problem!

**Comment by 566666666666789** [comment]
How to do？

**Comment by 566666666666789** [comment]
？

**Comment by jonathanqwq** [comment]
你可以试试把顶调成四个高的🤦‍
这是没办法的办法

**Comment by 566666666666789** [comment]
我弄的五格高，还是PPT呀

**Comment by 566666666666789** [comment]
Still can't solve it
‘

**Comment by 566666666666789** [comment]
@jonafanho Still can't solve it

**Comment by jonafanho** [comment]
Try running the command `/time set 0`. This might clear some of the stuttering in the world. Also, I'm still not really sure what the problem is. Do you have additional screenshots? What version of the mod are you using?

**Comment by 566666666666789** [comment]
@jonafanho There are a total of five stations on this line. After the train arrived at the second station, it jammed when the door closed, and then the train bounced back to the starting point! What's the matter?

**Comment by jonafanho** [comment]
Maybe try removing the last platform rail and connecting it again. Also check that the rest of the route has paths connecting all the following platforms properly.

**Comment by 566666666666789** [comment]
@jonafanho Yes, I have done everything you said, but this problem still occurs

**Comment by jonafanho** [comment]
Hmm, do you want to send me the world? Perhaps I can take a look at it.

**Comment by linuxkettle** [comment]
The first comment says he has beta-6 installed, but those tracks in the screenshot are from vanilla minecraft.
