### ISSUE TITLE
The depot section is not working

### ISSUE THREAD

**Issue by Unknoa** [jonafanho/Minecraft-Transit-Railway#304]
**Expected Behaviour**
It says path generated

**Actual Behaviour**
It says path not found on line 1 between leftsang village and ABCD Bank.

**Reproduction Steps**
Steps to reproduce the behaviour:

1.Using The tutorial
2.Delete and readd the an depot 
3.quit and rejoin the game
![image](https://user-images.githubusercontent.com/89019214/154788229-6919d2e4-a751-4450-b2f1-9a494f564c09.png)

![image](https://user-images.githubusercontent.com/89019214/154788229-6919d2e4-a751-4450-b2f1-9a494f564c09.png)
**Screenshots**
.

**Environment**
Minecraft Fabric
- Minecraft Version:
- Minecraft Fabric 1.18.1
- Installed Mods:
Mtr mod latest beta world edit 
**Additional Information**
How do i fix this

**Comment by kettle-7** [comment]
you don't have tracks connecting those two platform rails. simple as that.
