### ISSUE TITLE
Add An on-off door prompt

### ISSUE THREAD

**Issue by Polish-ball-man** [jonafanho/Minecraft-Transit-Railway#31]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Example: I'm always frustrated when...
Can you add a hint
**Describe the solution you'd like**
Add A cue, such as: Please do not approach the door
**Additional Information**

**Comment by Eric28020** [comment]
There’s a [YouTube video](https://youtu.be/CKLKx9EF_E0) of this mod, but with the doors closing chime. Please Note that the uploader used the video editor to add in the door chime.

**Comment by 566666666666789** [comment]
你去玩一玩1.10.2版本的这个模组

**Comment by 566666666666789** [comment]
???

**Comment by a160052** [comment]
自問自答.....

**Comment by jonafanho** [comment]
This can be achieved with announcer blocks with resource packs.
