### ISSUE TITLE
Crashes in 1.18.1 Server while exploding with Platform Screen Doors

### ISSUE THREAD

**Issue by DreamUniverse843** [jonafanho/Minecraft-Transit-Railway#311]
**Expected Behaviour**
Normal Explosion Behaviour

**Actual Behaviour**
Server-side crashed.

**Reproduction Steps**
Steps to reproduce the behaviour:
1.Set a TNT beside a Platform Screen Doors
2.Light the TNT
3.Server Crashed...

**Crash Report**
Attach a crash report to the issue.
https://paste.ubuntu.com/p/f2PPNSVyNs/

**Screenshots**
![image](https://user-images.githubusercontent.com/53889721/155443085-90cbfb93-828c-443a-b5b2-cf41d7df9f11.png)
As image shows,while light the TNT the server will crash.

**Environment**
- Java:version "17.0.1" 2021-10-19 LTS
- Minecraft Version:1.18.1
- Installed Mods:
![image](https://user-images.githubusercontent.com/53889721/155443512-b7f94dcb-0392-4416-b327-6b457d839777.png)

**Comment by HistoryButtsandCo10** [comment]
Interesting results, this should not usually happen. Let me get back to you on this, and if you can, you may join our discord. Thanks.

**Comment by HistoryButtsandCo10** [comment]
Checked the crash report, the top part of the PSD, where the signs and stations names are usually situated, they are not meant to be blown up in a way.

**Comment by DreamUniverse843** [comment]
I know , but it could be a illegal operation to crash the server if someone blow it up on purpose.

**Comment by kettle-7** [comment]
There is a fix in the latest unofficial version。

**Comment by jonafanho** [comment]
Fixed in the latest release
