### ISSUE TITLE
Players bug out mid train ride and are left floating as the train continues

### ISSUE THREAD

**Issue by Navy737** [jonafanho/Minecraft-Transit-Railway#314]
**Expected Behaviour**
Train goes from point A to point B with players on board.
**Actual Behaviour**
Train goes from point A to point B but will randomly bug out and drop off players in the middle of the track.

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Get on train (on a server)
2. At some random point the train may or may not bug out and drop you off mid track.

**Crash Report**
No crash report

**Screenshots**
On train normally
![2022-03-02_11 44 32](https://user-images.githubusercontent.com/100435815/156408422-df94da11-2041-4ad7-9cb9-83a8bcf21af1.png)
Glitching starts to happen (the screenshots don't show it well, but the glitching looks like I'm constantly teleporting between where the glitching started, and where the train currently is)
![2022-03-02_11 44 35](https://user-images.githubusercontent.com/100435815/156408477-980ffc37-90ab-4a36-a58c-dc096deca072.png)
Glitching ends and I'm kicked out
![2022-03-02_11 44 36](https://user-images.githubusercontent.com/100435815/156408499-54bca2b7-bc03-41ad-bae1-38a260395684.png)
I'm left floating mid track
![2022-03-02_11 44 43](https://user-images.githubusercontent.com/100435815/156408516-3b3b8842-458b-4bc2-9c86-8f03b819785f.png)

**Environment**

- Minecraft Version: 1.18.1 forge 39.0.79
- Installed Mods:
[Just Enough Resources (JER) (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer)
[Music Maker Mod (by xerca0)](https://www.curseforge.com/minecraft/mc-mods/music-maker-mod)
[Inventory Sorter (by cpw)](https://www.curseforge.com/minecraft/mc-mods/inventory-sorter)
[Simple Voice Chat (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat)
[Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)
[Framework (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/framework)
[Cosmetic Armor Reworked (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)
[Collective (Forge) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
[Villagers Leashed! (by GentWorm)](https://www.curseforge.com/minecraft/mc-mods/villagers-leashed)
[Sneaky Tree Growing (by ConmineLP)](https://www.curseforge.com/minecraft/mc-mods/sneaky-tree-growing)
[Signpost (by Gollorum)](https://www.curseforge.com/minecraft/mc-mods/signpost)
[PlayerRevive (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/playerrevive)
[Better Fps - Render Distance[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance)
[Sophisticated Backpacks (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks)
[Measurements (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/measurements)
[Simply Light (by Flanks255)](https://www.curseforge.com/minecraft/mc-mods/simply-light)
[Tree Harvester (Forge) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/tree-harvester)
[FPS Reducer (by bre2el)](https://www.curseforge.com/minecraft/mc-mods/fps-reducer)
[DrawerFPS (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/drawerfps)
[Flywheel (by jozufozu)](https://www.curseforge.com/minecraft/mc-mods/flywheel)
[Terralith 2.0 ~ Overworld Evolved (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/terralith)
[GraveStone Mod (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/gravestone-mod)
[KleeSlabs (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/kleeslabs)
[CC: Tweaked (by SquidDev)](https://www.curseforge.com/minecraft/mc-mods/cc-tweaked)
[Create Deco (by talrey)](https://www.curseforge.com/minecraft/mc-mods/create-deco)
[Amplified Nether (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/amplified-nether)
[Moyai (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/moyai)
[Effortless Building (by Requioss)](https://www.curseforge.com/minecraft/mc-mods/effortless-building)
[Curious Elytra (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curious-elytra)
['Dustrial Decor (by BlueDuckYT)](https://www.curseforge.com/minecraft/mc-mods/dustrial-decor)
[Curios API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
[Crafting Tweaks (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/crafting-tweaks)
[Snow Under Trees (by bl4ckscor3)](https://www.curseforge.com/minecraft/mc-mods/snow-under-trees)
[Macaw's Bridges (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-bridges)
[Quark (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/quark)
[AutoRegLib (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/autoreglib)
[Quark Oddities (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/quark-oddities)
[Axes Are Weapons (Fabric/Forge) (by Fourmisain)](https://www.curseforge.com/minecraft/mc-mods/axes-are-weapons)
[Torchmaster (by xalcon)](https://www.curseforge.com/minecraft/mc-mods/torchmaster)
[Architectury API (Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-forge)
[Searchlight (& Wall Lights) (Forge) (by lizard_ofoz)](https://www.curseforge.com/minecraft/mc-mods/searchlight-forge)
[ChickensShed (by holmraven)](https://www.curseforge.com/minecraft/mc-mods/chickensshed)
[Mantle (by mDiyo)](https://www.curseforge.com/minecraft/mc-mods/mantle)
[MrCrayfish's Furniture Mod (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod)
[Valhelsia Core (by ValhelsiaTeam)](https://www.curseforge.com/minecraft/mc-mods/valhelsia-core)
[Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
[Macaw's Paintings (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-paintings)
[ForgeEndertech (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/forgeendertech)
[Illagers Wear Armor (by almightytallestred)](https://www.curseforge.com/minecraft/mc-mods/illagers-wear-armor)
[Advanced Hook Launchers (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/advanced-hook-launchers)
[Enchantment Descriptions (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions)
[FerriteCore (Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
[Tiny Redstone (by Danny_and_Son)](https://www.curseforge.com/minecraft/mc-mods/tiny-redstone)
[Selene Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[Mod Name Tooltip (by mezz)](https://www.curseforge.com/minecraft/mc-mods/mod-name-tooltip)
[Builders Crafts & Additions (Forge) (by MRHminer)](https://www.curseforge.com/minecraft/mc-mods/buildersaddition)
[Gauges and Switches (by wilechaote)](https://www.curseforge.com/minecraft/mc-mods/redstone-gauges-and-switches)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Guard Villagers (by almightytallestred)](https://www.curseforge.com/minecraft/mc-mods/guard-villagers)
[Iron Furnaces [FORGE] (by XenoMustache)](https://www.curseforge.com/minecraft/mc-mods/iron-furnaces)
[Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Distant Horizons: A Level of Detail mod (by James_Seibel)](https://www.curseforge.com/minecraft/mc-mods/distant-horizons)
[Cloth Config API (Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config-forge)
[MrCrayfish's Gun Mod (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/mrcrayfishs-gun-mod)
[Macaw's Windows (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-windows)
[Tiny Gates (by Danny_and_Son)](https://www.curseforge.com/minecraft/mc-mods/tiny-gates)
[Caelus API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/caelus)
[Moving Elevators (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/moving-elevators)
[Default Options (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/default-options)
[Aquaculture 2 (by Shadowclaimer)](https://www.curseforge.com/minecraft/mc-mods/aquaculture)
[Macaw's Doors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-doors)
[Macaw's Trapdoors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-trapdoors)
[Alex's Mobs (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)
[Supplementaries (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/supplementaries)
[Minecraft Transit Railway (by jonafanho)](https://www.curseforge.com/minecraft/mc-mods/minecraft-transit-railway)
[Croptopia [FABRIC/FORGE] (by thethonk)](https://www.curseforge.com/minecraft/mc-mods/croptopia-fabric)
[Valhelsia Structures (by ValhelsiaTeam)](https://www.curseforge.com/minecraft/mc-mods/valhelsia-structures)
[Windowlogging (by mc_Grimmauld)](https://www.curseforge.com/minecraft/mc-mods/windowlogging)
[Decorative Blocks (by stohun)](https://www.curseforge.com/minecraft/mc-mods/decorative-blocks)
[CreativeCore (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/creativecore)
[Storage Drawers (by Texelsaur)](https://www.curseforge.com/minecraft/mc-mods/storage-drawers)
[Curio of Undying (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curio-of-undying)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[FramedBlocks (by XFactHD)](https://www.curseforge.com/minecraft/mc-mods/framedblocks)
[Aquatic Torches (by realmayus)](https://www.curseforge.com/minecraft/mc-mods/aquatic-torches)
[Villager Names (Forge) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/villager-names)
[Macaw's Lights and Lamps (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-lights-and-lamps)
[Farsight [Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/farsight)
[Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
[JourneyMap (by techbrew)](https://www.curseforge.com/minecraft/mc-mods/journeymap)
[Nature's Compass (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/natures-compass)
[Macaw's Fences and Walls (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls)
[Neat (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/neat)
[NetherPortalFix (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/netherportalfix)
[Uppers (by vadis365)](https://www.curseforge.com/minecraft/mc-mods/uppers)
[Baubley Heart Canisters (by traverse_joe)](https://www.curseforge.com/minecraft/mc-mods/baubley-heart-canisters)
[Tinkers Construct (by mDiyo)](https://www.curseforge.com/minecraft/mc-mods/tinkers-construct)
[Better Animals Plus (by cybercat5555)](https://www.curseforge.com/minecraft/mc-mods/betteranimalsplus)
[Drink Beer (Forge) (by Lekavar)](https://www.curseforge.com/minecraft/mc-mods/drink-beer-forge)

**Additional Information**
I know It's a lot of mods but I don't think it's caused by any of them since this bug has only occurred while on a server. I copied the world file into singleplayer and it worked perfectly. Its not caused by any client-side mods either since I was still able to reproduce the bug without them.

**Comment by jonafanho** [comment]
Thanks for your report. What mod version are you using? beta-9-unofficial something?

**Comment by Navy737** [comment]
MTR-forge-1.18-3.0.0-beta-8

**Comment by jonafanho** [comment]
Please verify if this is fixed in the latest release, thanks!
