### ISSUE TITLE
PIDS not showing on station "Central" heading to "Gohkamah Town"

### ISSUE THREAD

**Issue by Neon4UltraPlays** [jonafanho/Minecraft-Transit-Railway#318]
**Expected Behaviour**
PIDS should work properly on the station.

**Actual Behaviour**
PIDS not showing destination.

Steps to reproduce the behaviour:
1. 

**Crash Report**
No crash reports, this is a non-crash report bug

**Screenshots**
![evidence!](https://user-images.githubusercontent.com/90380800/158360713-341c5a55-7cb2-4436-a9e3-e0cc96f4d4d8.png)
![evidence! 2](https://user-images.githubusercontent.com/90380800/158361203-2599d7fc-2505-4c6b-bda0-961e64ee07dc.png)

**Environment**

- Minecraft Version: Forge Optifine 1.16.5
- Installed Mods: ![mods](https://user-images.githubusercontent.com/90380800/158360448-184a5db5-fb59-4d51-9f30-214a3c30de56.png)

**Additional Information**
The train arrival projector isn't working too.

**Comment by kettle-7** [comment]
try put the pids above the apg

**Comment by Neon4UltraPlays** [comment]
what is apg

**Comment by Ultimate-USA-YT** [comment]
> what is apg

Automatic Platform Gates

**Comment by Neon4UltraPlays** [comment]
> try put the pids above the apg

doesn't work

**Comment by TingChangHang** [comment]
It so far from the rail

**Comment by jonafanho** [comment]
Your PIDS is probably too far, try and see if the latest version fixes it.
