### ISSUE TITLE
Add MTR high speed train to Forge/Fabric mod

### ISSUE THREAD

**Issue by Neon4UltraPlays** [jonafanho/Minecraft-Transit-Railway#319]
![high speed rail](https://user-images.githubusercontent.com/90380800/158362393-6f0a059c-1cb9-4c6a-8909-b656278d8825.jpg)
Hello, can you add the **high-speed train from MTR?** There are three types.

**Mini** - 9 blocks
**Small** - 19 blocks
**Normal sized** 24 blocks

**Comment by kettle-7** [comment]
Waiting for #242

**Comment by Ultimate-USA-YT** [comment]
Already being made
