### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by jonathanqwq** [jonafanho/Minecraft-Transit-Railway#32]
**Expected Behaviour**
the train goes to the next station

**Actual Behaviour**
the train disappeard at the first station and suddenly it appeard and go to the next station

**Reproduction Steps**
please use this map
[新的世界.zip](https://github.com/jonafanho/Minecraft-Transit-Railway/files/6284003/default.zip)

**Crash Report**
none

**Screenshots**
none

**Environment**

- Minecraft Version:1.16.5
- Installed Mods:mtr

**Additional Information**
no

**Comment by jonathanqwq** [comment]
@jonafanho

**Comment by 566666666666789** [comment]
You can extend 3 squares, because the platform track you put is too short!

**Comment by jonathanqwq** [comment]
是站台方块吗？还是站台轨道？
谢谢🙏



jonathan&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;网站：https://jonathanqwq.github.io


------------------ Original ------------------
From: 波兰球之人 ***@***.***&gt;
Date: Sat,Apr 10,2021 6:35 PM
To: jonafanho/Minecraft-Transit-Railway ***@***.***&gt;
Cc: Shi Jonathan ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [jonafanho/Minecraft-Transit-Railway] bug (#32)





 
You can extend 3 squares, because the platform track you put is too short!

**Comment by 566666666666789** [comment]
月台轨道

**Comment by jonathanqwq** [comment]
好滴

jonathan&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;网站：https://jonathanqwq.github.io


------------------ Original ------------------
From: 波兰球之人 ***@***.***&gt;
Date: Sun,Apr 11,2021 10:45 AM
To: jonafanho/Minecraft-Transit-Railway ***@***.***&gt;
Cc: Shi Jonathan ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [jonafanho/Minecraft-Transit-Railway] bug (#32)





 
月台轨道
