### ISSUE TITLE
Add this Pokémon train to TR

### ISSUE THREAD

**Issue by Neon4UltraPlays** [jonafanho/Minecraft-Transit-Railway#321]
![pokemon rail](https://user-images.githubusercontent.com/90380800/158560173-8abd7a25-5af3-4a09-8dee-96c4fbcde858.jpg)
Can you add this Pokemon train to your mod on all versions? It would make people download our mod.

**Additional Information**
TRT means "Transit Railway"

**Comment by Ultimate-USA-YT** [comment]
Make it Yourself

**Comment by TheBreadGuy102** [comment]
The mod won't be adding trains except HK MTR, NYC Subway and London Underground trains. Thanks.

**Comment by HistoryButtsandCo10** [comment]
Hello, this is one of the staff of the MTR Discord Server. We actually do have a discord server; with an active server and player base for pokemon-styled trains and stations.  Join our discord server and find "MetroMon"; however we still lack a train for any pokemon-related themes; you may join the server if you want to help out.

**Comment by minecraftLYC** [comment]
我能加入服务器吗
