### ISSUE TITLE
MOD 没中文

### ISSUE THREAD

**Issue by Yexiaowei11** [jonafanho/Minecraft-Transit-Railway#328]
使用的电脑系统是 Windows 7
版本是beta8

**Comment by TingChangHang** [comment]
I think you can go to discord download the previews version mod
这边建议你去discord下载测试版本试下

**Comment by kettle-7** [comment]
> 使用的电脑系统是 Windows 7
版本是beta8

Windows 7 is not supported anymore, I know its a big down grade but you'll need to use Windows 10 or 11

**Comment by jonafanho** [comment]
Fixed in the latest release
