### ISSUE TITLE
Add an airport train

### ISSUE THREAD

**Issue by 566666666666789** [jonafanho/Minecraft-Transit-Railway#33]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Example: I'm always frustrated when...
I have been using SP1900 instead of the airport train when building my airport railway line, it is too unreal!
**Describe the solution you'd like**
Add an airport train

**Additional Information**
Add this
![K411-E111_MTR_Airport_Express_22-06-2020](https://user-images.githubusercontent.com/80515666/114307588-f3fb9580-9b12-11eb-9de7-d8acf678c2d3.jpg)

**Comment by Eric28020** [comment]
The mod is still being developed AND the AEL A-Train is already in the todo list.

**Comment by Eric28020** [comment]
The mod is still being developed. AND the Airport Express Train is already in the todo list.

**Comment by Eric28020** [comment]
You know the mod is still being developed. AND the Airport Express Train is already in the todo list.

**Comment by Eric28020** [comment]
Not to mention [this video of the Airport Express train debut](https://youtu.be/MarsLcIVrjQ).
