### ISSUE TITLE
While at the end of the platform,the PSD can't show the Route Map entirely.

### ISSUE THREAD

**Issue by DreamUniverse843** [jonafanho/Minecraft-Transit-Railway#331]
**Expected Behaviour**
The top of the PSD should show the entire map like this:
![image](https://user-images.githubusercontent.com/53889721/161717844-6d3e081d-631c-4ac2-93bc-8c837b226603.png)

**Actual Behaviour**
The map is incomplete on the PSD at the end of the platform.
![image](https://user-images.githubusercontent.com/53889721/161718048-fd8a683c-2a84-485e-a57b-577be2f52695.png)

**Reproduction Steps**
Steps to reproduce the behaviour:

1.Set a Station and place a platform.
2.Put the PSD along the platform,and end it at the edge of the platform.
3.It occurs at the end of the platform.

**Crash Report**
It's not related to a crash.

**Screenshots**
Shown above.

**Environment**
- MTR version:beta-9-unofficial-9
- Minecraft Version:1.18.1-Fabric
- Installed Mods:
Cilent Side:
==========================================
ChiselsBits-fabric-1.18.1-1.2.77.jar
fabric-api-0.46.1+1.18.jar
joestu-client-mod-fabric-1.18-1.0.6.jar
MTR-fabric-1.18-3.0.0-beta-9-unofficial-9.jar
test.txt
Xaeros_Minimap_21.23.0_Fabric_1.18.jar
dynamic-fps-2.0.6.jar
enhancedblockentities-0.5+1.18.jar
EntityCulling-Fabric-1.3.3.jar
starlight-1.0.0+fabric.d0a3220.jar
lazydfu-0.1.2.jar
sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14.jar
ferritecore-4.0.0-fabric.jar
lithium-fabric-mc1.18.1-0.7.7.jar
item-model-fix-1.0.3+1.18.jar
chatlagfix-1.0.0.jar
worldedit-mod-7.2.8.jar
architectury-3.0.39.jar
cloth-api-2.0.54.jar
cloth-config-6.0.42-fabric.jar
indium-1.0.2-alpha2+mc1.18.1.jar
malilib-fabric-1.18.0-0.10.0-dev.26.jar
completeconfig-lib-1.3.3.jar
WI-Zoom-1.3-MC1.18.jar
animatica-0.3+1.18.jar
continuity-1.0.3+1.18.jar
fabric-optifine-capes-2.0.0.jar
RoughlyEnoughItems-fabric-7.0.339.jar
InventoryProfilesNext-fabric-1.18-1.1.8.jar
XaerosWorldMap_1.20.0_Fabric_1.18.jar
CustomSkinLoader_Fabric-14.13-SNAPSHOT-313.jar
fabric-carpet-1.18-1.4.56+v211130.jar
TweakMyClient-fabric-mc1.18-Snapshot-1.1.11+bba69f9.jar
Controlling-fabric-1.18.1-9.0.8.jar
litematica-fabric-1.18.0-0.9.0.jar
tweakeroo-fabric-1.18.0-0.11.0.jar
mcwifipnp-1.5.3-1.18-fabric.jar
easiervillagertrading-1.18-fabric0.43.1-1.5.4.jar
bsvsb-2.0.5.jar
InGameAccountSwitcher-Fabric-1.18-7.1.3.jar
chat-up-2.0.0.jar
auto_third_person-1.18-1.1.0.jar
imblockerfabric-1.0.17.jar
mousewheelie-1.8.0+mc1.18-pre5.jar
sodium-extra-mc1.18.1-0.3.8.jar
modmenu-3.0.0.jar
MemoryUsageScreen-1.17-1.2.jar
wthit-fabric-4.2.0.jar
Boat-Item-View-Fabric-1.18-0.0.3.jar
lambdynamiclights-2.1.0+1.17.jar
slight-gui-modifications-2.0.2.jar
enhanced_attack_indicator-1.0.2+1.18.jar
shulkerboxtooltip-3.0.5+1.18.jar
durabilityviewer-1.18-fabric0.43.1-1.10.2.jar
armorchroma-1.1.0.jar
chat_heads-0.5.1-fabric-1.18.jar
appleskin-fabric-mc1.18-2.2.0.jar
orderly-2.0.1-alpha.2+custom-1.18.jar
tooltipfix-1.0.4-1.18.jar
advancementinfo-1.18-fabric0.43.1-1.3.jar
minihud-fabric-1.18.0-0.19.0-dev.20211204.230657.jar
RandomTitle-Fabric-1.0.7.jar
iris-mc1.18.1-1.2.0-pre.jar
hatlist-1.2.jar
notenoughanimations-fabric-1.4.0-mc1.18-pre1.jar
3dSkinLayers-Fabric-1.3.1.jar
essential-client-1.18.1-1.1.2.jar
carpet-extra-1.18-1.4.56.jar
MasaGadget-fabric-1.18-rc3-2.0.7-alpha.114514.jar
can-i-mine-this-block-1.1.0.jar
MiniHUD-Injector-fabric-mc1.16-1.2.0+916ad27.jar
========================================
Server Side:
![image](https://user-images.githubusercontent.com/53889721/161719903-ad8b4e52-2ad5-4938-afd6-05c12648574a.png)

**Additional Information**
None,tks.

**Comment by Yeche0603** [comment]
Normally,  that board don't place maps according to how the PSD are being used in the reallife.
the maps and the PIS or so, things like these can only work proplly around the platform rail for about 5(maybe 6?) blocks, this defines which platform does the facility belongs to.
