### ISSUE TITLE
Designate rail segments one-way

### ISSUE THREAD

**Issue by 16-squared** [jonafanho/Minecraft-Transit-Railway#34]
**Is your feature request related to a problem? Please describe.**
Often, when trains encounter a station, they will reverse, which is glitchy(anyone in the vehicle is ejected, and the gangway is stretched), and take a humorously long route instead of taking a shorter route which does not require reversing. 

**Describe the solution you'd like**
Please introduce the ability to designate select stretches of rail as being one-way

**Additional Information**

**Comment by 566666666666789** [comment]
Sorry, I don’t know what you want to express!

**Comment by 16-squared** [comment]
I am hoping for a means of preventing trains from using a specific rail segment (between nodes) for a specific direction of travel. A possible way is by adding a rail node connector which, instead of changing the train's speed limit, prevents train movement between the two nodes that is moving from the second node of the segment to the first node of the second.

**Comment by linuxkettle** [comment]
That is to me a very valid request. I have the same problem too. So why is it closed?

**Comment by linuxkettle** [comment]
There are cases where it would be useful still, like my "Scenic Train" which is a twelve car M train that shares two very small sections of track with an urban line, and as a result follows the very not scenic urban route the whole way instead of the big loop.

Also, there is another use case at #59.
