### ISSUE TITLE
SIGN FONT CRASH

### ISSUE THREAD

**Issue by BLAZINGKAT** [jonafanho/Minecraft-Transit-Railway#342]
WHEN EVER I OPEN THE GAME AFTER IT CRASHED DUE TO THE CUSTOM FONT IT CRASHES NOW HOPEFULLY UNINSTALLING AND REINSTALLING WILL FIX IT

**Comment by HistoryButtsandCo10** [comment]
1.  Go to Mod Configuration 
2. Disable Fonts 
3. Done 

Not all computers can MTR Fonts
