### ISSUE TITLE
Add 3 train doors trains like Small train(has 4 train doors)&Mini train(has 2 train doors)

### ISSUE THREAD

**Issue by xiaobaimao233** [jonafanho/Minecraft-Transit-Railway#350]
I think 2 train doors trains are too small and 4 train doors are a bit long, so to add a 3 train doors trains is a good idea.

**Comment by HistoryButtsandCo10** [comment]
We try to make the trains as realistic as possible to their real counterparts, so feel free to model one instead.

**Comment by xiaobaimao233** [comment]
What...I mean this mod can add a new type of train like train's name(Small/Mini)<<<there

**Comment by xiaobaimao233** [comment]
And Small type train has 4 doors on the one side of a car of this train, like Small type, Mini type train has 2 doors on the one side of a car of this train, and they are only use the original model to stitch.

**Comment by jonafanho** [comment]
Probably out of scope for this mod; you can easily make a resourcepack for it as well using the existing models on GitHub
