### ISSUE TITLE
一个车库发出的车只能先跑一遍A路线，再跑一遍B路线。现实中一个车库可以给很多路线发车，并且这些车只跑它自己所属的路线。

### ISSUE THREAD

**Issue by CokeStudios** [jonafanho/Minecraft-Transit-Railway#351]
**Is your feature request related to a problem? Please describe.** 
We can set the train from the depots to run in routes. But the trains can only run in a route after run in another route if you want to send trains to many routes in one depot. 

**Describe the solution you'd like** 
We can set some of the trains in one depot running only in one route and some running only in another route.

**Comment by HistoryButtsandCo10** [comment]
You need seperate depots for seperate routes.

**Comment by kettle-7** [comment]
well yes, unless you have a turn back rail in the depot and add all the lines to train instructions

**Comment by CokeStudios** [comment]
> You need seperate depots for seperate routes.

In real world, we may need only 1 depot but seperate sidings for seperate routes (eg. branch line and main line).

**Comment by user111192** [comment]
> **您的功能请求是否与问题有关？请描述。** 我们可以设置从车站出发的火车在路线上运行。但是，如果您想在一个站点中将火车发送到多条路线，则火车只能在另一条路线上运行后运行。
> 
> **描述您想要的解决方案** 我们可以将一些列车设置在一个站点中仅在一条路线上运行，而另一些则仅在另一条路线上运行。

创建多个车厂
