### ISSUE TITLE
Add Cable cars, Cable Car rails, Cable Car platforms, Cable Car sidings

### ISSUE THREAD

**Issue by chortle3** [jonafanho/Minecraft-Transit-Railway#357]
Hello Minecraft MTR mod, I would like you to add cable cars, along with cable car-themed rails, platforms, etc. It is like the Ocean Park Cable Car and the Ngong Ping 360 Cable Car (Tung Chung)

![Cable Car concept](https://user-images.githubusercontent.com/94771839/169646993-551e5013-3828-4c2d-9e16-c0f0cc9ab4ec.jpg)

I would be delighted if you add this feature to MTR mod.

**Comment by Ultimate-USA-YT** [comment]
This is Already in the Mod

**Comment by chortle3** [comment]
> This is Already in the Mod

where

**Comment by kettle-7** [comment]
@chortle3 Please compile from the 3.0.1 branch or get the preview from our Discord server, only major releases get posted on CurseForge as it's a bit annoying to upload them.

**Comment by chortle3** [comment]
What version 3.0.1 branch? Where is it?

**Comment by chortle3** [comment]
**CABLE CAR IS RELEASED!**
https://minecrafttransitrailway.com/libs/3.0.1-unofficial-4-hotfix-1/MTR-forge-1.18.2-3.0.1-unofficial-4-hotfix-1.jar 1.18.2 FORGE
https://minecrafttransitrailway.com/libs/3.0.1-unofficial-4-hotfix-1/MTR-fabric-1.18.2-3.0.1-unofficial-4-hotfix-1.jar 1.18.2 FABRIC

**Comment by kettle-7** [comment]
yes, that was ages ago

**Comment by kettle-7** [comment]
> What version 3.0.1 branch? Where is it?

https://github.com/jonafanho/Minecraft-Transit-Railway/tree/3.0.1
