### ISSUE TITLE
Rien ne se sauvegarde

### ISSUE THREAD

**Issue by JigSaw13** [jonafanho/Minecraft-Transit-Railway#358]
J’ai installé le mod via Fabric 1.16.5, tout fonctionne parfaitement à l’exception que le mod ne se sauvegarde pas. 
a chaque redémarrage de la map, toutes les donnés (rails/Dépôt/Itinéraire/etc..) sont effacé et je dois tout recommencer.
Pouvez-vous m’aidez s’il vous plaît ?

**Comment by Ultimate-USA-YT** [comment]
Veuillez mettre à jour le mod
