### ISSUE TITLE
localhost:8888 網頁顯示HTTP ERROR 404 Not Found

### ISSUE THREAD

**Issue by DaiLyTyan** [jonafanho/Minecraft-Transit-Railway#368]
在localhost:8888上訪問提示HTTP ERROR 404 Not Found
![QQ截图20220526222035](https://user-images.githubusercontent.com/93910300/170508334-063c7023-ab44-4fb3-878b-6e999d21ee6d.jpg)
是確實存在的BUG問題還是我設定有出錯？

website localhost:8888 displays HTTP ERROR 404 Not Found.
Is that a real bug or i have some setting issues?

**Comment by jonafanho** [comment]
http://localhost:8888/index.html

**Comment by DaiLyTyan** [comment]
It's done. Thx.
