### ISSUE TITLE
Add Q-Train and R-Train

### ISSUE THREAD

**Issue by XHG78999** [jonafanho/Minecraft-Transit-Railway#371]
**Is your feature request related to a problem? Please describe.**
New trains come to MTR these day. Q-Train now run at Tsuen Wan Line, and R-Train works at East Rail Line.
R-Train made from Korea, and Q-Train made from CNR Sifang EMU.

**Describe the solution you'd like**
Add MTR Q-Train and R-Train Model.

**Additional Information**
Q-Train: https://m.youtube.com/watch?v=HKt7uoYR3dw
R-Train inside: https://m.youtube.com/watch?v=f6nv6hIkQi0&t=186s
Sorry, but there are no much infomation there.

**Comment by DeadBoy2537** [comment]
R-Train已经有了，在unofficial-4里（首次出现在哪个版本不是很清楚）

**Comment by kettle-7** [comment]
already completed

**Comment by XHG78999** [comment]
Ehhh....hope that there will be a release about it.
