### ISSUE TITLE
广播器出现的问题。 The issue with Announcer.

### ISSUE THREAD

**Issue by DeadBoy2537** [jonafanho/Minecraft-Transit-Railway#372]
当"在聊天室显示「下一站」信息"设置为关闭时，广播器无法在聊天中显示信息。
这是一个漏洞吗？
另外，可以添加一个站台广播器吗？

When "Show 'next station' messages in chat" is set to Off, Announcer cannot display information in chat.
Is this a bug?
In addition, can you add an Announcer for Platform?

**Comment by kettle-7** [comment]
This is intentional, and no, we don't need announcer for platforms, just use command block with /playsound or /tellraw, along with the schedule sensor.

**Comment by DeadBoy2537** [comment]
> 这是故意的，不，我们不需要平台播音员，只需使用带有 /playsound 或 /tellraw 的命令块，以及时间表传感器。



> This is intentional, and no, we don't need announcer for platforms, just use command block with /playsound or /tellraw, along with the schedule sensor.

ok thanks
