### ISSUE TITLE
The content displayed incorrectly after opening the Railway System Map page.

### ISSUE THREAD

**Issue by murongyuanye** [jonafanho/Minecraft-Transit-Railway#374]
**Actual Behaviour**
When I start the server, open the Railway System Map page, and enter the local address + port in the LAN, the content can be displayed normally. But when I enter the domain name or IP address, there is only "refresh" and search box on the page after opening.

**Crash Report**
The game didn't crash.

**Screenshots**
![Screenshot_20220530-233407_Samsung Internet](https://user-images.githubusercontent.com/101809483/171025542-437e7713-2882-476b-b60a-e619cddcec1a.png)

**Environment**

- Minecraft Version: 1.16.5
- Server: Mohist-1.16.5-995
- Forge Version: 36.2.35

- Installed Mods:
MTR-forge-1.16.5-3.0.0
blockcarpentry-1.16-0.4.0
car-1.16.5-1.0.17
chiselsandbits-1.0.63
designer-modeling-1.16.5-1.0.0
forestry-1.16.5-6.0.11
InventoryProfilesNext-forge-1.16-1.3.6
ironchest-1.16.5-11.2.21
Mantle-1.16.5-1.6.157
Neat+1.7-27
obfuscate-0.6.3-1.16.5
Patchouli-1.16.4-53.2
plane-1.16.5-1.1.2
TConstruct-1.16.5-3.3.4.335
timeless_and_classics-gun_mod-0.1.4.1-1.16.5
Xaeros_Minimap_22.7.0_Forge_1.16.5

-Installed Plugins:
worldedit-bukkit-7.2.10
Vault-1.7.3
Slimefun-v2022.05-release
Residence5.0.1.6
QuickShop-5.1.0.7
Multiverse-Core-4.3.1
LuckPerms-Bukkit-5.4.25
EssentialsX-2.19.4
CMILib1.1.2.5
Auto-Tune-0.13.0

**Comment by kettle-7** [comment]
I hear it doesn't work very well on the Chinese Mainland...

**Comment by murongyuanye** [comment]
As you know, Google is only available for Google Translate, Chrome and Android developers in Chinese Mainland. 
(Actually Github sometimes works and sometimes fails to load...)
But the CDN used by Railway System Map claims to be available in Chinese Mainland, maybe not for this reason...
“jsDelivr is the only public CDN with a valid ICP license issued by the Chinese government, and hundreds of locations directly in Mainland China.”

**Comment by DeadBoy2537** [comment]
现已知VIA浏览器无法访问，Chrome应该是可以的，至少我这可以(

**Comment by murongyuanye** [comment]
我在手机上用的是三星浏览器（Chromium内核），群里帮忙测试的人用的是新版edge，都加载不出来...
I am using the Samsung browser (Chromium kernel) on my mobile phone, and the people in the group who help test are using the new version of edge, neither of these can be loaded...

**Comment by DeadBoy2537** [comment]
> 我在手机上用的是三星浏览器（Chromium内核），群里帮忙测试的人用的是新版edge，都加载不出来... I am using the Samsung browser (Chromium kernel) on my mobile phone, and the people in the group who help test are using the new version of edge, neither of these can be loaded...

换下浏览器UA看看
