### ISSUE TITLE
Add route option to avoid unused platforms

### ISSUE THREAD

**Issue by TJCPlays** [jonafanho/Minecraft-Transit-Railway#375]
**Is your feature request related to a problem? Please describe.**
I have a large station with 40 platforms across 4 floors, with a sort of roundabout of rails going around it to allow for access to every platform, from anywhere on the rail line; but the trains, when making their way to the necessary platform to stop at, cut through the other platforms instead of going around the outside like I would like them to.

**Describe the solution you'd like**
An "Avoid Unused Platforms" option in the route settings or depot settings that, when checked, would cause the route to, if possible, find another path between stations that does not include passing through another platform that it doesn't stop at.
**Alternate Solution:** Allow for manually choosing which rails the route should take, rather than it just being automatically determined.

**Comment by jonafanho** [comment]
I feel like this can be achieved by making the outer rail a higher speed, so that trains will always prioritise it when pathfinding.
