### ISSUE TITLE
Custom textures not working with small and mini trains

### ISSUE THREAD

**Issue by TJCPlays** [jonafanho/Minecraft-Transit-Railway#376]
**Expected Behaviour**
Texture loads properly

**Actual Behaviour**
The train still uses the carriage length of the regular size train, and only loads the model of the smaller selected size in the middle of the carriage, leaving empty gaps between the end of the model and the connector model.

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Create a custom texture for a train that has small and/or mini variants
2. Set the base train type for the custom train to the small/mini variant

**Crash Report**
Attach a crash report to the issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/104585300/171244499-807b81e8-c186-4a63-9132-dbe3a205bbaa.png)

**Environment**

- Minecraft Version: 1.18.1
- Installed Mods:
 - [1.18.1]+SecurityCraft+v1.9.0.2-beta1.jar
 - architectury-3.9.57.jar
 - betterboats-1.1.4.jar
 - car-1.18.1-1.0.2.jar
 - create-mc1.18.1_v0.4d.jar
 - flywheel-forge-1.18-0.6.0.jar
 - jei-1.18.1-9.2.1.69.jar
 - journeymap-1.18.1-5.8.1.jar
 - MapFrontiers-1.18.1-2.1.4.jar
 - minecraft-comes-alive-7.2.1+1.18.1-forge.jar
 - moreminecarts-1.4.2.jar
 - MTR-forge-1.18-3.0.0.jar
 - MTR-LU-Addon-forge-1.18.2-3.0.0-1.0.14.jar
 - OptiFine_1.18.1_HD_U_H5.jar
 - plane-1.18.1-1.0.0.jar
 - thutcore-1.18.1-8.7.0.jar
 - worldedit-mod-7.2.9.jar

**Additional Information**
Anything else you want to add?

**Comment by jonafanho** [comment]
Is this still an issue? Please try with the latest version of the mod and reopen this issue if it still persists.
