### ISSUE TITLE
Add different types of mesh track to the game

### ISSUE THREAD

**Issue by Moo-Cow-News** [jonafanho/Minecraft-Transit-Railway#378]
I think it would be cool if we get different type of mesh track to the game. For an example, we may have standard track, standard track with catenary, third rail track, fourth rail track (e.g: London Underground) etc.

I think this would be a cool feature to go with some of the underground trains and some of the trains that run on caternary or third rail.

**Comment by jonafanho** [comment]
Similar to #125
