### ISSUE TITLE
Visual issue/incompatibility with Pehkui

### ISSUE THREAD

**Issue by epmgr** [jonafanho/Minecraft-Transit-Railway#381]
**Expected Behaviour**
Tracks and trains being rendered on their normal level (relatively to the respective nodes)

**Actual Behaviour**
Tracks and trains dipping 1.5 below the ground when in 1st person & changing position relatively to the player's position when in 3rd person.

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Place a section of track with highlighted mods below installed.

**Environment**

- Minecraft Version: 1.18.2 fabric 0.14.6
- Installed Mods: 
MTR_3.0.1_unofficial-5
LU_addon_1.0.17
Joban_1.1.1
Quartz Elevator 2.1.1
Fabric API 0.54.0
FL Kotlin 1.7.4
Architectury 4.4.68
SmoothBoot 1.7.0
LazyDFU 0.1.2
Not Enough Crashes 4.1.6
Not Enough Animations 1.6.0
ModMenu 3.2.2
Bad Packets 0.1.2
wthit 4.10.3
REI 8.2.470
Inv Control Tweaks 1.3.13
Xaero Minimap 22.9.0
Xaero WorldMap 1.23.1
Sodium 0.4.1
Sodium Extra 
Reese's Sodium Options
Indium 1.0.3
Krypton 0.1.9
Lithium 0.7.10
Phosphor 0.8.1
LambdaBetterGrass 1.2.3
LambDynamicLights 2.1.0
WorldEdit 7.2.10
Worldedit CUI .01
Time & wind 1.4.2
BetterThirdPerson 1.7.3
Bits and Chisels 2.6.8
CaffeineConfig 1.1.0
ClothConfig 6.2.62
Clumps 8.0.0+8
Continuity 1.1.0
DynamicFPS 2.1.0
FerriteCore 4.2.1
EBE 0.6
MineGate 1.2.2
TechReborn 5.2.0
Paintings++ 9.1.2.1
**Pehkui 3.3.2** (removal found to have fixed the issue)

**Comment by Proofeek** [comment]
This bug appeared in 3.0.1 unofficial 4. 
Unofficial 3 works fine with Pehkui.

**Comment by jonafanho** [comment]
@epmgr @Proofeek Fixed in 3.1.3!

**Comment by epmgr** [comment]
> Fixed in 3.1.3!

🥳🥳🥳 Thanks
