### ISSUE TITLE
Passengers on trains

### ISSUE THREAD

**Issue by ChaoDee** [jonafanho/Minecraft-Transit-Railway#383]
How about we add passenger NPCs to the mod! First the passengers will spawn as a data file in front of one of the ticket barriers in one of the stations, then they will go find a path to one of the PSDs or APGs and line up there. Once the PSDs or APGs are fully opened, they'll be commanded to go into the train and stand at a random position in the train. Then they'll leave at one of the station the route will stop at. If they didn't exit the train all the way to the terminus stop, they'll be forced to exit the train at the last stop. Once they arrived at their "destination", they'll find the closest PSD or APG to exit the train then will have 50% chance of either exiting the station via pathfinding to the nearest ticket barrier, or pathfinding to interchange another route in the same station. But if that station is not an interchange station the passengers will find a path to the nearest shop (which can be placed down and be customized with different colours) and stay there for 10-30 in game minutes, then exit the station via pathfinding to the nearest ticket barrier. Also, since it's a data file that means you can't push them like you can with mobs.

**Comment by kettle-7** [comment]
Please, before you make a suggestion see if it has already been suggested. iirc this is the third github issue requesting this and there's been a number on Discord too.

**Comment by ChaoDee** [comment]
> Please, before you make a suggestion see if it has already been suggested. iirc this is the third github issue requesting this and there's been a number on Discord too.
I know, but the problem is I got banned in the server for ABSOLUTELY NO REASON.

**Comment by Ultimate-USA-YT** [comment]
> > Please, before you make a suggestion see if it has already been suggested. iirc this is the third github issue requesting this and there's been a number on Discord too.
> > I know, but the problem is I got banned in the server for ABSOLUTELY NO REASON.
You Were Banned for Ban Evasion

**Comment by ChaoDee** [comment]
> > > Please, before you make a suggestion see if it has already been suggested. iirc this is the third github issue requesting this and there's been a number on Discord too.
> > > I know, but the problem is I got banned in the server for ABSOLUTELY NO REASON.
> > > You Were Banned for Ban Evasion

Bruh can someone unban I did nothing wrong 😐

**Comment by jonafanho** [comment]
Related to #307
