### ISSUE TITLE
Add planes to MTR mod

### ISSUE THREAD

**Issue by Neon4UltraPlays** [jonafanho/Minecraft-Transit-Railway#384]
![A330-300_RR_white](https://user-images.githubusercontent.com/90380800/172979786-3bbc0583-679c-41cb-903e-3ba40eaf4571.jpg)
![737-800_white_winglets](https://user-images.githubusercontent.com/90380800/172979794-735837d1-e539-4158-81ac-8bae18ddccca.jpg)
Can you add planes to the Minecraft Transit Railway mod?
Since there are cable cars, trains, boats,
You must add planes this time!
Add A330s and B737s and add Plane rail nodes!

**Comment by Ultimate-USA-YT** [comment]
No

**Comment by notmyfault1829** [comment]
> 

Why not? The point is I want working planes!

**Comment by notmyfault1829** [comment]
> No

I just want working planes to be added, maybe your being selfish to people

**Comment by kettle-7** [comment]
> > No
> 
> I just want working planes to be added, maybe your being selfish to people

or maybe you are? this mod called mincefart transit **railway** for a reason, and the boats were only there to pave the way to buses.

**Comment by kettle-7** [comment]
As cherbert pointed out, the more different modes of transport you add the less time is put towards what is the focus of the mod. Jona would spend all his time fixing plane bugs and not have time to improve trains. If you're willing to code it in and fix any related bugs then go ahead and slap it in a pull request. Otherwise, I suggest to appreciate the effort people have put into the mod, rather than what they haven't done.

**Comment by chortle3** [comment]
> > > No
> > 
> > 
> > I just want working planes to be added, maybe your being selfish to people
> 
> or maybe you are? this mod called mincefart transit **railway** for a reason, and the boats were only there to pave the way to buses.

mincefart? lol

**Comment by chortle3** [comment]
> or maybe you are? this mod called mincefart transit **railway** for a reason, and the boats were only there to pave the way to buses.

mincefart? lol

**Comment by Neon4UltraPlays** [comment]
> As cherbert pointed out, the more different modes of transport you add the less time is put towards what is the focus of the mod. Jona would spend all his time fixing plane bugs and not have time to improve trains. If you're willing to code it in and fix any related bugs then go ahead and slap it in a pull request. Otherwise, I suggest to appreciate the effort people have put into the mod, rather than what they haven't done.


I agree. All the work Jonathan Ho has done; he is exhausted from all the work he has done. Maybe it is time to help Jonathan Ho with his MTR mod. **Maybe he can hire more people to work for Minecraft Transit Railway. Alternatively, the community can help by making addons for the mod.** Minecraft Transit Railway brings transportation to the game with easy configuration and attractive characteristics.

**Comment by kettle-7** [comment]
> *hire more people to work for Minecraft Transit Railway*
>
I don't suppose you know where the money will come from...

That aside, you can contribute to the mod via this GitHub repo, but few
people both have the time and are willing to use it for this. Also with the
code-base changing fairly frequently you need to do it relatively quickly,
or be prepared to need to change the code often.

Anyway, as I have mentioned people are welcome to add new features
themselves, but it can be counterproductive if Jonathan needs to spend lots
of time fixing bugs in your code.

**Comment by iLoadspecs** [comment]
No, JUST NO, like its ONE dev working on it you expect them to program a whole flight system and everything and jetbridges etc?
that would be hard even for a team of devs.

**Comment by iLoadspecs** [comment]
> > No
> 
> I just want working planes to be added, maybe your being selfish to people

the thing is, it would be a bit hard to make planes even if you have a large team of devs it would still take alot and be buggy

**Comment by kettle-7** [comment]
> No, JUST NO, like its ONE dev working on it you expect them to program a whole flight system and everything and jetbridges etc? that would be hard even for a team of devs.

we kinda have 18 devs depending on how you count but it's still a massive undertaking

**Comment by kettle-7** [comment]
anyways this is best in a different mood

**Comment by iLoadspecs** [comment]
> > No, JUST NO, like its ONE dev working on it you expect them to program a whole flight system and everything and jetbridges etc? that would be hard even for a team of devs.
> 
> 
> 
> we kinda have 18 devs depending on how you count but it's still a massive undertaking

oh didnt know lulz

**Comment by iLoadspecs** [comment]
still would be hard probs

**Comment by michelepestulnik** [comment]
What about only airports, fuel stations, runways and depots?

**Comment by kettle-7** [comment]
Well that's quite a handful, not to mention something that would be so much better as a separate mod...

**Comment by kettle-7** [comment]
Is Isaac here? He might be interested

**Comment by kettle-7** [comment]
You can get a flying dragon resource pack for now :~)

**Comment by XHG78999** [comment]
> You can get a flying dragon resource pack for now :~)

Good idea. I'll do it soon. [doge]

**Comment by Neon4UltraPlays** [comment]
Good news!
Planes will be released soon!

**Comment by Ultimate-USA-YT** [comment]
> Good news! Planes will be released soon!

They were out for a While

**Comment by kettle-7** [comment]
Planes got added last year...

**Comment by aaaaaaaaaaaa573** [comment]
Aaaaand they are released
