### ISSUE TITLE
Option in the mtr_custom_resources.json to disable door overlay for a certain train.

### ISSUE THREAD

**Issue by gdshu1337** [jonafanho/Minecraft-Transit-Railway#387]
**Is your feature request related to a problem? Please describe.**
Probably, because whenever I want to include a different door design in my train retextures, the door overlay just makes the window design look more ugly.
Below is an example of a TCL CAF-train retexture with a different door design, and the door overlay makes the doors look very weird.
![2022-06-10_20 06 40](https://user-images.githubusercontent.com/76419828/173060890-0e3b2db8-f178-42b2-9437-d0689ad3026f.png)

**Describe the solution you'd like**
I think a way of implementing this is a parameter in the mtr_custom_resources that allows the user to set the door overlay.
![image](https://user-images.githubusercontent.com/76419828/173061237-63b7953d-0a86-4e12-8a32-f6702f58e252.png)

Additionally, I hope that I'm not asking for too much, but it would be nice if custom trains can use a door overlay of something else. 
![image](https://user-images.githubusercontent.com/76419828/173062928-ce02a55d-fa95-4a2c-a0b6-29cce7bccbe4.png)
This is what it would look like.

**Additional Information**
I don't mean to beg or annoy Jonathan about this, I just feel like train retexturing could be better if this feature would be implemented. Keep up with the great work Jonathan!

**Comment by HistoryButtsandCo10** [comment]
So I'm assuming you do not want the overlay to be there? Or make adjustments. 

If that's the case, here are the steps. As these overlays arent really modelled right there exactly on the train. 

1. Find the door overlay pictures of that specific train,  you can find the .png here. 
https://github.com/jonafanho/Minecraft-Transit-Railway/tree/master/common/src/main/resources/assets/mtr/textures/sign 
So for this one, find m_train_left and m_train_right. There are two as one is representing one side of each door. 

2. Using any photo editing application, open the .png and remove the area which you dont want. You can also cut and move the signs - it's up to you.  Remember to never change or rename anything, everything is name-sensetive. Name it as is. 

3. Next, as you are making a Resource Pack in assets/mtr - make a seperate folder and name it textures. If there is one already proceed  with step below.

4. Make a folder inside the textures folder, name it "sign". 

5. Inside of it,  paste in your version of the door overlay pictures.

**Comment by jonafanho** [comment]
There is now a `render_door_overlay` property available in the JSON.
