### ISSUE TITLE
Consider providing a "server only" jar with smaller size

### ISSUE THREAD

**Issue by 3TUSK** [jonafanho/Minecraft-Transit-Railway#388]
**Is your feature request related to a problem? Please describe.**
Probably yes.  
We are preparing an in-game convention event in which the MTR mod has been requested. We have a functional modpack updating mechanism to allow us updating the mod list on the fly; however, we have to host/mirror the actual mod files because more than half of the mods used are built from the source. Having a mod with [size of ~50 MB](https://www.curseforge.com/minecraft/mc-mods/minecraft-transit-railway/files/3769151) may be a challenge for both of us event organizers and visiting players.

**Describe the solution you'd like**
Provide download options of 

  - A "server-only" jar where there is no `assets/` directory inside it. Possibly also exclude the `data/` directory?
  - A standalone resourcepack that includes the missing `assets/` (and possibly `data/`) directory, complementing the "server-only" jar. It should also be possible to use a customized resourcepack where only bare minimal resources are present, say, only one type of train is included, just for demo purpose.

The default download should still be the monolith jar.

**Additional Information**
An example of mod using this approach is [The Betweenland](https://www.curseforge.com/minecraft/mc-mods/angry-pixel-the-betweenlands-mod/files/3540284) mod. You can find a "server-only" version of the mod listed under "[a]dditional [f]iles" section.

**Comment by kettle-7** [comment]
Interesting idea, to remove assets/ server side, but data/ needs to stay,
that's server side files. In the meantime you can download the jar on a
client computer, extract it, remove assets/ and then zip it back up again.

**Comment by jonafanho** [comment]
@3TUSK This is a good idea. #392 adds server-only builds. You may access those via the [artifacts of each run](https://github.com/jonafanho/Minecraft-Transit-Railway/actions). I can also post them on CurseForge when I finish the new release.
