### ISSUE TITLE
Handrail model gets messed up when loaded in game

### ISSUE THREAD

**Issue by gdshu1337** [jonafanho/Minecraft-Transit-Railway#399]
**Expected Behaviour**
I modelled and textured a train with Blockbench and tried to load it in game. Everything worked like it's supposed to be, except for the handrails. The handrails looked like this on Blockbench:

![image](https://user-images.githubusercontent.com/76419828/174473316-2cc91628-42c8-4e22-94dd-f922150d34da.png)

However, they looked like this when loaded in game.
![2022-06-19_16 55 49](https://user-images.githubusercontent.com/76419828/174473417-496b8f7a-dbf9-4cc1-98a6-2dd0b4b22b86.png)

I made sure that the exact texture and model gets loaded and I uploaded the model and texture multiple times yet the same thing happens over and over again.

**Environment**

- Minecraft Version: 1.16.5
- Installed Mods:
![image](https://user-images.githubusercontent.com/76419828/174473371-489a80d6-f977-4fcd-b152-fb649f50b822.png)

**Additional Information**
I'm Mei Fwong#4462 by the way

**Comment by kettle-7** [comment]
So what do the handrails look like in game?
