### ISSUE TITLE
trains not loading properly

### ISSUE THREAD

**Issue by cmtekin** [jonafanho/Minecraft-Transit-Railway#401]
**Expected Behaviour**
Trains to be loaded properly

**Actual Behaviour**
After updating MTR-fabric-1.18-3.0.1 trains from previous saves look distorted. Also trains listed within the depots were not showing properly

**Reproduction Steps**
Steps to reproduce the behaviour:

1.

**Crash Report**
Attach a crash report to the issue.

**Screenshots**
![1](https://user-images.githubusercontent.com/47123268/174500699-80f2ed35-8cad-4314-943b-b829bfa73ba3.png)
![2](https://user-images.githubusercontent.com/47123268/174500720-5f86dfb0-5f68-4ced-bbae-a856a001a0a9.png)

**Environment**

- Minecraft Version:
fabric 1.18.1
- Installed Mods:
![image](https://user-images.githubusercontent.com/47123268/174500863-b062973b-2168-4792-8c81-e02eff676786.png)

**Additional Information**
Anything else you want to add?

**Comment by jonafanho** [comment]
Try selecting the train on the siding again.

**Comment by jonafanho** [comment]
Why do you have so many copies of the same mod?

**Comment by Ultimate-USA-YT** [comment]
And 2 MTR Mod's as ZIP

**Comment by cmtekin** [comment]
> Try selecting the train on the siding again.

I tried to reselect the train on the siding but not working. Also since some train names are missing I cannot properly point the same train for some cases. 

I tried to create a new siding and spawn a new train which results the same.

**Comment by cmtekin** [comment]
> Why do you have so many copies of the same mod?

Is this related to the solution? I deleted the old ones but it is still the same.

**Comment by jonafanho** [comment]
Can you show me your mods folder again?

**Comment by cmtekin** [comment]
> And 2 MTR Mod's as ZIP

Thanks for pointing out. I zip the one mods files to try the other mod.

**Comment by jonafanho** [comment]
Now can you try launching Minecraft again? Create a new siding

**Comment by cmtekin** [comment]
hi again,

actions taken after last thread:

1- Uninstall / reinstall minecreaft launcher
2- clean install fabric 1.19 and all mods in 1.19 version
3- update java

result is the same. Trains still summon with one million doors, list is not showing proper train names.

below is the ss of the mods folder.
![Ekran görüntüsü 2022-07-17 122922](https://user-images.githubusercontent.com/47123268/179392545-455988a1-6ac5-49c9-9af7-7000f80bba87.jpg)

below is the train
![222](https://user-images.githubusercontent.com/47123268/179392553-f1db9941-3b21-4d6a-bac6-0aca08b9ac16.png)

below is the list of trains
![333](https://user-images.githubusercontent.com/47123268/179392568-d6fd94bc-5b9d-4df7-9bf4-b22f38436ea8.png)

**Comment by cmtekin** [comment]
One other question, my son saw this passenger info display and looks for it. Could you let me know in which mod I can find this item?
![444](https://user-images.githubusercontent.com/47123268/179420530-531817e8-1de0-45b0-bd2a-b58b40915b19.png)

**Comment by kettle-7** [comment]
The passenger displays are from the Joban Client Mod, which unfortunately you can only download from the Joban discord server, and the latest unofficial preview of MTR should fix the issue, although you may need to remake the sidings.

Both links can be found in <https://dsc.gg/mtr>, where we can also offer faster support.

**Comment by Big-Cake-jpg** [comment]
Wait, you installed so many versions of Fabric API?

**Comment by jonafanho** [comment]
Is this still an issue? Please try with the latest version of the mod and reopen if needed.
