### ISSUE TITLE
Game constantly crashes on my MacOS

### ISSUE THREAD

**Issue by ChaoDee** [jonafanho/Minecraft-Transit-Railway#402]
My game crashed on a server everytime when I place down a train on a siding.
[latest.log](https://github.com/jonafanho/Minecraft-Transit-Railway/files/8936483/latest.log)

**Comment by jonafanho** [comment]
Remove all resource packs and try again.

**Comment by ChaoDee** [comment]
> Remove all resource packs and try again.

Still crashed

**Comment by jonafanho** [comment]
Try downloading the artifacts from this build and try again.
https://github.com/jonafanho/Minecraft-Transit-Railway/actions/runs/2543270789
