### ISSUE TITLE
Dynamic LCD

### ISSUE THREAD

**Issue by XHG78999** [jonafanho/Minecraft-Transit-Railway#403]
**Is your feature request related to a problem? Please describe.**
If there is an LCD, we can know what does the train is going and the next station without listening to the TTS and read the chatbar(sometimes it will be refreshed by chat)

**Describe the solution you'd like**
Add LCD to the train(configureable), and addition authors can set the UV position of the screen.

**Additional Information**

**Comment by jonafanho** [comment]
Similar to #143
