### ISSUE TITLE
Crashed when open the MTR font

### ISSUE THREAD

**Issue by XHG78999** [jonafanho/Minecraft-Transit-Railway#404]
**Expected Behaviour**
I change the settings in panel, set the MTR font to true, and then crashed.

**Actual Behaviour**
GPU drivers.

**Reproduction Steps**

**Crash Report**
OpenGL Error

**Screenshots**

**Environment**
GPU: Intel HD Graphics 520 (like a shit)

- Minecraft Version: 1.16.5
- Installed Mods: MTR 3.0.0

**Additional Information**

**Comment by ChaoDee** [comment]
It already said in the mod, some computers can't use the MTR fonts.
