### ISSUE TITLE
So many train

### ISSUE THREAD

**Issue by hzoniichan** [jonafanho/Minecraft-Transit-Railway#405]
![5555](https://user-images.githubusercontent.com/107871570/174633429-51e71125-6cb1-48a9-ba65-102614533b5e.png)

What can i do for this

**Comment by jonafanho** [comment]
Try selecting the train on the siding again.

**Comment by jonafanho** [comment]
I'm going to need more information than that... what mods do you have installed? What have you tried? What did you do in your siding?

**Comment by hzoniichan** [comment]
i installed thats mods 
![resim_2022-06-20_191241933](https://user-images.githubusercontent.com/107871570/174642879-2162d1b0-c8e0-43aa-b7a6-6500ba0334f0.png)
i didnt anything. just i made a train system and after i started system and this is the result

**Comment by 16-squared** [comment]
is the siding set to unlimited?

**Comment by CokeStudios** [comment]
Try to rechoose the train.

**Comment by jonafanho** [comment]
Duplicate of #401. Does this still persist in the latest version?
