### ISSUE TITLE
Banned on Discord server for no reason

### ISSUE THREAD

**Issue by ChaoDee** [jonafanho/Minecraft-Transit-Railway#408]
Idk why I was checking Discord and I saw I am not in the MTR discord server when I was supposed to be joined. And when I tried to join it says I am banned from the server. The MTR bot didn't say why I got banned, but can you just unban me, I did nothing wrong and I followed all of the rules in the Discord server. (Although I broke 1 rule once)

**Comment by jonafanho** [comment]
What is your birthday (and year)? You must comply with the Discord terms of service.

**Comment by ChaoDee** [comment]
My birthday is 24/7/2009 which means I'm 13 years old which ALSO means I can use discord. Therefore I shouldn't been banned on the Minecraft Transit Railway Discord Server as I follow every rules on the Discord ToS.

**Comment by Ultimate-USA-YT** [comment]
You Did Violate Discord ToS and Likely Permanently Banned from MTR

**Comment by jonafanho** [comment]
Thanks @ChaoDee, please let me know your Discord name and tag and I can let you back in.
