### ISSUE TITLE
When the train is about to arrive, report the station

### ISSUE THREAD

**Issue by Polish-ball-man** [jonafanho/Minecraft-Transit-Railway#41]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Example: I'm always frustrated when...
There was no report when the train was about to arrive. It was particularly unreal!
**Describe the solution you'd like**
When the train is about to arrive, report the station
**Additional Information**

**Comment by 566666666666789** [comment]
No one responded! ! !

**Comment by YPetremann** [comment]
Your issue is incorrectly filled.

**Comment by jonafanho** [comment]
Sorry, it takes a while for me to respond to these GitHub issues but I do read them. This could be added as an option in the game settings.

**Comment by JLC87** [comment]
it would be a good idea but be patient i guess

**Comment by linuxkettle** [comment]
I saw some audio files (just after jonafanho's m train announcement) that read the next station (although at the time only Town Centre), a message saying to mind the gap, and a message saying 'For the convenience of other passengers, please do not smoke, eat, or drink on LRT platforms, and inside train compartments. Thank you.'

If you're talking about a message in chat, you can enable it in **Railway Dashboard** > **Options**.

**Comment by jonafanho** [comment]
This can be done with the train schedule or redstone sensor blocks. Thanks for your suggestion!
