### ISSUE TITLE
希望作者大大能把优化做的好一点，我玩起来好卡！

### ISSUE THREAD

**Issue by gm6169** [jonafanho/Minecraft-Transit-Railway#410]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Example: I'm always frustrated when...

**Describe the solution you'd like**

**Additional Information**

**Comment by ZiYueCommentary** [comment]
要不要详细描述一下？卡不卡跟配置也有关系

MTR模组很复杂也很大，有点卡很正常。

**Comment by gm6169** [comment]
我玩的是fabric1.17.1版本，模组版本beta-9
配置：RTX960

**Comment by jonafanho** [comment]
As ZiYueCommentary said, please give more details, for example
- Screenshots or videos of your F3 menu
- List of mods installed
- Logs

**Comment by Simba98** [comment]
> 要不要详细描述一下？卡不卡跟配置也有关系
> 
> MTR模组很复杂也很大，有点卡很正常。

Perhaps you may try the newest version, now we have 3.0.0 release.

**Comment by gm6169** [comment]
> As ZiYueCommentary said, please give more details, for example
> 
> * Screenshots or videos of your F3 menu
> * List of mods installed
> * Logs

请稍等几天
Please wait for a few days.

**Comment by gm6169** [comment]
> > 要不要详细描述一下？卡不卡跟配置也有关系
> > MTR模组很复杂也很大，有点卡很正常。
> 
> Perhaps you may try the newest version, now we have 3.0.0 release.

emmmm

**Comment by gm6169** [comment]
> As ZiYueCommentary said, please give more details, for example
> 
> * Screenshots or videos of your F3 menu
> * List of mods installed
> * Logs

我可以先告诉你我安装了哪些模组
在这个链接下载文件：https://gm6169.lanzouw.com/i4mjO06x79de
密码：0000
由于模组有点多，所以做成了一个txt

**Comment by jonafanho** [comment]
Well if you have so many mods, lag is to be expected. Also, having too many optimisation mods might not be necessary. EntityCulling might not be compatible with Minecraft Transit Railway.

**Comment by gm6169** [comment]
> Well if you have so many mods, lag is to be expected. Also, having too many optimisation mods might not be necessary. EntityCulling might not be compatible with Minecraft Transit Railway.

okok，请问作者是中国人吗？我说英语有点不习惯

**Comment by ZiYueCommentary** [comment]
可以用只装了mtr模组的版本测试，如果还卡的话可能跟配置有关系。

另外一个区域内列车太多也会很卡

**Comment by gm6169** [comment]
> Well if you have so many mods, lag is to be expected. Also, having too many optimisation mods might not be necessary. EntityCulling might not be compatible with Minecraft Transit Railway.

我会尽量删除一些模组，看看会不会卡顿
