### ISSUE TITLE
In minecraft transit railway 3.0.1 (1.18.1), most things in the mod lose their textures

### ISSUE THREAD

**Issue by Mi6A16** [jonafanho/Minecraft-Transit-Railway#413]
**Expected Behaviour**

**Actual Behaviour**
A clear and concise description of what actually happened.

**Reproduction Steps**
Steps to reproduce the behaviour:

1.

**Crash Report**
Attach a crash report to the issue.

**Screenshots**

**Environment**

- Minecraft Version:
- Installed Mods:

**Additional Information**
Anything else you want to add?

**Comment by jonafanho** [comment]
Please at least give me a screenshot. I don't know what you are referring to.
