### ISSUE TITLE
Make players unable to sneak in the train

### ISSUE THREAD

**Issue by Raft08** [jonafanho/Minecraft-Transit-Railway#415]
**Is your feature request related to a problem? Please describe.**
When you sneak you're being droped from the train is it possible to disable sneak in the train?

**Describe the solution you'd like**
Disable sneak in the train

**Comment by kettle-7** [comment]
This is intentional, just in case train riding bug happens and you need to leave the train.

**Comment by Raft08** [comment]
Is it not possible to use like a command to leave the train?

**Comment by jonafanho** [comment]
It might be a good idea to add a custom keybinding for it, thanks for the suggestion

**Comment by jonafanho** [comment]
Functionality improved in #468
