### ISSUE TITLE
Avoid platform rail

### ISSUE THREAD

**Issue by squid233** [jonafanho/Minecraft-Transit-Railway#419]
**Is your feature request related to a problem? Please describe.**
The trains always pass the platform and it can block some other trains don't pass.

**Describe the solution you'd like**
```
Red = Fast Line
Blue = Slow Line
Arrow = Stop
Purple Arrow = Both stop
```
![image](https://user-images.githubusercontent.com/60126026/176987852-c792303c-d318-4c22-baed-cadf47055831.png)

**Additional Information**
no

**Comment by jonafanho** [comment]
Trains will prioritise rails with a higher speed. Use this to design local/express bypasses.
