### ISSUE TITLE
platform block placement doesn't align rotation with placement direction

### ISSUE THREAD

**Issue by JadianRadiator** [jonafanho/Minecraft-Transit-Railway#42]
**Expected Behaviour**
platform block placement doesn't align rotation with placement direction

**Actual Behaviour**
A clear and concise description of what actually happened.
platform block placement aligning rotation with placement direction

**Reproduction Steps**
Steps to reproduce the behaviour:

1. place platform block in a direction
2. place a platform block in a different direction

**Crash Report**
Attach a crash report to the issue.
not applicable

**Screenshots**
not applicable because a screenshot wouldn't show the issue

**Environment**

Minecraft Version:

- 1.16.5

Installed Mods:

- Architectury API (Fabric)
- Cloth Config API (Fabric)
- Fabric API
- Jumploader
- KubeJS Fabric
- KubeJS UI (Fabric)
- Minecraft Transit Railway
- Rhino
- Roughly Enough Items Fabric (REI)

**Additional Information**
Anything else you want to add?

**Comment by Eric28020** [comment]
![2021-04-25_17 03 01](https://user-images.githubusercontent.com/55635216/116015207-582b5880-a5ed-11eb-82f6-625bfb012ec4.png)

**Comment by YPetremann** [comment]
if you place blocks around your platform except where tracks will be, then platforms will align in the right direction.

**Comment by linuxkettle** [comment]
Does building from the master branch include untested patches? CurseForge server regularly crashes, so I build from source.

**Comment by jonafanho** [comment]
The master branch is the same as what is released on CurseForge. Preview builds are generated from beta branches.

**Comment by linuxkettle** [comment]
Okay, thanks for clarifying that. At the end of the platform, I either put a wall if the station is underground or a stone block, so maybe that's why I haven't noticed this issue.
