### ISSUE TITLE
Texture lost in v3.0.1 1.18.1

### ISSUE THREAD

**Issue by Mi6A16** [jonafanho/Minecraft-Transit-Railway#422]
**Expected Behaviour**

**Actual Behaviour**
A clear and concise description of what actually happened.

**Reproduction Steps**
Steps to reproduce the behaviour:

1.

**Crash Report**
Attach a crash report to the issue.

**Screenshots**

**Environment**

- Minecraft Version:
- Installed Mods:

**Additional Information**
Anything else you want to add?

**Comment by jonafanho** [comment]
Duplicate of #414, not enough information
