### ISSUE TITLE
如果有兩個入閘機，方向相同，一個是出站的，一個是入站的，但如果你出站後餘額不足，你會被困

### ISSUE THREAD

**Issue by Mi6A16** [jonafanho/Minecraft-Transit-Railway#424]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Example: I'm always frustrated when...

**Describe the solution you'd like**

**Additional Information**

**Comment by jonafanho** [comment]
Well then you can add vending machines, or don't do that?
