### ISSUE TITLE
Webserver not working

### ISSUE THREAD

**Issue by iLoadspecs** [jonafanho/Minecraft-Transit-Railway#429]
**Expected Behaviour**
To work normally

**Actual Behaviour**
"HTTP ERROR 404 Not Found"

**Reproduction Steps**
Steps to reproduce the behaviour:

1. start the server with the allocation setup
2. go to the webserver port and ip

**Crash Report**
Isnt Really a crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/81424453/178065355-f4754128-66e7-4921-b3a5-18c3dd1e9a5f.png)

**Environment**

- Minecraft Version: 1.19
- Installed Mods: ![image](https://user-images.githubusercontent.com/81424453/178065546-6f42716a-6691-465e-b65e-87810209439d.png)

**Additional Information**
Using revivenode

**Comment by jonafanho** [comment]
Please try adding `/index.html` at the end of the URL, for example `http://123.123.123.123:8888/index.html`

**Comment by iLoadspecs** [comment]
ok thank you
