### ISSUE TITLE
[Feature Request] The ability to see a parked/docked train's doors will be while parked/docked

### ISSUE THREAD

**Issue by JadianRadiator** [jonafanho/Minecraft-Transit-Railway#43]
### Is your feature request related to a problem? Please describe.
**A clear and concise description of what the problem is. Example: I'm always frustrated when...**
I can't tell where a train car's door will be when parked at a station

### Describe the solution you'd like
**A clear and concise description of what you want to happen.**
The ability to either

1. tell a train to park/dock stationary at a station without going through its route
2. or a tool that displays a "hologram" model of the train car on the station tracks in the position the actual train car would be in when parked/docked

### Additional Information
**Add any other context or screenshots about the feature request here.**
I am wanting this so that I can (at least try to) place the automatic doors right up againgst the train.

**Comment by 566666666666789** [comment]
机铁吗？怎么可能找不到车门？

**Comment by JadianRadiator** [comment]
I don't mean the door item you place.
I mean the doors of the trains in and of themselves.

**Comment by 566666666666789** [comment]
你难道开着谷歌生草机吗！

**Comment by JadianRadiator** [comment]
I used Bing translator... translation of your second reply made no sense to me.

**Comment by 566666666666789** [comment]
对了，一段文字用不同的翻译器，翻译出来的意思也是不同的！

**Comment by 16-squared** [comment]
JadianRadiator, send the trains along the routes before you build the screen doors. When the train stops at the stop, note where the doors are, and add the automatic doors. Eventually, some of this information(such as the fact that doors on the same car of a M train (or it's mini variant) are always 3 blocks apart) will passively enter your memory.

**Comment by jonafanho** [comment]
A holographic image of the train might be a good solution to this. I'll look into it.

**Comment by jonafanho** [comment]
This can now be done with a temporary depot and siding rail. Thanks for your suggestion!
