### ISSUE TITLE
Odd messages in server console

### ISSUE THREAD

**Issue by cpm9** [jonafanho/Minecraft-Transit-Railway#433]
**Expected Behaviour**
I expected weird messages missing timestamps to not appear in my server console

**Actual Behaviour**
Weird messages with no timestamp appear in the server console but not in the latest.log file

**Reproduction Steps**
Steps to reproduce the behaviour:
1. Launch forge server with transit railway and watch console, shortly after start up the weird messages appear

**Screenshots**
![image](https://user-images.githubusercontent.com/82549089/178670086-2d7c0cca-cadd-4c75-9c15-d20768d9a189.png)

**Environment**
- Minecraft Version: 1.18.2
- Installed Mods:
- transit railway 3.0.1, 
- forge 40.1.60
- minecolonies
- beyond earth
- croptopia

**Additional Information**
Minecraft Transit Railway data successfully loaded for minecraft:overworld
Dynamp is not loaded
BlueMap is not loaded
Squaremap is not loaded
Minecraft Transit Railway data successfully loaded for beyond_earth:glacio
Dynamp is not loaded
BlueMap is not loaded
Squaremap is not loaded
Minecraft Transit Railway data successfully loaded for beyond_earth:mercury
Dynamp is not loaded
BlueMap is not loaded
Squaremap is not loaded
Minecraft Transit Railway data successfully loaded for minecraft:the_nether
Dynamp is not loaded
BlueMap is not loaded
Squaremap is not loaded
Minecraft Transit Railway data successfully loaded for beyond_earth:glacio_orbit
Dynamp is not loaded
BlueMap is not loaded
Squaremap is not loaded
Minecraft Transit Railway data successfully loaded for beyond_earth:moon_orbit
Dynamp is not loaded
BlueMap is not loaded
Squaremap is not loaded
Minecraft Transit Railway data successfully loaded for beyond_earth:earth_orbit
Dynamp is not loaded
BlueMap is not loaded
Squaremap is not loaded
Minecraft Transit Railway data successfully loaded for beyond_earth:venus
Dynamp is not loaded
BlueMap is not loaded
Squaremap is not loaded
Minecraft Transit Railway data successfully loaded for beyond_earth:moon
Dynamp is not loaded
BlueMap is not loaded
Squaremap is not loaded
Minecraft Transit Railway data successfully loaded for beyond_earth:mars_orbit
Dynamp is not loaded
BlueMap is not loaded
Squaremap is not loaded
Minecraft Transit Railway data successfully loaded for beyond_earth:mercury_orbit
Dynamp is not loaded
BlueMap is not loaded
Squaremap is not loaded
Minecraft Transit Railway data successfully loaded for minecraft:the_end
Dynamp is not loaded
BlueMap is not loaded
Squaremap is not loaded
Minecraft Transit Railway data successfully loaded for ae2:spatial_storage
Dynamp is not loaded
BlueMap is not loaded
Squaremap is not loaded
Minecraft Transit Railway data successfully loaded for beyond_earth:venus_orbit
Dynamp is not loaded
BlueMap is not loaded
Squaremap is not loaded
Minecraft Transit Railway data successfully loaded for beyond_earth:mars
Dynamp is not loaded
BlueMap is not loaded
Squaremap is not loaded

**Comment by kettle-7** [comment]
Yeah, this is normal, it's just more noticeable because you have lots of dimensions. You can probably ignore it.

**Comment by cpm9** [comment]
Ok but could it be fixed? These logs aren't being sent properly, they don't appear in the latest.log and don't have a timestamp
