### ISSUE TITLE
Can't move when using this mod

### ISSUE THREAD

**Issue by JonnyTang1** [jonafanho/Minecraft-Transit-Railway#435]
**Expected Behaviour**
I should can move.

**Actual Behaviour**
I can enter the game and play for a while, but it will suddenly have strange light on the edge of the block(like the picture). After seeing the light, I can't move, turn my head or open the GUI and so on. However, the sound is OK and I still can hear the train stop in the station and open the door. I wait for a long time, and the issue still can't be solved. I just can close the game and restart it, but the issue still happen again.

**Reproduction Steps**
1.Get on or near the train.
2.Go into or near an elevator.

**Crash Report**
Can't move. No crash report.

**Screenshots**
![螢幕擷取畫面 2022-07-17 002018](https://user-images.githubusercontent.com/67949541/179364218-28805c08-4942-4b7b-8b24-5c9ad6655b66.jpg)

**Environment**

- Minecraft Version:1.18.2
- Installed Mods:
1. architectury-4.5.76-forge
2. configured-1.5.3-1.18.2
3. jei-1.18.2-9.7.0.209
4. MTR-forge-1.18.2-3.0.1
5. MTR-LU-Addon-forge-1.18.2-3.0.1-1.1

**Additional Information**
In my latest.log it says
" Saving and pausing game..."
[latest.log](https://github.com/jonafanho/Minecraft-Transit-Railway/files/9126236/latest.log)

**English is not my native language. I'm sorry about my disfluent English.**

**Comment by jonafanho** [comment]
This doesn't look like a crash, how much ram did you allocate to the game?

**Comment by JonnyTang1** [comment]
![螢幕擷取畫面 2022-07-17 095714](https://user-images.githubusercontent.com/67949541/179380781-51703eb3-b1bc-4a40-bb4e-6bd2806f3586.jpg)

**Comment by kettle-7** [comment]
That's definitely enough memory

**Comment by Big-Cake-jpg** [comment]
When you're playing in a singleplayer save and didn't open your game to LAN, this message `saving and pausing game` will always appear when you paused the game.

**Comment by JonnyTang1** [comment]
Excuse me. I followed your advice. While the issue still happened. How could I do?

**Comment by JonnyTang1** [comment]
Like this!
![螢幕擷取畫面 2022-07-17 234456](https://user-images.githubusercontent.com/67949541/179406052-2b1be0b6-f89c-4dbf-bf64-2853eef2b8d0.jpg)

**Comment by Big-Cake-jpg** [comment]
> Like this!
> 
> ![螢幕擷取畫面 2022-07-17 234456](https://user-images.githubusercontent.com/67949541/179406052-2b1be0b6-f89c-4dbf-bf64-2853eef2b8d0.jpg)
> 
> 

Looks like textures were broken. Try to reinstall Minecraft Trainsit Railway mod and add TextureFix mod. If it didn't work, try to reinstall your game or use old version of Fabric/Forge.

This problem can't reproduce on my game (Minecraft 1.18.2, Fabric Loader 0.13.3)

**Comment by jonafanho** [comment]
Please reopen if this issue persists.
