### ISSUE TITLE
Muiltiplayer Bugs

### ISSUE THREAD

**Issue by XHG78999** [jonafanho/Minecraft-Transit-Railway#438]
**Expected Behaviour**
Works like singleplayer.

**Actual Behaviour**
(Translate:)
The first player joined to the server will be the "Mod Controller" of MTR. (Custom Name:) )
1. When the "Mod Controller" use the dashboard to refresh it will works just in a second, but other players will show "Flushing" and then cannot success.
2. When the "Mod Controller" put a new rail, it will show in a second, but other players will show after 10-15 seconds and only can view one of the node.
3. When the "Mod Controller" get on the train/ferry/cable, it will works as normal, but other players cannot take it while the train start.
Cable is the same, but other player cannot take and will not take on when the cable on.
Maybe it is designed for permission controlling, but it is so terrible to other players.

**Reproduction Steps**
Just open a server and make at least 2 players in server.

**Crash Report**
Does not crashed.

**Screenshots**
*Not Nessary*

**Environment**
Any Version of MTR, Forge or Fabric.

- Minecraft Version: *Does not effected*
- Installed Mods: *Does not effected*

**Additional Information**
Copy from https://www.mtrbbs.top/forum.php?mod=viewthread&tid=538&extra=&_dsign=db9b2a6d.

**Comment by jonafanho** [comment]
Thank you so much for finding this bug! Thanks to @zbx1425's help, I'm working on a fix.

**Comment by kettle-7** [comment]
I have only noticed this on Forge, seen nothing on Fabric of it...
