### ISSUE TITLE
Misspelling translate on Chinese Version

### ISSUE THREAD

**Issue by Forest103** [jonafanho/Minecraft-Transit-Railway#44]
**Expected Behaviour**
In chinese, min should translate to "分鐘"
The follow is the chinese version in real life
![image](https://user-images.githubusercontent.com/83854276/117527114-12fb2380-affc-11eb-9337-d6988ae8fd00.png)

**Actual Behaviour**
However it translate to "分鍾"

**Reproduction Steps**
Not require

**Crash Report**
It haven't make crash

**Screenshots**
![2021-05-08_12 43 26](https://user-images.githubusercontent.com/83854276/117527037-7e90c100-affb-11eb-82b7-e1d90c4d5d95.png)
![2021-05-08_12 54 24](https://user-images.githubusercontent.com/83854276/117527161-8ac94e00-affc-11eb-8c04-00736279cd2e.png)

**Environment**

Minecraft Version:
- 1.16.5 (Fabric)

Installed Mods:
- Optifine
- OptiFabric
- Replay mod
- WorldEdit
- Xearo's map
- Xearo's minimap

**Additional Information**
No Additional Information

**Comment by jonafanho** [comment]
Thanks for spotting this! I actually fixed it in the beta-7 branch's code. It will be released along with beta-7. Feel free to try out the unofficial builds of beta-7 linked on the official Minecraft Transit Railway Discord server.
