### ISSUE TITLE
Metal side of rails not rendering/invisible

### ISSUE THREAD

**Issue by SmugSw2** [jonafanho/Minecraft-Transit-Railway#441]
### **NOTE : TITLE IS WRONG, THOUGHT THEY WEREN'T RENDERING AT ALL BUT IT TURNS OUT THEY RENDER, JUST WAY BELOW THE RAIL NODES**

**Expected Behaviour**
Able to see rails after connecting them

**Actual Behaviour**
I only see the wood, no rails on the sides

**Reproduction Steps**
Steps to reproduce the behaviour:

1.Get rail connector and rail node
2.Connect them , the rails are invisible

**Crash Report**
NA

**Screenshots**
### DONT MIND THIS IMAGE, THEY RENDER, JUST WAY BELOW THE NODES AS SEEN HERE
https://github.com/jonafanho/Minecraft-Transit-Railway/issues/441#issuecomment-1191101253 (or 2nd comment in this issue)
![2022-07-21_13 31 44](https://user-images.githubusercontent.com/96033110/180136948-8e2f3373-8506-4d1b-a793-0065ba3d19d3.png)

**Environment**

- Minecraft Version: 1.18.2 (Fabric)
- Installed Mods:
I have 300+ mods, will be hard to list them all but I will list down the ones that improve FPS in-case one of them is making the rails invisible
*FerriteCore
*EnhancedBlockEntities
*Sodium (and extras and more options / etc )
*Indium
*Lithium
*Cull Leaves
*C2ME (Concurrent Chunk Management Engine)
*EntityCulling-Fabric
*Starlight

**Additional Information**
Anything else you want to add?
Quickly edited this after I found out how dumb I am apparently

**Comment by Big-Cake-jpg** [comment]
Maybe you can try to remove Starlight.
Starlight wholly rewrites Minecraft's lighting engine so a couple of mods can't work with it.

**Comment by SmugSw2** [comment]
![2022-07-21_14 39 10](https://user-images.githubusercontent.com/96033110/180146316-9b881b07-4242-4307-bca3-cbe4a7dbe428.png)
Turns out i'm dumb, it's not that they aren't rendering/invisible

It's that they are rendering way below the nodes , gonna edit the main post , was even visible in the 1st screenshot (no idea how I didn't notice)

**Comment by Kenny-Hui** [comment]
Likely caused by Pehkui
https://github.com/jonafanho/Minecraft-Transit-Railway/issues/381

**Comment by SmugSw2** [comment]
ah that solved it , thanks!
