### ISSUE TITLE
Unable to Refresh Path

### ISSUE THREAD

**Issue by Mausthedog** [jonafanho/Minecraft-Transit-Railway#445]
Running minecraft forge 1.19 in Windows 10 PC. After following all the instructions in the official tutorial video to create stations, routes and depots, I click Refresh Path, but nothing happens. Any suggestions? 
![refresh path](https://user-images.githubusercontent.com/109832560/180581964-47ce86d4-0a6c-4cc6-881f-e27bdf75583d.png)

**Comment by kettle-7** [comment]
Could you show what is in the Edit Train Instructions?

**Comment by Mausthedog** [comment]
Here it is:
[cid:9c5c74f2-d756-45f4-b97a-b0eb1eb9c3b3]
________________________________

**Comment by Mausthedog** [comment]
![image](https://user-images.githubusercontent.com/109832560/181343105-7f17e1b1-55d2-46dc-b046-29471db491e3.png)
In case it didn't come through via email. :)

**Comment by kettle-7** [comment]
interesting

and does the line 1 use at least 2 stations?

because normally this is what shows if the train doesn't have at least 2 stations to go through

**Comment by Mausthedog** [comment]
Well, my son did have multiple stations but the screen showed 1/1 so I questioned if that meant only 1. He went in and did something and then the Refresh Path started working, so I guess we're fine now. Thanks so much for the help! He really loves MTR.
