### ISSUE TITLE
[1.19] Crash on load due to breaking changes in Forge

### ISSUE THREAD

**Issue by ProsperCraft** [jonafanho/Minecraft-Transit-Railway#447]
**Crash Report**
(https://gist.github.com/ProsperCraft/666db6e6a65b8a497cd6b9e3d3b1fba0)

- Minecraft Version: 1.19
- Installed Mods: reproduced with only MTR -

**Comment by jonafanho** [comment]
Forge 1.19 isn't stable yet. Please try using older versions of Forge and Architectury or using the preview versions on Discord.
