### ISSUE TITLE
log bug

### ISSUE THREAD

**Issue by lostopkk** [jonafanho/Minecraft-Transit-Railway#448]
**Expected Behaviour**
log clean

**Actual Behaviour**
https://www.toptal.com/developers/hastebin/odipiqoxaz.properties

- Minecraft Version:1.19

**Comment by Ultimate-USA-YT** [comment]
This Appears Normal

**Comment by lostopkk** [comment]
well, it doesn't give any problem in the game, but it floods the log a lot

**Comment by kettle-7** [comment]
Do you have the same issue if you replace modern elevators and escalators with regular mtr?
