### ISSUE TITLE
资源包创建器塞拉门

### ISSUE THREAD

**Issue by TingChangHang** [jonafanho/Minecraft-Transit-Railway#449]
MTR现在推出的资源包创建器，只能使用内藏门与外挂门，不能使用塞拉门。

但很多车辆都是塞拉门，却只能有仿造的或无法做出。

From:[https://www.mtrbbs.top/forum.php?mod=viewthread&tid=635&page=1&extra=#pid4727](url)

**Comment by SteveNotSet** [comment]
注：“塞拉门”在香港叫做“内嵌门”，在K-Train和CAF-Train上有使用

**Comment by jonafanho** [comment]
Duplicate of #406
