### ISSUE TITLE
Vehicles

### ISSUE THREAD

**Issue by MinecraftPerson** [jonafanho/Minecraft-Transit-Railway#451]
How do I spawn vehicles? I've tried everything.

**Comment by kettle-7** [comment]
I wouldn't be so sure. Make sure your siding is at least 26 blocks long, inside a depot area and follow the [wiki](https://github.com/jonafanho/Minecraft-Transit-Railway/wiki/).

**Comment by MinecraftPerson** [comment]
What is siding?

**Comment by Ultimate-USA-YT** [comment]
> What is siding?

You should Watch Jona's Tutorials

**Comment by saleem0915** [comment]
https://www.youtube.com/watch?v=KIsuRxNW3Lc&t=480s
The link for the MTR Tutorial
