### ISSUE TITLE
Mtr error bug

### ISSUE THREAD

**Issue by TLB337** [jonafanho/Minecraft-Transit-Railway#452]
**Expected Behaviour**

**Actual Behaviour**
A clear and concise description of what actually happened.

**Reproduction Steps**
Steps to reproduce the behaviour:

1.

**Crash Report**
Attach a crash report to the issue.

**Screenshots**

**Environment**

- Minecraft Version:
- Installed Mods:

**Additional Information**
Anything else you want to add?

**Comment by Ultimate-USA-YT** [comment]
How will we know what is wrong?

**Comment by kettle-7** [comment]
@TLB337 You have provided none of the requested information and we can't do anything about the bug. Please fill out the issue template, it's there for a reason.
