### ISSUE TITLE
Adding mph to the speedometer

### ISSUE THREAD

**Issue by saleem0915** [jonafanho/Minecraft-Transit-Railway#453]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Example: I'm always frustrated when...
When I use the mod, and I get in the train, I don't know what the speed it because it's only in meters/second and kilometers/second.
**Describe the solution you'd like**
An option that lets you pick your unit of measure.
**Additional Information**

**Comment by kettle-7** [comment]
Maybe there can be an imperial measurement setting, but miles doesn't make much sense in mincefart

**Comment by saleem0915** [comment]
Okay then

Thank you
