### ISSUE TITLE
Sided_Setup Error

### ISSUE THREAD

**Issue by Zetonium** [jonafanho/Minecraft-Transit-Railway#454]
**Expected Behaviour**
The mod to work

**Actual Behaviour**
When I attempted to open Minecraft i got mtr encountered an error during the sided_setup phase and I removed the mod and reinstalled it again, but it still didn't work

**Reproduction Steps**
I'm not sure

1.

**Crash Report**
latest log: https://pastebin.com/ttuZBhq6

crash report: https://pastebin.com/w7bB8KFL

**Screenshots**
![Screenshot (2)](https://user-images.githubusercontent.com/74768219/183269246-4cc5a9f3-a40e-4baf-95f8-dbb0fc5a0835.png)

**Environment**

- Minecraft Version: visible in crash report
- Mod List: visible in crash report

**Additional Information**
Anything else you want to add?

**Comment by jonafanho** [comment]
This is fixed in the Discord preview versions as well as the latest builds in GitHub actions.
