### ISSUE TITLE
Does MTR support Express trains?

### ISSUE THREAD

**Issue by saleem0915** [jonafanho/Minecraft-Transit-Railway#456]
I was just wondering if MTR supported trains passing the platform rail without stopping, like how express trains don't stop at all stations.

**Comment by Ultimate-USA-YT** [comment]
Yes

**Comment by saleem0915** [comment]
Thank you

**Comment by saleem0915** [comment]
How would I do this?

**Comment by kettle-7** [comment]
just not add certain platforms to the route

**Comment by saleem0915** [comment]
Okay Thank you
