### ISSUE TITLE
Railway spawns 2 blocks below

### ISSUE THREAD

**Issue by Shimumel** [jonafanho/Minecraft-Transit-Railway#457]
The entire train system works, the train spawns and moves from platform to platform and stops at each platform.

However, the problem is that it’s very buggy as when I place 2 rail nodes and connect them with tracks it spawns the rail track and train 2 blocks below the nodes. I accounted for this by placing 2 blocks above and the track now runs on the ground but now the platform has to be places 2 blocks above or else it will not open gates and when it does and I go inside it glitches me to the top and not inside the train where I can move about

I added the modpack to medieval MC 1.16.5 
please help

**Comment by kettle-7** [comment]
Please remove pehkui, it causes a known conflict.
