### ISSUE TITLE
Platform screen doors won't open

### ISSUE THREAD

**Issue by Shimumel** [jonafanho/Minecraft-Transit-Railway#458]
Hi. I've managed to get the railway working but when I place the platform screen doors where the train doors open they don't open. The platform doors remain closed but the train doors still open. Please help as I've followed the YouTube video for guidance but still doesn't work

**Comment by kettle-7** [comment]
Does the train sit for a while at the station after shutting the doors w

**Comment by Shimumel** [comment]
Yup

**Comment by jonafanho** [comment]
Any screenshots or videos?

**Comment by kettle-7** [comment]
> Yup

ah so it's probably desync

**Comment by kettle-7** [comment]
restarting the server will often fix it for a while but it'll come back again

**Comment by Shimumel** [comment]
> Any screenshots or videos?

I’m pregenerating the server right now, I’ll send screenshots and videos when it’s back up

**Comment by Shimumel** [comment]
> restarting the server will often fix it for a while but it'll come back again

Restarting didn’t fix it but I reckon it’s an issue with server lag cause it works perfectly fine in single player, guess I’ll just have to deal with no platforms. Unless there’s something else causing it
