### ISSUE TITLE
Trains take the wrong route

### ISSUE THREAD

**Issue by EhrenNick** [jonafanho/Minecraft-Transit-Railway#459]
Hello,

I have the following problem with the trains.
The trains always look for the wrong way to the station. They often drive a long way. Since I'm building a system with track triangles, it annoys me a lot because the trains always go wrong because of these triangles.

Is there any way to make the trains run correctly with these tracks?`

And yes my English is not the best :c

p.s I checked the existing lines to see if the right stops are connected. I couldn't discover anything.

**Comment by kettle-7** [comment]
Trains will prefer to take the track with the highest speed limit, then if there's multiple with the same speed limit they'll take the shortest distance to the next node. Other than setting the speeds though there's no way to change the path the train will take yet.

**Comment by jonafanho** [comment]
Any screenshots or track diagrams that can help me understand the issue better?

**Comment by kettle-7** [comment]
I'd imagine it's similar to CLR Green Horizons route going via Badlands Beach

**Comment by saleem0915** [comment]
Have you tried one-way rails?
