### ISSUE TITLE
TTS Improvement

### ISSUE THREAD

**Issue by XHG78999** [jonafanho/Minecraft-Transit-Railway#462]
**Is your feature request related to a problem? Please describe.**
Now we can use the TTS in MTR mod to describe the station. I see the code, it uses `com.mojang.text2speech`. Yeah, it is easy, but it is bad for MacOS users (Need change native libs by themselves) and Windows users without SAPI (Some copy systems delete many `useless` things include this)
And the voice now is so machinal and bad. It makes people feel not good.

**Describe the solution you'd like**
Bundle the high-quality offline TTS engine into mod assets. Don't think about the copyright, they're all free and open-source.
I searched these are very useful:
TTSKit-Java: https://gitee.com/endlesshh/ttskit-java/tree/master Use Pytorch-Java to do. For Simplfied Chinese.
Java-TTS: https://github.com/ekk0/java-tts Normal, no big requires. For Cantonese.
JavaX TTS API+FreeTTS: You can look at this https://www.javatpoint.com/convert-text-to-speech-in-java . For English.
In addition, we can add a option to config if you want to use cantonese to repeat chinese part.

**Additional Information**
I know add them will make the mod so big and mess, so maybe we can made it to a core, and you can use a extension to do it.
If you feel difficult to use these engines, i can help.
PS: Also there is an engine ekho (Written in C) supports these threes and it is simple, but it is just to merge many pinyin and speak one by one. It is so bad.

**Comment by kettle-7** [comment]
I worry this will massively increase the size of the mod, maybe they can be an optional dependency?

**Comment by jonafanho** [comment]
This is probably out of scope for the mod.
