### ISSUE TITLE
Game Crash when joined the Server!

### ISSUE THREAD

**Issue by TheRedstoneWolf** [jonafanho/Minecraft-Transit-Railway#465]
**Expected Behaviour**
I have a server with the MTR mod. When I join the server, it loads briefly and minecraft crashes. The error message comes: "**could not render boolean mtr.data.IGui.isCjk(java.lang.String)**". Even after multiple attempts, the problem has not been resolved.

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Start the MTR mod with the mods below and the Minecraft / Fabric Loader version below.

2. Join the server (2gb ram / 6gb SSD)

3. Wait for the game to load --> crash

**Crash Report**
[crash-2022-08-17_19.20.27-client.txt](https://github.com/jonafanho/Minecraft-Transit-Railway/files/9364994/crash-2022-08-17_19.20.27-client.txt)

**Environment**

- Minecraft Version: Fabric 1.19 (0.14.7)
- Installed Mods:
- Adorn 3.6.1
- Appleskin 2.4.1
- Architectury 5.12.42
- Charm 4.2.1
- Chisel 1.4.6
- Cloth Config 8.0.75
- Decor4fabric 1.2.1
- Dynamic Sound Filters 1.3.0
- Fabric Api 0.58.0
- Fabric Language Kotlin 1.8.2
- Iris MC 1.2.6
- Joban Client Mod 1.1.4
- Light Overlay 7.0.0
- MCW Paintings 1.0.4
- Modmenu 4.0.4
- Mo Glass 1.6.1
- MTR 3.0.1
- MTR LU Addon 3.0.1
- Reeses Sodium Options 1.4.5
- Roughly Enough Items 9.1.528
- Sodium Extra 0.4.6
- Sodium 0.4.2
- World Edit Cui 01
- World Edit 7.2.11
- Xaeros Minimap 22.12.0
- Xaeros World Map 1.26.1

**Additional Information**
It's not the server. The day before the crash everything was running smoothly and there were no problems. Since I installed Dynamic Sound Filters and updated the Joban Client mod it doesn't work anymore.

**Comment by Kenny-Hui** [comment]
Joban Client Mod 1.1.4 is not compatible with MTR 3.0.1
You can choose to update MTR to 3.1.0-unofficial-4 in Discord's #previews channel. (It's not on CurseForge)
Or you can downgrade Joban Client Mod to 1.1.2

**Comment by TheRedstoneWolf** [comment]
> Joban Client Mod 1.1.4 is not compatible with MTR 3.0.1 You can choose to update MTR to 3.1.0-unofficial-4 in Discord's #previews channel. (It's not on CurseForge) Or you can downgrade Joban Client Mod to 1.1.2

**Comment by TheRedstoneWolf** [comment]
Thanks for your help.
