### ISSUE TITLE
Latest Bluemap version is incompatible with latest full release of MTR (v3.0.1)

### ISSUE THREAD

**Issue by sleepysapph** [jonafanho/Minecraft-Transit-Railway#472]
**Expected Behaviour**
Bluemap 3.2.0 behaves nicely with MTR, and integrates its stations onto the Bluemap.

**Actual Behaviour**
Because MTR 3.0.1 is using an older version of the Bluemap API, there is a crash due to
`java.lang.NoSuchMethodError: 'de.bluecolored.bluemap.api.marker.MarkerAPI de.bluecolored.bluemap.api.BlueMapAPI.getMarkerAPI()'..`
and Minecraft suspects MTR as the compatibility issue
`Suspected Mods: Minecraft Transit Railway (mtr)`

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Install MTR v3.0.1 on server
2. Install Bluemap v3.2.0 on server
3. Watch server crash

**Crash Report**
(https://gnomebot.dev/paste/1011441975456706660)

**Environment**

- Minecraft Version: Fabric 1.16.5 on loader 0.11.3 running Java 17
- Installed Mods: 
![image](https://user-images.githubusercontent.com/111823977/186046316-60299ab2-8f2b-450a-80e4-7887839e75f4.png)
![image](https://user-images.githubusercontent.com/111823977/186046344-b0ef5e8f-87f9-43e4-bc81-a79bd66e2558.png)
![image](https://user-images.githubusercontent.com/111823977/186046366-205c757e-f1f5-440b-bf35-e22b1ba158b3.png)
![image](https://user-images.githubusercontent.com/111823977/186046388-7fcb1fdb-6585-416e-b945-c4a40aad4c7a.png)
![image](https://user-images.githubusercontent.com/111823977/186046405-8918a504-3708-4f1c-95a1-83c6dbbc530e.png)
![image](https://user-images.githubusercontent.com/111823977/186046433-28fdd778-95cf-488b-ad71-a5343b8c7580.png)

I have also tested this with only MTR, Joban Client, and LU and Bluemap on an empty server and I get the same results.

**Additional Information**
According to the owner of Bluemap, 
_"well Minecraft Transit Railway depend on the old API version .. and the new bluemap version uses a newer one ^^'"_

https://github.com/BlueMap-Minecraft/BlueMapAPI Bluemap has their API public on their Github. I've already mentioned this on the MTR discord however I feel it would be more conducive to have it as an actual issue report on this Github :D

**Comment by jonafanho** [comment]
Thank you! I will remember to do this. Thanks for reminding me.

**Comment by sleepysapph** [comment]
Awesome :D Thanks so much for making sure that this gets into the next update

**Comment by sleepysapph** [comment]
Awesome :D Thanks so much for making sure that this gets into the next update

**Comment by sleepysapph** [comment]
Since I posted this issue, Bluemaps has officially released their version 3.3. Just wanted to make sure the upcoming MTR v3.1.0 was compatible with Bluemaps v3.3.0 
[](https://github.com/BlueMap-Minecraft/BlueMap/releases/tag/v3.3)

**Comment by jonafanho** [comment]
Fixed in c23c357921162b214930439765b3c5ef9b0f02f
