### ISSUE TITLE
Cable Car not slowing down on CC Station node (+platform rail)

### ISSUE THREAD

**Issue by TobaT3** [jonafanho/Minecraft-Transit-Railway#474]
**Expected Behaviour**
The cable car slowing down as it enters a station node (+ a platform rail)

**Actual Behaviour**
The cable car doesnt slow down. I have a turn a few blocks later and it slows down there but not on the platforms

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Build a cable car loop
2.

**Crash Report**
Did not crash

**Screenshots**
Sorry for the terrible text
![image](https://user-images.githubusercontent.com/67913859/186436278-8d9ae394-203f-44ac-935a-6cafe2d8ca69.png)

**Environment**

- Minecraft Version: Fabric 1.19
- Installed Mods: MTR 3.0.1, MTR LU Addon 3.0.1-1.1, joban client mod 1.19-1.1.3 and other mods but purely cosmetic/performance (sodium, iris, continuity, xaeros mini+world map...)

**Additional Information**
Anything else you want to add?
fix it please thanks

**Comment by jonafanho** [comment]
You will need to make a longer section of station track for the cable car to slow down first before it enters the platform.
