### ISSUE TITLE
Why can't I download the files

### ISSUE THREAD

**Issue by Jay20081229** [jonafanho/Minecraft-Transit-Railway#476]
Why can't I download the example resource pack?

![image](https://user-images.githubusercontent.com/59323889/186703838-19ae2ccf-0a4a-4783-89b1-55fd9cd88b7d.png)

Please get new link to download the example resource pack.

**Comment by jonafanho** [comment]
It's working for me. Does anyone else have this issue? Please check your internet connection and try again.

**Comment by Jay20081229** [comment]
> It's working for me. Does anyone else have this issue? Please check your internet connection and try again.

My internet connection doesn't have any issue. Please send new link to download the files or change the downloading link.

**Comment by Big-Cake-jpg** [comment]
看起来你是中国大陆地区的用户。`raw.githubusercontent.com` 是 GitHub 的域名，因此在大陆地区的连通性会比较差。请尝试使用代理
