### ISSUE TITLE
More type of PIDS

### ISSUE THREAD

**Issue by Forest103** [jonafanho/Minecraft-Transit-Railway#48]
This request doesn't related to any problem.

**Main point:**
- Hope to add new PIDS that installation in 2017
- Hope to add more text form/colour for the old PIDS

**Point one - new PIDS**
In now, the mod have these two version of PIDS:
![2021-05-08_12 54 24](https://user-images.githubusercontent.com/83854276/117531256-48137000-b014-11eb-98fd-35585d75982a.png)
![2021-05-08_12 43 26](https://user-images.githubusercontent.com/83854276/117531260-49dd3380-b014-11eb-8051-75c20192b832.png)

However these two PIDS are already uninstallation in 2017 for the new LCD PIDS.
The follow picture is the new LCD PIDS in real life:
![image](https://user-images.githubusercontent.com/83854276/117531458-2666b880-b015-11eb-9525-f5b57ad40ffb.png)

And recreate in virtual
![PIDS](https://user-images.githubusercontent.com/83854276/117533114-7fd2e580-b01d-11eb-93e2-62ca23a776d0.png)

The new LCD PIDS can show the follow information:
- 1.Destination of next train (below part)
- 2.Time take for next train (below part)
- 3.Weather outside the station (upper part)
- 4.Temperature outside the station (upper part)
- 5.Time (upper part)
- 6.Next four train's destination & time take & car this train have (only enable when there a different car number train run in same route) & platform the train stop (middle & below part)
- 7.Latest news of train services (like delay, accident...) (middle part)
- 8.Some Trailer for new route and safety (middle part)

**Point two - more text form/colour**
Before 2017, East Rail Line have the old PIDS that installation by KCR, the follow is the old East Rail Line PIDS in real life:
![image](https://user-images.githubusercontent.com/83854276/117533981-16a1a100-b022-11eb-8194-8f902c129c5f.png)

And recreate in virtual (picture by other person)
![image](https://user-images.githubusercontent.com/83854276/117533505-d17c6f80-b01f-11eb-84d3-160601a2bbb4.png)

The East Rail Line old PIDS have the follow feature:
- 1.Text in red
- 2.Can show two next train
- 3.With a number at left
- 4."Minute" in short form is "min" and in chinese version is "分" not "分鐘"
- 5.Text is little bit bigger than urban line PIDS
- 6.Screen is make by LED light

Hope you can add these two PIDS into the mod, these PIDS can make the mod more real to the real life.

**Comment by JLC87** [comment]
they will be added its just time problem and many people including me and the creator likes the old pids more than new ones
but at least u gave examples and virtual pics

**Comment by jonafanho** [comment]
Added in JCM
