### ISSUE TITLE
Bug in unofficial-5-hotfix-1 (may not be reproducible) 在unofficial-5-hotfix-1版本中出现的漏洞（可能无法复现）

### ISSUE THREAD

**Issue by DeadBoy2537** [jonafanho/Minecraft-Transit-Railway#480]
Minecraft Version: Fabric-1.16.5
游戏版本: Fabric-1.16.5
I set a real time schedule for the depot and synchronized real time for the game.
This seems to work fine, but my depot time is not synced with real time, resulting in vehicles not departing at the time I set.
我为车厂设定了实时时间表，并为游戏同步现实时间。
这看起来一切正常，但是我的车厂时间却没有同步现实时间，导致车辆不会在我设定的时间发车。
![IMG_20220828_151646](https://user-images.githubusercontent.com/87133530/187062537-22ad38d9-ad63-4835-8ed8-c72ceb24ea84.jpg)
![Screenshot_WeaversLauncher_PojavLauncher__20220828-105912](https://user-images.githubusercontent.com/87133530/187062542-3ba79252-c1f3-48df-8daf-9596b8329217.png)
![Screenshot_WeaversLauncher_PojavLauncher__20220828-105840](https://user-images.githubusercontent.com/87133530/187062547-e4e77583-88cf-4d68-8a35-7d315f59a2ef.png)
This bug did not appear on August 27th, but it appeared on August 28th.
这个BUG在8月27号的时候没有出现，但在8月28号出现了。

**Comment by kettle-7** [comment]
Check to be sure that the server and client both have the time synced, sometimes the clocks get knocked off and will cause delay. Also real time is based on the actual time in your timezone, not the time in mincefart which is what the clock shows.

**Comment by DeadBoy2537** [comment]
i make sure that the server and client both have the time synced

**Comment by DeadBoy2537** [comment]
> Check to be sure that the server and client both have the time synced, sometimes the clocks get knocked off and will cause delay. Also real time is based on the actual time in your timezone, not the time in mincefart which is what the clock shows.

i make sure that the server and client both have the time synced

**Comment by DeadBoy2537** [comment]
> 检查以确保服务器和客户端都已同步时间，有时时钟会被敲掉并导致延迟。实时时间也是基于您所在时区的实际时间，而不是时钟显示的 mincefart 时间。

Ok I now know why.
The time sync uses not GMT+08:00 but GMT+00:00.
But how to fix it? My server system (CentOS 8) does use GMT+08:00, and typing "/taw system-time" in the game shows the correct time.

**Comment by kettle-7** [comment]
See if it works well without Time & Wind, you can still use the real time scheduling. Also iirc CentOS is no longer under active maintenance.

The real time scheduling should be based off local time so it should work but evidently it can't always.

**Comment by DeadBoy2537** [comment]
> See if it works well without Time & Wind, you can still use the real time scheduling. Also iirc CentOS is no longer under active maintenance.
> 
> The real time scheduling should be based off local time so it should work but evidently it can't always.

Still can't sync real time.
Maybe add a setting to the mod to select a time zone?

**Comment by kettle-7** [comment]
The point is that it uses the time zone of the client, does it all work without time and wind?

**Comment by kettle-7** [comment]
My mistake you already answered

**Comment by DeadBoy2537** [comment]
> See if it works well without Time & Wind, you can still use the real time scheduling. Also iirc CentOS is no longer under active maintenance.
> 
> The real time scheduling should be based off local time so it should work but evidently it can't always.

这几天又重新研究了这个问题，通过日志文件所打印的时间，发现其实是客户端所用的时区是UTC+0（可能是因为我所使用的启动器是Pojavlauncher）。然后我在网上搜查了一番，发现其实可以给客户端/服务端的启动参数加入"-Duser.timezone=Asia/Shanghai"来解决。
In the past few days, I revisited the problem and found that the time zone used by the client was UTC+0 (probably because the launcher I was using was Pojavlauncher) by the time printed in the log file. Then I searched the internet and found that I could add "-Duser.timezone=Asia/Shanghai" to the client/server startup parameters to solve the problem.
