### ISSUE TITLE
PIDS (variant 2) only showing one side (but not always)

### ISSUE THREAD

**Issue by TobaT3** [jonafanho/Minecraft-Transit-Railway#488]
**Expected Behaviour**
The screens working

**Actual Behaviour**

**Reproduction Steps**
Steps to reproduce the behaviour:

1.No idea, sometimes the screens show both sides, sometimes not. For example if i place a PIDS on the ground, it shows both sides but when i place it even one block above the ground it only shows one side, but if i move it further along the platform (still right next to it), it shows both sides... Doesnt make sense to me

**Screenshots**
![image](https://user-images.githubusercontent.com/67913859/188263917-e2b6c7c0-5dcf-4e4f-8ccf-74df6a22afdf.png)
![image](https://user-images.githubusercontent.com/67913859/188263924-4a2f194f-7dcc-4263-93a5-838fda720ea7.png)
(Shows the same PIDSs from two different sides)

**Environment**

- Minecraft Version: 1.19
- Installed Mods: Continuity, Indium, Iris, Joban Client Mod (Though i used the normal MTR pids_2), Sodium, LambdaBetterGrass, LambDynamicLights, Litematica, Lithium, MTR LU Addon, Sodium, MTR Version 3.0.1

**Additional Information**
Anything else you want to add? No

**Comment by jonafanho** [comment]
It's a bit too far from your platform. Try putting it closer.
