### ISSUE TITLE
Player falls through floor when riding cable car

### ISSUE THREAD

**Issue by tommyskeff** [jonafanho/Minecraft-Transit-Railway#490]
**Expected Behaviour**
Player enters cable car and stays with it as it moves.

**Actual Behaviour**
Player enters cable car and falls through the floor, unable to ride the car.

**Reproduction Steps**
1. Enter cable car in multiplayer and soemtimes fall through the floor.

**Screenshots**

**Environment**
Server

- Minecraft Version: 1.16.5 Forge Server
- Installed Mods: 
- • minecraft forge-1.16.5-36.2.34-server.jar : minecraft (1.16.5) - 1
• mods_folder elevatorid-1.16.5-1.7.13.jar : elevatorid (1.16.5-1.7.13) - 1
• mods_folder Dynmap-3.4-beta-3-forge-1.16.5.jar : dynmap (3.4-beta-3-774) - 1
• mods_folder Orva+Alarms+2.2+1.16.5.jar : orva_alarms (2.0) - 1
• mods_folder obfuscate-0.6.2-1.16.3.jar : obfuscate (0.6.2) - 1
• mods_folder worldedit-mod-7.2.5-dist.jar : worldedit (7.2.5+57d5ac9) - 1
• mods_folder Traffic+Control+Ps+Roads+3.0.0+_1.16.5.jar : traffic_control_roadsmodbyteerth (3.0.0) - 1
• mods_folder cfm-7.0.0pre22-1.16.3.jar : cfm (7.0.0-pre22) - 1
• mods_folder architectury-1.31.60 (5).jar : architectury (1.31.60) - 1
• mods_folder MTR-forge-1.16.5-3.0.1.jar : mtr (1.16.5-3.0.1) - 1
• mods_folder mapperbase-1.16.5-2.4.0.0.jar : mapperbase (1.16.5-2.4.0.0) - 1
• mods_folder vehicle-mod-0.45.2-1.16.3.jar : vehicle (0.45.2) - 1
• maven_libs forge-1.16.5-36.2.34-universal.jar : forge (36.2.34) - 1
• mods_folder flywheel-1.16-0.2.5.jar : flywheel (1.16-0.2.5) - 1
• mods_folder create-mc1.16.5_v0.3.2g.jar : create (v0.3.2g) - 1
• mods_folder roadstuff-1.16.5-4.3.0.jar : roadstuff (1.16.5-4.3.0) - 1
• mods_folder [1.16.5]+SecurityCraft+v1.9.0.2.jar : securitycraft (v1.9.0.2) - 1

**Additional Information**
Restarting server usually fixes the issue.

![image](https://user-images.githubusercontent.com/96320424/188286036-6dcbc410-31ac-40db-9a7d-6c7c7017bdbc.png)

**Comment by jonafanho** [comment]
Is this due to server lag?

**Comment by tommyskeff** [comment]
I don't think so, TPS is running at 20 consistently with only a few players online at any time. It happens randomly and restarting the server fixes the issue. Sometimes it happens for one player and not another, and restarting game doesn't help.

Also, while I'm here, I think it would be a really good idea to add a config option to disable chunk loading while on a train above a certain speed threshold (sometimes when going at high speeds chunks don't load fast enough to keep up and lag the server). I also think it would be a great idea to add station announcements to let passengers at a station know when trains are arriving.

Another bug I have encountered a lot is where the path gets stuck on "Generating Path" and I have to relog to remove it.

Thanks!

**Comment by jonafanho** [comment]
The chunks are loaded by the player, not by additional chunk loading code. Player chunk loading is always enabled by Minecraft. It sounds like connection lag then, if your TPS is 20. You can add announcements through resourcepacks and play them using schedule sensors and command blocks. As of the generating path bug, I will look into that, thanks.

**Comment by jonafanho** [comment]
Did you resolve this issue?

**Comment by tommyskeff** [comment]
I didn't change anything but haven't encountered it since so I'm assuming so yes. Thanks!
