### ISSUE TITLE
Elevator Floor Track Not Editable

### ISSUE THREAD

**Issue by ATrashbin** [jonafanho/Minecraft-Transit-Railway#492]
**Expected Behaviour**
I Was Expecting It To Bring Up The Edit Screen When I Right Click It.

**Actual Behaviour**
The Elevator Floor Track Does Not Bring Up The Edit Screen When I Right Click It

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Place Down A Floor Track
2. Right Click

**Environment**

- Minecraft Version: Fabric 1.17.1
- Installed Mods: architectury-2.10.12.jar
- fabric-api-0.46.1+1.17.jar
- Modern-Elevators-Escalators-fabric-1.17.1-3.0.1-prerelease-1.jar

**Comment by jonafanho** [comment]
Are you using the brush to right click it?
