### ISSUE TITLE
Can't ride the cable car

### ISSUE THREAD

**Issue by Craft374** [jonafanho/Minecraft-Transit-Railway#494]
**Expected Behaviour**
Everyone can ride a cable car

**Actual Behaviour**
Other than me, no one else can ride a cable car

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Build and ride a cable car on the server

**Screenshots**
https://www.youtube.com/watch?v=KNOGXE8JN9w&ab_channel=J.Craft374
https://www.youtube.com/watch?v=Y8zTZvJtP1c&ab_channel=J.Craft374

**Environment**
server
- Minecraft Version: 1.18.2
- Installed Mods:
paucal-forge-1.18.2-0.4.7.jar                     |PAUCAL                        |paucal                        |0.4.7               
bigbrain-1.5.3.jar                                |Big Brain                     |bigbrain                      |1.5.3               
infernal-expansion-1.18.2-2.5.0.jar               |Infernal Expansion            |infernalexp                   |2.5.0               
mcw-windows-2.0.3-mc1.18.2.jar                    |Macaw's Windows               |mcwwindows                    |2.0.3               
soundphysics-forge-1.18.2-1.0.6.jar               |Sound Physics Remastered      |sound_physics_remastered      |1.18.2-1.0.6        
Neat-1.8-31.jar                                   |Neat                          |neat                          |1.8-31              
upgradednetherite_items-1.18.2-3.2.0.0-release.jar|Upgraded Netherite : Items    |upgradednetherite_items       |1.18.2-3.2.0.0-relea
guardvillagers-1.18.2.1.4.3.jar                   |Guard Villagers               |guardvillagers                |1.4.3               
clickadv-1.18.2-2.5.jar                           |clickadv mod                  |clickadv                      |1.18.2-2.5          
SimplyHouses-1.1.0-1.18.2-forge.jar               |Simply Houses                 |simply_houses                 |1.1.0-1.18.2        
balm-3.2.0+0.jar                                  |Balm                          |balm                          |3.2.0+0             
dynview-1.18.2-2.8.jar                            |Dynamic view distance         |dynview                       |2.3                 
DLC_Collection2.0.16.jar                          |DLC Collection                |dlc_collection                |2.0.16              
chat_heads-0.6.1-forge-1.18.2.jar                 |Chat Heads                    |chat_heads                    |0.6.1               
Paraglider-1.18.2-1.6.0.0.jar                     |Paraglider                    |paraglider                    |1.6.0.0             
refinedstorage-1.10.3.jar                         |Refined Storage               |refinedstorage                |1.10.3              
upgradednetherite-1.18.2-4.2.0.6-release.jar      |Upgraded Netherite            |upgradednetherite             |1.18.2-4.2.0.6-relea
structure_gel-1.18.2-2.4.6.jar                    |Structure Gel API             |structure_gel                 |2.4.6               
corpse-1.18.2-1.0.1.jar                           |Corpse                        |corpse                        |1.18.2-1.0.1        
AdvancementPlaques-1.18.2-1.4.5.1.jar             |Advancement Plaques           |advancementplaques            |1.4.5.1             
BetterPingDisplay-1.18.2-1.1.jar                  |Better Ping Display           |betterpingdisplay             |1.1                 
morevillagers-forge-1.18.2-3.3.2.jar              |More Villagers                |morevillagers                 |3.3.2               
ironfurnaces-1.18.2-3.3.1.jar                     |Iron Furnaces                 |ironfurnaces                  |3.3.1               
timeout_fixes-1.18.1-1.0.0.jar                    |Timeout Fixes                 |timeout_fixes                 |1.18.1-1.0.0        
mcw-trapdoors-1.0.7-mc1.18.2.jar                  |Macaw's Trapdoors             |mcwtrpdoors                   |1.0.7               
Botania-1.18.2-434.jar                            |Botania                       |botania                       |1.18.2-434          
SoMSecondSemester1.18.2-3.1.3.jar                 |Schools of Magic: Second Semes|schoolsofmagic                |3.1.3               
curios-forge-1.18.2-5.0.7.1.jar                   |Curios API                    |curios                        |1.18.2-5.0.7.1      
industrialcraft-2-2.9.98+ex118-1.18.2-forge.jar   |IndustrialCraft 2             |ic2                           |2.9.98+ex118        
randomite-1.18.2-1.1.2.jar                        |Randomite Classic             |randomite                     |1.1.2               
advancednetherite-1.12.4-1.18.2.jar               |Advanced Netherite            |advancednetherite             |1.12.4              
worldedit-mod-7.2.10.jar                          |WorldEdit                     |worldedit                     |7.2.10+1742f98      
constructionwand-1.18.2-2.7.jar                   |Construction Wand             |constructionwand              |1.18.2-2.7          
mcw-roofs-2.1.2-mc1.18.2.jar                      |Macaw's Roofs                 |mcwroofs                      |2.1.2               
cfm-7.0.0-pre29-1.18.2.jar                        |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre29         
mcw-furniture-3.0.1-mc1.18.2.jar                  |Macaw's Furniture             |mcwfurnitures                 |3.0.1               
JadeAddons-1.18.2-2.4.0.jar                       |Jade Addons                   |jadeaddons                    |2.4.0               
krypton-0.1.10-SNAPSHOT.jar                       |Krypton Reforged              |krypton                       |0.1.10-SNAPSHOT     
FastLeafDecay-28.jar                              |FastLeafDecay                 |fastleafdecay                 |28                  
EnchantingInfuser-v3.3.2-1.18.2-Forge.jar         |Enchanting Infuser            |enchantinginfuser             |3.3.2               
mcw-lights-1.0.4-mc1.18.2.jar                     |Macaw's Lights and Lamps      |mcwlights                     |1.0.4               
torchslabmod-1.18.1_v1.7.5.jar                    |Torch Slab Mod                |torchslabmod                  |1.7.5               
cgm-1.2.6-1.18.2.jar                              |MrCrayfish's Gun Mod          |cgm                           |1.2.6               
AoA3-1.18.2-3.6.6.jar                             |Advent of Ascension           |aoa3                          |1.18.2-3.6.6        
jei-1.18.2-9.7.1.255.jar                          |Just Enough Items             |jei                           |9.7.1.255           
ProjectE-1.18.2-PE1.0.1.jar                       |ProjectE                      |projecte                      |1.0.1               
goblintraders-1.7.2-1.18.2.jar                    |Goblin Traders                |goblintraders                 |1.7.2               
Mekanism-1.18.2-10.2.5.465.jar                    |Mekanism                      |mekanism                      |10.2.5              
caelus-forge-1.18.1-3.0.0.2.jar                   |Caelus API                    |caelus                        |1.18.1-3.0.0.2      
colytra-forge-1.18.1-5.2.0.2.jar                  |Colytra                       |colytra                       |1.18.1-5.2.0.2      
Runic1.18_V1.6.jar                                |Runic                         |runic                         |1.0.0               
RingsOfAscension-1.18.2-1.0.1.jar                 |Rings of Ascension            |ringsofascension              |1.0.0               
Fallingleaves-1.18.2-1.3.2.jar                    |Falling Leaves                |fallingleaves                 |1.3.2               
TravelersBackpack-1.18.2-7.1.8.jar                |Traveler's Backpack           |travelersbackpack             |7.1.8               
NaturesCompass-1.18.2-1.9.7-forge.jar             |Nature's Compass              |naturescompass                |1.18.2-1.9.7-forge  
badpackets-forge-0.1.2.jar                        |Bad Packets API               |badpackets                    |0.1.2               
snowundertrees-1.18.2-1.2.1.jar                   |Snow Under Trees              |snowundertrees                |1.2.1               
starlight-1.0.2+forge.546ae87.jar                 |Starlight                     |starlight                     |1.0.2+forge.83663de 
projecte-integration-1.18.2-5.3.1.jar             |ProjectE Integration          |projecteintegration           |5.3.1               
catalogue-1.6.2-1.18.2.jar                        |Catalogue                     |catalogue                     |1.6.2               
nethertears-forge-1.0.0.jar                       |下界遗泪                        |ntrs                          |1.0.0               
restored_earth-1.18.2-1.4.2.jar                   |Restored Earth                |restored_earth                |1.4.2               
forge-1.18.2-40.1.68-universal.jar                |Forge                         |forge                         |40.1.68             
mcw-paths-1.0.1-mc1.18.2.jar                      |Macaw's Paths and Pavings     |mcwpaths                      |1.0.1               
alchemistry-1.18.2-2.0.8a.jar                     |Alchemistry                   |alchemistry                   |1.18.2-2.0.8a       
server-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              
cofh_core-1.18.2-1.6.4.21.jar                     |CoFH Core                     |cofh_core                     |1.6.4.21            
thermal_foundation-1.18.2-1.6.3.28.jar            |Thermal Series                |thermal                       |1.6.3.28            
thermal_integration-1.18.2-1.6.3.7.jar            |Thermal Integration           |thermal_integration           |1.6.3.7             
thermal_innovation-1.18.2-1.6.3.12.jar            |Thermal Innovation            |thermal_innovation            |1.6.3.12            
thermal_locomotion-1.18.2-1.6.3.8.jar             |Thermal Locomotion            |thermal_locomotion            |1.6.3.8             
lucky-block-forge-1.18.2-13.1.jar                 |Lucky Block                   |lucky                         |1.18.2-13.1         
trade-cycling-forge-1.18.2-1.0.2.jar              |Trade Cycling                 |trade_cycling                 |1.18.2-1.0.2        
TerraBlender-forge-1.18.2-1.1.0.102.jar           |TerraBlender                  |terrablender                  |1.18.2-1.1.0.102    
ImmersiveEngineering-1.18.2-8.2.0-151.jar         |Immersive Engineering         |immersiveengineering          |1.18.2-8.2.0-151    
pamhc2crops-1.18.2-1.0.1.jar                      |Pam's HarvestCraft 2 - Crops  |pamhc2crops                   |1.0.1               
domum_ornamentum-1.18.2-1.0.50-ALPHA-universal.jar|Domum Ornamentum              |domum_ornamentum              |1.18.2-1.0.50-ALPHA 
flywheel-forge-1.18-0.6.3.jar                     |Flywheel                      |flywheel                      |1.18-0.6.3.81       
Mantle-1.18.2-1.9.27.jar                          |Mantle                        |mantle                        |1.9.27              
ecologics-forge-1.18.2-1.7.9.jar                  |Ecologics                     |ecologics                     |1.7.9               
pamhc2foodcore-1.18.2-1.0.1.jar                   |Pam's HarvestCraft 2 - Food Co|pamhc2foodcore                |1.0.1               
thermal_cultivation-1.18.2-1.6.3.11.jar           |Thermal Cultivation           |thermal_cultivation           |1.6.3.11            
AutoRegLib-1.7-53.jar                             |AutoRegLib                    |autoreglib                    |1.7-53              
[1.18.2] SecurityCraft v1.9.3.1.jar               |SecurityCraft                 |securitycraft                 |1.9.3.1             
structurize-1.18.2-1.0.424-ALPHA.jar              |Structurize                   |structurize                   |1.18.2-1.0.424-ALPHA
AmbientEnvironment-forge-1.18.2-7.0+19.jar        |Ambient Environment           |ambientenvironment            |7.0+19              
appleskin-forge-mc1.18.2-2.4.1.jar                |AppleSkin                     |appleskin                     |2.4.1+mc1.18.2      
lootr-1.18.2-0.2.19.56.jar                        |Lootr                         |lootr                         |0.2.19.56           
upgradednetherite_ultimate-1.18.2-3.2.0.1-release.|Upgraded Netherite : Ultimerit|upgradednetherite_ultimate    |1.18.2-3.2.0.1-relea
PuzzlesLib-v3.3.5-1.18.2-Forge.jar                |Puzzles Lib                   |puzzleslib                    |3.3.5               
Aquaculture-1.18.2-2.3.8.jar                      |Aquaculture 2                 |aquaculture                   |1.18.2-2.3.8        
CosmeticArmorReworked-1.18.2-v2.jar               |CosmeticArmorReworked         |cosmeticarmorreworked         |1.18.2-v2           
blue_skies-1.18.2-1.3.12.jar                      |Blue Skies                    |blue_skies                    |1.3.12              
Piglin+Expansion+1.2.1.jar                        |Piglin Expansion              |piglin_expansion              |1.1.0               
mc2discord-forge-1.18.x-3.2.10.jar                |Mc2Discord                    |mc2discord                    |3.2.10              
Galosphere-1.18.2-1.0.4.jar                       |Galosphere                    |galosphere                    |1.18.2-1.0.4        
sophisticatedcore-1.18.2-0.5.1.98.jar             |Sophisticated Core            |sophisticatedcore             |1.18.2-0.5.1.98     
sleeping_bags-1.18.2-1.0.1.jar                    |Sleeping Bags                 |sleeping_bags                 |1.18.2-1.0.1        
citadel-1.11.3-1.18.2.jar                         |Citadel                       |citadel                       |1.11.3              
alexsmobs-1.18.6.jar                              |Alex's Mobs                   |alexsmobs                     |1.18.6              
domesticationinnovation-1.4.2-1.18.2.jar          |Domestication Innovation      |domesticationinnovation       |1.4.2               
potionsmaster-0.5.8-1.18.2-40.1.0.jar             |Potions Master                |potionsmaster                 |0.5.8-1.18.2-40.1.0 
sophisticatedbackpacks-1.18.2-3.18.17.680.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.18.2-3.18.17.680  
u_team_core-1.18.2-4.0.1.216.jar                  |U Team Core                   |uteamcore                     |4.0.1.216           
simpleplanes-1.18.2-4.15.0.jar                    |Simple Planes                 |simpleplanes                  |1.18.2-4.15.0       
mcw-doors-1.0.7-mc1.18.2.jar                      |Macaw's Doors                 |mcwdoors                      |1.0.7               
MekanismGenerators-1.18.2-10.2.5.465.jar          |Mekanism: Generators          |mekanismgenerators            |10.2.5              
maessentials-1.18-3.7.1.jar                       |MaEssentials                  |maessentials                  |1.18-3.7.1          
hedgehog-1.18.2-1.1.0.jar                         |Hedgehog                      |hedgehog                      |1.18.2-1.1.0        
MmmMmmMmmMmm-1.18.2-1.5.2.jar                     |MmmMmmMmmMmm                  |dummmmmmy                     |1.18-1.5.2          
twilightforest-1.18.2-4.1.1220-universal.jar      |The Twilight Forest           |twilightforest                |4.1.1220            
Buddycards-1.18.2-3.2.1.jar                       |Buddycards Core               |buddycards                    |1.18.2-3.2.1        
mcw-bridges-2.0.3-mc1.18.2.jar                    |Macaw's Bridges               |mcwbridges                    |2.0.3               
FarmersDelight-1.18.2-1.1.2.jar                   |Farmer's Delight              |farmersdelight                |1.18.2-1.1.2        
useful_backpacks-1.18.2-1.12.2.94.jar             |Useful Backpacks              |usefulbackpacks               |1.12.2.94           
AmbientSounds_FORGE_v5.0.16_mc1.18.2.jar          |Ambient Sounds                |ambientsounds                 |5.0.16              
getittogetherdrops-1.18.2-1.2.jar                 |Get It Together, Drops!       |getittogetherdrops            |1.2                 
MekanismAdditions-1.18.2-10.2.5.465.jar           |Mekanism: Additions           |mekanismadditions             |10.2.5              
endrem_forge-5.1.0-R-1.18.2.jar                   |End Remastered                |endrem                        |5.1.0-R-1.18.2      
mcw-fences-1.0.6-mc1.18.2.jar                     |Macaw's Fences and Walls      |mcwfences                     |1.0.6               
simplylight-1.18.2-1.4.2-build.31.jar             |Simply Light                  |simplylight                   |1.18.2-1.4.2-build.3
upgradedtools-1.18.2-1.1.0.1-release.jar          |Upgraded Tools                |upgradedtools                 |1.18.2-1.1.0.1-relea
pamhc2foodextended-1.18.2-1.0.0.jar               |Pam's HarvestCraft 2 - Food Ex|pamhc2foodextended            |1.0                 
CNB-1.18.2-1.4.0.jar                              |Creatures and Beasts          |cnb                           |1.4.0               
geckolib-forge-1.18-3.0.35.jar                    |GeckoLib                      |geckolib3                     |3.0.35              
crittersandcompanions-1.18.2-1.0.1.jar            |Critters and Companions       |crittersandcompanions         |1.18.2-1.0.1        
naturalist-forge-1.1.1-1.18.2.jar                 |Naturalist                    |naturalist                    |1.1.1               
Goblins_Dungeons_1.0.8.jar                        |Goblins & Dungeons            |goblinsanddungeons            |1.0.8               
hole_filler_mod_1.2.5-mc_1.18.1-forge.jar         |Hole Filler Mod               |hole_filler_mod               |1.2.5               
Cataclysm-0.19.jar                                |Cataclysm Mod                 |cataclysm                     |1.0                 
Patchouli-1.18.2-71.1.jar                         |Patchouli                     |patchouli                     |1.18.2-71.1         
ars_nouveau-1.18.2-2.7.6.jar                      |Ars Nouveau                   |ars_nouveau                   |2.7.6               
blockui-1.18.2-0.0.58-ALPHA.jar                   |UI Library Mod                |blockui                       |1.18.2-0.0.58-ALPHA 
multi-piston-1.18.2-1.2.15-ALPHA.jar              |Multi-Piston                  |multipiston                   |1.18.2-1.2.15-ALPHA 
arsomega-2.6.1.jar                                |Ars Omega                     |arsomega                      |1.18.2-2.2.1        
camera-1.18.2-1.0.2.jar                           |Camera Mod                    |camera                        |1.18.2-1.0.2        
thermal_expansion-1.18.2-1.6.3.13.jar             |Thermal Expansion             |thermal_expansion             |1.6.3.13            
Gobber2-Forge-1.18.2-2.6.32.jar                   |Gobber 2                      |gobber2                       |2.6.32              
MekanismTools-1.18.2-10.2.5.465.jar               |Mekanism: Tools               |mekanismtools                 |10.2.5              
architectury-4.9.83-forge.jar                     |Architectury                  |architectury                  |4.9.83              
ftb-library-forge-1802.3.6-build.140.jar          |FTB Library                   |ftblibrary                    |1802.3.6-build.140  
ftb-teams-forge-1802.2.6-build.51.jar             |FTB Teams                     |ftbteams                      |1802.2.6-build.51   
AI-Improvements-1.18.2-0.5.0.jar                  |AI-Improvements               |aiimprovements                |0.5.0               
productivebees-1.18.2-0.9.0.11.jar                |Productive Bees               |productivebees                |1.18.2-0.9.0.11     
framework-0.2.4-1.18.2.jar                        |Framework                     |framework                     |0.2.4               
enchantwithmob-1.18.2-4.2.0.jar                   |Enchant With Mob              |enchantwithmob                |1.18.2-4.2.0        
sulfurpotassiummod-1.18.2-2.3.3+Forge.jar         |Sulfur & Potassium Mod        |sulfurpotassiummod            |2.3.3               
Towns-and-Towers-1.18.2-1.6.0.jar                 |Towns and Towers - Structure A|t_and_t                       |1.6                 
inventorysorter-1.18-19.0.0.jar                   |Simple Inventory Sorter       |inventorysorter               |19.0.0              
FixMySpawnR-forge-1.18.2-1.0.0.jar                |Fix My SpawnR                 |fixmyspawnr                   |1.0.0               
Cucumber-1.18.2-5.1.2.jar                         |Cucumber Library              |cucumber                      |5.1.2               
trashslot-forge-1.18.1-11.0.2.jar                 |TrashSlot                     |trashslot                     |11.0.2              
pamhc2trees-1.18.2-1.0.1.jar                      |Pam's HarvestCraft 2 - Trees  |pamhc2trees                   |1.0.1               
biomemakeover-FORGE-1.18.2-1.4.31.jar             |Biome Makeover                |biomemakeover                 |1.18.2-1.4.31       
sophisticatedstorage-1.18.2-0.5.1.107.jar         |Sophisticated Storage         |sophisticatedstorage          |1.18.2-0.5.1.107    
reap-1.18.2-1.0.0.jar                             |Reap Mod                      |reap                          |1.18.2-1.0.0        
create-1.18.2-0.5.0.d.jar                         |Create                        |create                        |0.5.0.d             
waystones-forge-1.18.2-10.1.0.jar                 |Waystones                     |waystones                     |10.1.0              
Structory-1.18.2-1.0.2.jar                        |Structory                     |structory                     |0.0NONE             
mcw-paintings-1.0.4-mc1.18.2.jar                  |Macaw's Paintings             |mcwpaintings                  |1.0.4               
Clumps-forge-1.18.2-8.0.0+15.jar                  |Clumps                        |clumps                        |8.0.0+15            
comforts-forge-1.18.2-5.0.0.4.jar                 |Comforts                      |comforts                      |1.18.2-5.0.0.4      
tumbleweed-1.18-0.4.12.jar                        |Tumbleweed                    |tumbleweed                    |1.18-0.4.12         
artifacts-1.18.2-4.0.7.jar                        |Artifacts                     |artifacts                     |1.18.2-4.0.7        
alternate-current-mc1.18-1.2.1.jar                |Alternate Current             |alternate_current             |0.0NONE             
gemsandcrystals-1.4.0-1.18.2.jar                  |Gems and Crystals             |gemsandcrystals               |1.4.0-1.18.2        
DimStorage-1.18.2-6.1.0.jar                       |DimStorage                    |dimstorage                    |6.1.0               
alcocraft-1.0.0.jar                               |Alcocraft                     |alcocraft                     |1.0.0               
BasicNetherOres-1.18.2-7.2.0.jar                  |Basic Nether Ores             |bno                           |7.2.0               
DungeonCrawl-1.18.2-2.3.10.jar                    |Dungeon Crawl                 |dungeoncrawl                  |2.3.10              
Modern-Elevators-Escalators-forge-1.18.2-3.0.1-pre|Modern Elevators and Escalator|mtr                           |1.18.2-3.0.1-prerele
Ore+Creeper-1.18.2-1.1.9.jar                      |Ore Creeper                   |ore_creeper                   |1.18.2-1.1.9        
mahoutsukai-1.18.2-v1.34.33.jar                   |Mahou Tsukai                  |mahoutsukai                   |1.18.2-v1.34.33     
blueprint-1.18.2-5.4.3.jar                        |Blueprint                     |blueprint                     |5.4.3               
boatload-1.18.2-3.0.0.jar                         |Boatload                      |boatload                      |3.0.0               
savage_and_ravage-1.18.2-4.0.0.jar                |Savage & Ravage               |savage_and_ravage             |4.0.0               
neapolitan-1.18.2-3.0.0.jar                       |Neapolitan                    |neapolitan                    |3.0.0               
personality-1.18.2-2.0.0.jar                      |Personality                   |personality                   |2.0.0               
allurement-1.18.2-2.0.0.jar                       |Allurement                    |allurement                    |2.0.0               
incubation-1.18.2-2.0.2.jar                       |Incubation                    |incubation                    |2.0.2               
buzzier_bees-1.18.2-4.0.0.jar                     |Buzzier Bees                  |buzzier_bees                  |4.0.0               
berry_good-1.18.2-5.0.0.jar                       |Berry Good                    |berry_good                    |5.0.0               
miningmaster-1.18.2-3.0.6.jar                     |Mining Master                 |miningmaster                  |3.0.6               
hexcasting-forge-1.18.2-0.9.1.jar                 |Hex Casting                   |hexcasting                    |0.9.1               
ftb-chunks-forge-1802.3.6-build.147.jar           |FTB Chunks                    |ftbchunks                     |1802.3.6-build.147  
BloodMagic-1.18.2-3.2.5-40.jar                    |Blood Magic                   |bloodmagic                    |1.18.2-3.2.5-40     
scuba_gear-1.18.2-1.0.4.jar                       |Scuba Gear                    |scuba_gear                    |1.0.4               
selene-1.18.2-1.17.9.jar                          |Selene                        |selene                        |1.18.2-1.17.9       
supplementaries-1.18.2-1.4.12.jar                 |Supplementaries               |supplementaries               |1.18.2-1.4.12       
MysticalAgriculture-1.18.2-5.1.1.jar              |Mystical Agriculture          |mysticalagriculture           |5.1.1               
TConstruct-1.18.2-3.5.1.31.jar                    |Tinkers' Construct            |tconstruct                    |3.5.1.31            
EnchantmentDescriptions-Forge-1.18.2-10.0.4.jar   |EnchantmentDescriptions       |enchdesc                      |10.0.4             
Jade-1.18.2-forge-5.2.3.jar                       |Jade                          |jade                          |5.2.3               
appliedenergistics2-11.1.6.jar                    |Applied Energistics 2         |ae2                           |11.1.6              
majobroom-1.4.1--1.18.2-forge.jar                 |Majo Broom Mod                |majobroom                     |1.0                 
CreativeCore_FORGE_v2.6.14_mc1.18.2.jar           |CreativeCore                  |creativecore                  |0.0NONE             
car-1.18.2-1.0.1.jar                              |Ultimate Car Mod              |car                           |1.18.2-1.0.1        
Iceberg-1.18.2-1.0.44.jar                         |Iceberg                       |iceberg                       |1.0.44              
Quark-3.2-358.jar                                 |Quark                         |quark                         |3.2-358             
cookiecore-1.18.2-4.0.1-6677a05.jar               |CookieCore                    |cookiecore                    |4.0.1               
magicfeather-1.18.2-4.2.0.jar                     |Magic Feather                 |magicfeather                  |1.18.2-4.2.0        
chemlib-1.18.2-2.0.8.jar                          |ChemLib                       |chemlib                       |1.18.2-2.0.8        
abnormals_delight-1.18.2-3.0.1.jar                |Abnormals Delight             |abnormals_delight             |3.0.1               
StorageDrawers-1.18.2-10.2.1.jar                  |Storage Drawers               |storagedrawers                |10.2.1              
ars_elemental-1.18.2-0.4.9.7.7.jar                |Ars Elemental                 |ars_elemental                 |1.18.2-0.4.9.7.7    
DiagonalFences-v3.1.0-1.18.2.jar                  |Diagonal Fences               |diagonalfences                |3.1.0            
Applied-Botanics-1.0.1.jar                        |Applied Botanics              |appbot                        |1.0.1               
upgradedcore-1.18.2-3.2.0.0-release.jar           |Upgraded Core                 |upgradedcore                  |1.18.2-3.2.0.0-relea
minecolonies-1.18.2-1.0.940-RELEASE.jar           |MineColonies                  |minecolonies                  |1.18.2-1.0.940-RELEA
arsarsenal-1.1.1-1.18.2.jar                       |Ars Arsenal                   |arsarsenal                    |1.1.1-1.18.2        
HunterIllager-1.18.2-4.0.1.jar                    |Hunter Illager                |hunterillager                 |1.18.2-4.0.1        
creeperoverhaul-1.18.2-1.3.0-forge.jar            |Creeper Overhaul              |creeperoverhaul               |1.3.0               
ferritecore-4.2.1-forge.jar                       |Ferrite Core                  |ferritecore                   |0.0NONE           
upgradednetherite_creative-1.18.2-3.2.0.0-release.|Upgraded Netherite : Creative |upgradednetherite_creative    |1.18.2-3.2.0.0-relea
harrypotter-2.0.0.jar                             |YDM's Harry Potter            |harrypotter                   |1.18.2-2.0          
expandability-6.0.0.jar                           |ExpandAbility                 |expandability                 |6.0.0               
valhelsia_core-forge-1.18.2-0.4.0.jar             |Valhelsia Core                |valhelsia_core                |1.18.2-0.4.0        
valhelsia_structures-forge-1.18.2-0.1.0.jar       |Valhelsia Structures          |valhelsia_structures          |1.18.2-0.1.0        
forbidden_arcanus-1.18.2-2.1.0-beta3.jar          |Forbidden & Arcanus           |forbidden_arcanus             |1.18.2-2.1.0-beta3  
createaddition-1.18.2-20220817a.jar               |Create Crafts & Additions     |createaddition                |1.18.2-20220817a    

**Additional Information**
Sometimes you can take the cable car
(I don't speak English so I used a translator)

**Comment by jonafanho** [comment]
You just got on the cable car in the second video.

**Comment by Craft374** [comment]
> You just got on the cable car in the second video. 

It looks like it can ride, but it's not actually rideable.
It only looks like that
