### ISSUE TITLE
Please add another type of NYC MTA train to MTR

### ISSUE THREAD

**Issue by saleem0915** [jonafanho/Minecraft-Transit-Railway#498]
Hello. I was just inquiring about if you guys could add the Kawasaki R188 and Bombardier R179 trains. Thank you, and this doesn't have to be high priority.

**Comment by Ultimate-USA-YT** [comment]
The R179 is in the Mod

**Comment by saleem0915** [comment]
What about the R188 Kawasaki?

I don't think that that's in there

**Comment by cherbert** [comment]
Stop asking for trains.

**Comment by saleem0915** [comment]
I'll close this then
