### ISSUE TITLE
I cannot see train

### ISSUE THREAD

**Issue by AdhamHakki** [jonafanho/Minecraft-Transit-Railway#499]
**Expected Behaviour**
I should see the train

**Actual Behaviour**
I hear the train, but don"t see it
**Reproduction Steps**
Steps to reproduce the behaviour:

1.

**Environment**
Windows 11 64-bit

- Minecraft Version: Forge 1.19.2
- Installed Mods: MTR Railway

**Comment by saleem0915** [comment]
Check if you have the hide train on in the options

**Comment by AdhamHakki** [comment]
> Check if you have the hide train on in the options

Now it says "Path not generated" when I refresh the path

**Comment by jonafanho** [comment]
Please watch the tutorial videos carefully. Check that your sidings are long enough (at least 26 blocks long) and trains have a path to get back to the sidings after the last route.
