### ISSUE TITLE
Shaders compatibility for 1.12.2

### ISSUE THREAD

**Issue by bengrebe** [jonafanho/Minecraft-Transit-Railway#5]
I know it's in alpha build and I'm not sure if this is a thing for earlier versions but I just wanted to mention that in 1.12.2, the transits are always fully visible on any lighting level, which makes every shaderpack think that the transits are supposed to be glowing and it makes them bright and blinding.

**Comment by jonafanho** [comment]
Thank you for pointing this out. In a future version, this will be fixed by having two different shading levels for the interior and exterior of the train. Let me know if this fixes it.
