### ISSUE TITLE
allow us to hide route that are displayed on psd/platform gates

### ISSUE THREAD

**Issue by JLC87** [jonafanho/Minecraft-Transit-Railway#50]
like maybe u shift-right click with brush on psd/gates then u get a gui allow u to choose what lines to be displayed and what not (routes and desnation) to so for example u have normal TSL on a platform and another special line you can choose to only display TSL on psds but the special line still works

i think its better to make a post here idk if u will miss any on discord and i dont want to brother u by pinging lol

**Comment by jonafanho** [comment]
Don't think this is necessary now that displaying branch routes have been implemented. Thanks for your suggestion!
