### ISSUE TITLE
why is so many trains here

### ISSUE THREAD

**Issue by Merth1** [jonafanho/Minecraft-Transit-Railway#505]
- Minecraft Version:1.19.2

![2022-09-22_18 33 54](https://user-images.githubusercontent.com/76266348/191792219-4fe63ba9-d03f-481a-948a-e32cc848954a.png)
 
- Installed Mods:
![image](https://user-images.githubusercontent.com/76266348/191792418-8484bed5-d3ff-446c-8759-9e9ba7ea995f.png)

**Comment by Merth1** [comment]
yes i created a new world and i tried change the train type and nothing changed
![Uploading 2022-09-22_19.39.07.png…]()

**Comment by Merth1** [comment]
yes i created a new world and tried change the train type and nothing changed
![2022-09-22_19 39 07](https://user-images.githubusercontent.com/76266348/191804745-25e1cc24-e920-4053-ad6f-95b89cc8096f.png)

**Comment by jonafanho** [comment]
Thanks, I'll look into it. It could also be due to some conflicting mods.

**Comment by kaan-guven** [comment]
Hi jonafanho, I too, seem to have the same (or similar) problem (screenshot and mod folder contents attached). Could you help me to resolve? Changing train settings (type etc.) did not solve it. Thanks!

![image](https://user-images.githubusercontent.com/61099781/194121844-017b8a79-188a-414d-9d2c-3004319cabfb.png)
![minecraft_mods_screenshot](https://user-images.githubusercontent.com/61099781/194121996-036b8534-3041-4e85-a21d-2988308b016e.PNG)

**Comment by kettle-7** [comment]
The best solution I can think of is to update to 3.1.2, change the train type in all the sidings then refresh and clear

**Comment by kettle-7** [comment]
Also worth mentioning is that architectury is for forge, not fabric, so I suggest to remove it

**Comment by kaan-guven** [comment]
Thanks kettle-7. Let me check your suggestions and get back. I forgot to mention that I'm using TLauncher. Architectury might be the culprit.
I guess the curved portions of the tracks should be large enough to accommodate the size of the trains, too (unlike mine!).
Cheers.

**Comment by Ultimate-USA-YT** [comment]
> Thanks kettle-7. Let me check your suggestions and get back. I forgot to mention that I'm using TLauncher. Architectury might be the culprit. I guess the curved portions of the tracks should be large enough to accommodate the size of the trains, too (unlike mine!). Cheers.

Cracked Launchers of Minecraft Are not Supported.

**Comment by jonafanho** [comment]
Hmm still kinda stumped about this issue, but thanks for the extra information.

**Comment by BDark000** [comment]
This seems to be an issue of TLauncher. Since we know very little about the differences between minecraft started with TLauncher vs other launchers, it's really hard to tackle this issue.

**Comment by BDark000** [comment]
Hello guys, what's the language of your Windows and minecraft? @Merth1 @kaan-guven

**Comment by Merth1** [comment]
> Hello guys, what's the language of your Windows and minecraft? @Merth1 @kaan-guven

My windows language turkish and minecraft tlauncher

**Comment by kettle-7** [comment]
Very strange, but everybody who has this bug seems to have their windows locale set to Turkish

**Comment by jonafanho** [comment]
Found the issue! https://stackoverflow.com/questions/11063102/using-locales-with-javas-tolowercase-and-touppercase

**Comment by jonafanho** [comment]
@Merth1 @kaan-guven @bekase Please try the latest version, 3.1.5, and see if it fixes this issue!

**Comment by bekase** [comment]
![2022-10-22_09 33 55](https://user-images.githubusercontent.com/64775258/197324254-f72dc14f-b0ea-4670-b069-95497aecf6a2.png)
![2022-10-22_09 34 01](https://user-images.githubusercontent.com/64775258/197324257-97f8d830-74a9-4eaf-91fe-059b163458d6.png)
Trains are normal now, thanks!

**Comment by jonafanho** [comment]
Great, Thanks for verifying.
