### ISSUE TITLE
Mod Not Detected

### ISSUE THREAD

**Issue by Thekielgamer** [jonafanho/Minecraft-Transit-Railway#506]
**Expected Behaviour**
MTR Mod section Found

**Actual Behaviour**
It just shows my other mods

**Reproduction Steps**
Steps to reproduce the behaviour:

1.

**Crash Report**
No Crash

**Screenshots**

**Environment**

- Minecraft Version:  1.16.5
- Installed Mods: chestcavity,modern elevators, modmenu, fabric api

**Additional Information**
None

**Comment by jonafanho** [comment]
I'm sorry, I don't really understand the problem here

**Comment by Thekielgamer** [comment]
> I'm sorry, I don't really understand the problem here

![Screenshot (232)](https://user-images.githubusercontent.com/114273595/192089458-b1a60b08-b0bb-475d-88a5-38b6de509654.png)
![Screenshot (233)](https://user-images.githubusercontent.com/114273595/192089474-7f306dd9-7a01-493c-8668-32be7f8457eb.png)
I actually installed a stable version but didint work

**Comment by Thekielgamer** [comment]
> > I'm sorry, I don't really understand the problem here
> 
> ![Screenshot (232)](https://user-images.githubusercontent.com/114273595/192089458-b1a60b08-b0bb-475d-88a5-38b6de509654.png) ![Screenshot (233)](https://user-images.githubusercontent.com/114273595/192089474-7f306dd9-7a01-493c-8668-32be7f8457eb.png) I actually installed a stable version but didint work

![Screenshot (233)](https://user-images.githubusercontent.com/114273595/192089689-051ed13e-88ea-4256-ad88-6f90bf037a1c.png)
another screenshot

**Comment by Thekielgamer** [comment]
Another Screenshot 
![Screenshot (235)](https://user-images.githubusercontent.com/114273595/192089738-78ce3821-01dc-4b8b-bbd4-97ae2c724642.png)

**Comment by jonafanho** [comment]
First of all, if you want the Minecraft Transit Railway mod, you shouldn't install Modern Elevators and Escalators as well. Second, please use the latest version of all mods. The latest version of the Minecraft Transit Railway is 3.1.0.

**Comment by Thekielgamer** [comment]
> First of all, if you want the Minecraft Transit Railway mod, you shouldn't install Modern Elevators and Escalators as well. Second, please use the latest version of all mods. The latest version of the Minecraft Transit Railway is 3.1.0.

Thanks
