### ISSUE TITLE
Train dropping off at depot

### ISSUE THREAD

**Issue by Thekielgamer** [jonafanho/Minecraft-Transit-Railway#508]
**Expected Behaviour**
train drops off platform rail

**Actual Behaviour**
Drops off at depot 
**Environment**
- Minecraft Version: 1.16.5
- Installed Mods: chestcavity,modmenu,MTR,worldedit,fabric api

**Comment by Ultimate-USA-YT** [comment]
This is Normal Behavior. When a Train Arrives at the Siding, the Passengers are Dismounted Automaticly
