### ISSUE TITLE
A train that can be driven automatically or manually

### ISSUE THREAD

**Issue by Polish-ball-man** [jonafanho/Minecraft-Transit-Railway#51]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Example: I'm always frustrated when...
Because I can’t drive manually and can only stand in the front of the car, I’m sad
**Describe the solution you'd like**
Can switch between automatic and manual driving modes
**Additional Information**
what is this?

**Comment by jonafanho** [comment]
The mod is designed for automatic train operation, that's why there are configurable schedules. There are other mods out there that provide manual driving. I don't plan on adding manual driving in the near future, sorry about that.

**Comment by JLC87** [comment]
i wanted automatic driving before but now i want both lol

lets wait for redstone psds and real train mod if has 1.16 fabric
