### ISSUE TITLE
Lines with distinguishable high speed (express) and all stop trains

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [jonafanho/Minecraft-Transit-Railway#511]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when there's no way to distinguish between all-stop and express trains (without using route numbers), and 2 lines are bad.

**Describe the solution you'd like**
There are 2 Lines Between Express And All-Stop Trains, But I want to make it into one line.
![image](https://user-images.githubusercontent.com/40109698/192777307-8ff09804-58f3-4f29-9c3f-ff17e25ca549.png)

**Additional Information**

**Comment by kettle-7** [comment]
Maybe the Hide Route option does what you're looking for? If you set the express route to hidden it should hide it from the system map.

On a completely unrelated topic, having that many tabs open ought to lag your computer?
