### ISSUE TITLE
Locked elevator door still open

### ISSUE THREAD

**Issue by Big-Cake-jpg** [jonafanho/Minecraft-Transit-Railway#515]
**Expected Behaviour**
Locked elevator door shouldn't open

**Actual Behaviour**
Locked door still open when the elevator stopped

**Reproduction Steps**
Steps to reproduce the behaviour:

1. build an elevator
2. lock elevator door
3. call the elevator

**Crash Report**
No any crash report

**Screenshots**
![image](https://user-images.githubusercontent.com/76810494/194483860-13bcd5a1-a500-4758-a504-bf89516c7060.png)
![image](https://user-images.githubusercontent.com/76810494/194483890-58145e27-4f23-45f3-8585-716dac58aab1.png)

**Environment**

- Minecraft Version: 1.16.5 on Fabric Loader 0.14.9
- Installed Mods: MTR, MTR-LU-Addon, JCM

**Comment by saleem0915** [comment]
Did you lock them in the open position?

**Comment by Big-Cake-jpg** [comment]
> Did you lock them in the open position?

No. I locked them after the elevator left.

**Comment by saleem0915** [comment]
@jonafanho Do you know a fix?

**Comment by jonafanho** [comment]
Fixed in 3.1.3, thanks!
