### ISSUE TITLE
Player sits down while on elevator, not stands up

### ISSUE THREAD

**Issue by Neon4UltraPlays** [jonafanho/Minecraft-Transit-Railway#518]
![2022-10-16_06 40 41](https://user-images.githubusercontent.com/90380800/196011465-11164b81-2c69-4a22-9a54-a94926512883.png)
Dear MTR mod developers,
When I go in to the elevator, my character's movement is sittting down at the elevator. This doesn't happen on trains, but it happens on elevators. Please help resolve this issue of riding the elevator but the character is sitting down.

**Comment by jonafanho** [comment]
This should be fixed in the latest version (3.1.2). Thanks.
