### ISSUE TITLE
Player falls out of the train when train does a 90 degree turn

### ISSUE THREAD

**Issue by orangegrouptech** [jonafanho/Minecraft-Transit-Railway#52]
**Expected Behaviour**
The player is supposed to stay on the train.

**Actual Behaviour**
When the player leans on the door on the side that the train is about to turn to, the player will fall out of the train after the train turns. Doors are still closed and shift was not pressed.

**Reproduction Steps**
Steps to reproduce the behaviour:
1. Enter a train
2. Lean on the door on the side that the train is turning to (eg if the train is turning right lean to the door on the right, if train is turning left then lean to the door on the left)
3. Player would fall out of the train after the 90 degree turn has been completed

**Crash Report**
None

**Screenshots**
Can't upload video here because it's too big. Uploaded to OneDrive: https://1drv.ms/u/s!AorrhabTMX03m3UmciU3ZVPUXyrM?e=yBYahj

**Environment**
- Minecraft Version: 1.16.3
- Installed Mods: MTR, Fabric, Hole Filler
- OS: Windows 10 21H1 Enterprise 64-bit (19043.985)

**Comment by Eric28020** [comment]
You know you should slow the train down by downgrading the curved track sections (Example: Diamond rail [300 km/h] to Blaze rail [160 km/h], Blaze Rail [160 km/h] to Obsidian Rail [120 km/h], Obsidian Rail [120 km/h] to Steel Rail [80 km/h], Steel Rail [80 km/h] to Stone Rail [40 km/h], & Stone Rail [40 km/h] to Wooden Rail [20 km/h]) to prevent this from happening.

**Comment by 16-squared** [comment]
the tighter the turns, the slower you must go to not fall out.
