### ISSUE TITLE
Train does not spawn / is non-visible

### ISSUE THREAD

**Issue by spe3tra** [jonafanho/Minecraft-Transit-Railway#520]
**Expected Behaviour**
Train was expected to generate at siding and station according to schedule.

**Actual Behaviour**
Audio cues and information display systems function correctly as if train is present, while train does not appear to spawn, or is non-visible. Expected position can be tracked via audio. No collisions are present, and driver key seems to have no effect in position where train is expected to be. 

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Created empty minecraft profile, installed with Forge, Architectury, and MTR. No game settings are changed.
2. Generated a blank superflat creative world
3. Created a small route containing two stations and one depot
4. Setup basic route and schedule between stations.
5. Waited for several loops to confirm results.

**Environment**

- Minecraft Version: 1.19.2, 
- Forge Versions tested: 43.1.1, 43.1.27, 43.1.43
- Installed Mods: MTR 1.19.2-3.1.3, Architectury 6.2.46

**Screenshots**
![2022-10-16_14 17 36](https://user-images.githubusercontent.com/23707111/196058800-db1c7ad3-6592-44c9-ab23-29644bf57488.png)
![2022-10-16_14 00 01](https://user-images.githubusercontent.com/23707111/196058803-860514dd-685f-4932-bbd4-05c7961c314e.png)

**Comment by jonafanho** [comment]
Try making the siding longer (at least 26 blocks long) or go to the Depots tab on the Railway Dashboard and click on the white square representing the siding and choose a "mini" train.

**Comment by spe3tra** [comment]
Fixed the issue
