### ISSUE TITLE
Add buses to MTR mod

### ISSUE THREAD

**Issue by Neon4UltraPlays** [jonafanho/Minecraft-Transit-Railway#522]
I want buses to be added to the Minecraft Transit Railway mod.
As shown of **jonafanho** riding the first bus line: https://www.youtube.com/watch?v=pEhV2QsncWc I want to create a bus line and I wish it could be added to the actual mod!

Add the following buses:
- Enviro 200 - 400
- Chinese buses
- Macao buses
- and more!

Thank you!

**Comment by jonafanho** [comment]
Similar to #384

**Comment by chortle3** [comment]
> Similar to #384

How is it similar? The one you're asking is how planes should be added. Maybe there's a typo or a mistake.

**Comment by jonafanho** [comment]
It's asking for a new transport type, not to mention that buses and planes have been suggested many times before. Both of these will come soon; thank you for your patience!
