### ISSUE TITLE
Spawn items not showing in creative menu and can't be given through commands.

### ISSUE THREAD

**Issue by AlephNoodle** [jonafanho/Minecraft-Transit-Railway#524]
**Expected Behaviour**
Spawn items appearing in creative menu in the mod's respective creative menu tabs.

**Actual Behaviour**
Spawn Items not appearing in creative menu or from the give command.

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Enter the creative menu.
2. Go to any of the mod's creative menu tabs.

**Screenshots**
![2022-10-20_21 13 14](https://user-images.githubusercontent.com/116330588/197111842-83217e4d-8d3f-42da-ae79-f2fca8a213f2.png)
![mods 10_20_2022 9_34_03 PM](https://user-images.githubusercontent.com/116330588/197113329-71e97736-1750-470c-887b-d587fbcf362e.png)

**Environment**

- Minecraft Version: 1.19.2
- Forge Version: 43.1.43
- Installed Mods: 
Applied Energistics 2
Architectury API (Fabric/Forge)
Balm (Forge Edition)
Bookshelf
Camera Mod
Corpse
Create
Create Deco
Curios API (Forge)
Dragon Mounts: Legacy
Easy Villagers
Enchantment Descriptions
GeckoLib
Macaw's Bridges
Macaw's Furniture
Macaw's Lights and Lamps
Mekanism
Mekanism Additions
Mekanism Generators
Mekanism Tools
Minecraft Transit Railway
Moonlight Lib
MrCrayfish's Furniture Mod
Nosiphus Furniture Mod
Patchouli
Simple Planes (Forge)
Supplementaries
Unoffical Turned Port
Valhelsia Core
Vampirism - Become a vampire!
ViesCraft Machines
Waystones
Werewolves - Become a Beast!

**Comment by jonafanho** [comment]
The Lift / Elevator Refresher is now used instead of the spawn items. I encourage you to join the Discord server to be notified about the latest updates.
