### ISSUE TITLE
VVVF和電機音 | VVVF and Motor sounds

### ISSUE THREAD

**Issue by ACS-resources** [jonafanho/Minecraft-Transit-Railway#526]
- [ ] 已解决 | Solved

列车在保持同一速度时电机音听上去很不自然。  
列車在保持同一速度時電機音聽上去很不自然。  
The motor sound seems to be a bit unnatural and frustrating when the train is running at a fixed speed.  

**解决方案  |  解決方案  |  Solution**  
可以尝试使用Rail Train Mod(RTM)的方式，将电机不同频率阶段的声音拆开来，再通过变速播放来实现比较真实和自然的电机音。  
可以嘗試使用Rail Train Mod(RTM)的方式，將電機不同頻率階段的聲音拆開來，再通過變速播放來實現比較真實和自然的電機音。  
It would be solved via a way similar to that of Rail Train Mod(RTM), which is to separate the sound of the motor by different stages of frequencies, and then play them with different speeds to make the sound of the motor more realistic and natural.

**Comment by jonafanho** [comment]
Would you be able to provide some sounds for me (preferably in the BVE format)? I'm looking for permission to use sounds to avoid legal troubles.

**Comment by ACS-resources** [comment]
很抱歉，我没有这样的资源啊……
>也许可以用[OTOTESU](https://play.google.com/store/apps/details?id=com.qtsoundlab.ototetsu&hl=en_US&gl=US)生成音频文件？  

很抱歉，我沒有這樣的資源啊......
>也許可以用[OTOTESU](https://play.google.com/store/apps/details?id=com.qtsoundlab.ototetsu&hl=en_US&gl=US)生成音頻文件?

Sorry, but I haven't got any...  
>_Maybe you can use ones generated by [OTOTESU](https://play.google.com/store/apps/details?id=com.qtsoundlab.ototetsu&hl=en_US&gl=US)?_

**Comment by kettle-7** [comment]
> * [ ]  已解决 | Solved
> 
> 
> 列车在保持同一速度时电机音听上去很不自然。 列車在保持同一速度時電機音聽上去很不自然。 The motor sound seems to be a bit unnatural and frustrating when the train is running at a fixed speed.
> 
> **解决方案 | 解決方案 | Solution** 可以尝试使用Rail Train Mod(RTM)的方式，将电机不同频率阶段的声音拆开来，再通过变速播放来实现比较真实和自然的电机音。 可以嘗試使用Rail Train Mod(RTM)的方式，將電機不同頻率階段的聲音拆開來，再通過變速播放來實現比較真實和自然的電機音。 It would be solved via a way similar to that of Rail Train Mod(RTM), which is to separate the sound of the motor by different stages of frequencies, and then play them with different speeds to make the sound of the motor more realistic and natural.

This functionality is in the mod (see 1995 stock) but very few trains we actually have recorded sounds of, so the old sound system is still used for them

**Comment by ACS-resources** [comment]
> > * [ ]   已解决 | Solved
> > 
> > 列车在保持同一速度时电机音听上去很不自然。 列車在保持同一速度時電機音聽上去很不自然。 The motor sound seems to be a bit unnatural and frustrating when the train is running at a fixed speed.
> > **解决方案 | 解決方案 | Solution** 可以尝试使用Rail Train Mod(RTM)的方式，将电机不同频率阶段的声音拆开来，再通过变速播放来实现比较真实和自然的电机音。 可以嘗試使用Rail Train Mod(RTM)的方式，將電機不同頻率階段的聲音拆開來，再通過變速播放來實現比較真實和自然的電機音。 It would be solved via a way similar to that of Rail Train Mod(RTM), which is to separate the sound of the motor by different stages of frequencies, and then play them with different speeds to make the sound of the motor more realistic and natural.
> 
> This functionality is in the mod (see 1995 stock) but very few trains we actually have recorded sounds of, so the old sound system is still used for them

Erm... It's true that some of the frequently used trains are not sorted out yet...
Software generation may be more convenient. After adding some white noise, the engine sound should be more realistic.

**Comment by kettle-7** [comment]
Software generation leaves the issue of copyright requirements, self recorded is best because we can be sure we're not going to have legal issues
