### ISSUE TITLE
system map not working

### ISSUE THREAD

**Issue by whitejesus69** [jonafanho/Minecraft-Transit-Railway#528]
The system map is not working, I tried all the different combinations such as
serveripaddres:8888/index.html.
:(

![image](https://user-images.githubusercontent.com/115583534/197606404-e3b08f50-70bc-4c93-b766-d97258772031.png)

**Expected Behaviour**

**Actual Behaviour**
A clear and concise description of what actually happened.

**Reproduction Steps**
Steps to reproduce the behaviour:

1.

**Crash Report**
Attach a crash report to the issue.

**Screenshots**

**Environment**

- Minecraft Version:
- Installed Mods:

**Additional Information**
Anything else you want to add?

**Comment by saleem0915** [comment]
the link should be localhost:8888 for fabric and localhost:8888/index.html

**Comment by jonafanho** [comment]
Is your world open? There could be a bunch of reasons why you can't load it.

**Comment by kettle-7** [comment]
Likely the computer hosting the server has not forwarded port 8888

**Comment by saleem0915** [comment]
What OS are you using?

There are specific ways to see if ports are opened or not

**Comment by whitejesus69** [comment]
I'm playing on a server that is hosted by pebblehost,
Windows 11 as an OS
and the world is open...
also I tried all different combinations :/

**Comment by XHG78999** [comment]
> 

Server hosted by third-party partners may not open the specified port. You can contact to you hosting partners to get more solution about make a NAT with other ports, like dynamic maps.
