### ISSUE TITLE
Custom station signs / projectors with resource or data packs

### ISSUE THREAD

**Issue by ajh123** [jonafanho/Minecraft-Transit-Railway#529]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
This would allow servers or players to create custom [station name signs](https://github.com/jonafanho/Minecraft-Transit-Railway/wiki/Station-Name). This could allow one to use custom text or images on their station sings without having to make a complex mod. These custom signs could also have custom sizes e.g. one could be 2x2 blocks and another could be 1x1.5 blocks, this would better suite different images. This would allow better customisation for roleplay servers, as resource packs can be made much easier than a mod.

**Additional Information**
This could probably be combined with #428. This would probably be complex to implement (as you need to dynamically create items in the creative menu). But stuff like this has been done in other mods e.g. in MrCrayfish's vehicle mod, vehicles can be registered by datapacks and each new vehicle is put as an extra item in the creative menu.

**Comment by jonafanho** [comment]
Similar to #146

**Comment by ajh123** [comment]
@jonafanho This suggestion isn't excatly the same as #146, as #146 is about removing the word "station" from signs.

This suggestion is about creating new Station Name signs that don't depend on the actual colour or name of the station.

However, I don't think MTR needs it as other mods like Mishang Urban Construction have this feature.
