### ISSUE TITLE
Train routing, Dashboard enhancement, Noise barriers, Overhead line systems | 指定路線，儀表盤的優化，隔音板，接觸網

### ISSUE THREAD

**Issue by ACS-resources** [jonafanho/Minecraft-Transit-Railway#530]
- [x] 已解决(如果没必要或没办法，直接关掉这个Issue就行了) | Solved (If not necessary or unsolvable, just go ahead and close this issue)
#### 問題 | Problem
自动化铁路系统很容易被弄乱。快车有时不走越行线，同一条线路的大小交路与上下行线不得不分开来。
Sometimes the automatic train system causes confusion, especially when using the one-way rails and turn-back rails; Express trains can sometimes go onto rails which Local trains use, rather than overtake rails, making the potential risk of creating jams or "crashes". Long & short running routes can be messed together; The bounds of a single train has to be separeted into two routes, easily mixed together with other lines in the dashboard. 

也许可以加入隔音板？这样经过居民区的架空线路就会更真实。
Noise barriers and protection fences on bridges is also really hard to make (Is it even possible to design and program barrier nodes?)

架空接触网系统照理来说应该加入到模组中，大多数城市都有架空接触网，轨道供电并不是唯一的供电方式。
Overhead line system is needed due to the fact that many cities have i t(Possibly design different types of wires, and catenary masts?).

#### 解決方案 | Solution
允许用户通过选择铁路节点来定义指定线路，允许用户将相同线路在仪表盘分在一组中，避免弄混。
Make some method of selecting (not necessarily) adjacent rail nodes to make trains go on a specific custom track in a specific direction, rather than only via selecting platforms; allow users to group different bounds of one train line together in the dashboard.

**Comment by SteveNotSet** [comment]
隔音板建议使用附加模组或原版方块自己做
关于接触网，Jon Ho之前说过不是很想做，除非充值（

**Comment by XHG78999** [comment]
> * [ ]  已解决(如果没必要或没办法，直接关掉这个Issue就行了) | Solved (If not necessary or unsolvable, just go ahead and close this issue)
> 
> #### 問題 | Problem
> 自动化铁路系统很容易被弄乱。快车有时不走越行线，同一条线路的大小交路与上下行线不得不分开来。 Sometimes the automatic train system causes confusion, especially when using the one-way rails and turn-back rails; Express trains can sometimes go onto rails which Local trains use, rather than overtake rails, making the potential risk of creating jams or "crashes". Long & short running routes can be messed together; The bounds of a single train has to be separeted into two routes, easily mixed together with other lines in the dashboard.
> 
> 也许可以加入隔音板？这样经过居民区的架空线路就会更真实。 Noise barriers and protection fences on bridges is also really hard to make (Is it even possible to design and program barrier nodes?)
> 
> 架空接触网系统照理来说应该加入到模组中，大多数城市都有架空接触网，轨道供电并不是唯一的供电方式。 Overhead line system is needed due to the fact that many cities have i t(Possibly design different types of wires, and catenary masts?).
> 
> #### 解決方案 | Solution
> 允许用户通过选择铁路节点来定义指定线路，允许用户将相同线路在仪表盘分在一组中，避免弄混。 Make some method of selecting (not necessarily) adjacent rail nodes to make trains go on a specific custom track in a specific direction, rather than only via selecting platforms; allow users to group different bounds of one train line together in the dashboard.

隔音板已经被我用1m车厂列车做出来了

**Comment by 52PD** [comment]
> 架空接触网系统照理来说应该加入到模组中，大多数城市都有架空接触网，轨道供电并不是唯一的供电方式。

架空接触网有人做了：https://www.curseforge.com/minecraft/mc-mods/mtr-station-decoration
