### ISSUE TITLE
Modification

### ISSUE THREAD

**Issue by gameyboy11** [jonafanho/Minecraft-Transit-Railway#535]
Would I have permission to modify the mod? I was thinking of adding my own train variants for my world. I couldn't find anywhere else to put this, so I put it here

**Comment by gameyboy11** [comment]
Nevermind, I just realised it's open source, if there's any issues with making my own then just put them here and I'll delete it

**Comment by saleem0915** [comment]
You can do so by just making a resource pack; @jonafanho has a tutorial series on how to do this.

**Comment by jonafanho** [comment]
Yes, the video is here: https://www.youtube.com/watch?v=QH1O-y6kPSk&list=PLp0jZgheSlXv_vjilwnbrOtdbmgvz1VkC
The mod is licensed with the MIT license, which means you can look at the source code and existing models.

**Comment by kettle-7** [comment]
I would strongly suggest using the Resource Pack Creator item to add new trains, however you can fork the mod and add trains that way, only bear in mind that it's a lot of work to keep your own branch up to date with all the new features and other people may be hesitant to download the forks. If it's a train you can find irl in London, New York or Hong Kong it may well get added to the main mod.

**Comment by gameyboy11** [comment]
Ok thanks, and I doubt it will be added officially as it's a train service for my world, with names from cities.

**Comment by Ultimate-USA-YT** [comment]
> I would strongly suggest using the Resource Pack Creator item to add new trains, however you can fork the mod and add trains that way, only bear in mind that it's a lot of work to keep your own branch up to date with all the new features and other people may be hesitant to download the forks. If it's a train you can find irl in London, New York or Hong Kong it may well get added to the main mod.

Well, we are Getting a Train from León and Germany

**Comment by gameyboy11** [comment]
Well, we are Getting a Train from León and Germany
