### ISSUE TITLE
[Softlock] Infinite Resource Pack Reload

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [jonafanho/Minecraft-Transit-Railway#543]
**Expected Behaviour**
The Game Would run.

**Actual Behaviour**
After completely loading, MTR immediately Reloads Resource Pack, and After Reloading, MTR immediately Reloads Resource Pack. Again.
This even happens without Resource Packs.

**Reproduction Steps**
Steps to reproduce the behaviour:

too complex, this is hard to reproduce this behaviour, but
1. Install MTR-fabric-1.18.2-3.1.8-hotfix-1.
2. Done.

**Crash Report**
[crash-2022-11-13_22.24.41-client.txt](https://github.com/jonafanho/Minecraft-Transit-Railway/files/9997276/crash-2022-11-13_22.24.41-client.txt)
Forced Crash Via F3+C

**Screenshots**

**Environment**

- Minecraft Version: 1.18.2-fabric
- Installed Mods:
![image](https://user-images.githubusercontent.com/40109698/201523929-a5d0baab-cfb0-4a44-bb39-7bfe35fb644d.png)

**Additional Information**
Anything else you want to add?

**Comment by jonafanho** [comment]
How much ram did you allocate? Try adding more.

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
8gb, my computer is 12gb and trying to increasing might cause memory leak

**Comment by jonafanho** [comment]
Make sure Joban Client Mod is up to date as well. A lot of players have been having loops because they didn't update the mod.

**Comment by EpicPuppy613** [comment]
> Make sure Joban Client Mod is up to date as well. A lot of players have been having loops because they didn't update the mod.

Its because of the PIDS changes I implemented a little bit ago. I tried playing with all add-ons with my dev build and got this same issue.
