### ISSUE TITLE
請添加香港港島區電車，謝謝

### ISSUE THREAD

**Issue by pokOSlanx** [jonafanho/Minecraft-Transit-Railway#550]
這個mod對於城市建設來說的確很好，但是有一個問題：一個城市的公共交通不只有地鐵，還會有巴士，比如我居住的香港觀塘秀茂坪區都有港鐵觀塘綫，九巴213M,213B,213C等，還有綠色專線小巴。
我之前反饋過添加巴士，但似乎受到了拒絕，原因是沒有固定的軌道。但是你在這裡也提到了會添加空客AirBus A380，證明虛擬軌道也是可以的。現在香港大部分巴士都有固定的路線，比如290X就是走寶琳路來往秀茂坪和將軍澳，而不會走將軍澳公路。所以，請添加電車和巴士，謝謝！

**Comment by pokOSlanx** [comment]
或者你可以嘗試添加E500MMC，E200這樣子的巴士？

**Comment by BDark000** [comment]
不好意思，Jonathan目前只接受鑽石級贊助者的增加鐵路車輛建議。
另，我們的Discord社群中創作者及職員之一Navi_LX9702已創建內含香港巴士的資源包，且會持續更新，歡迎下載。
