### ISSUE TITLE
Game crashes when launching Minecraft with 1.18.2 Forge 3.1.9

### ISSUE THREAD

**Issue by chortle3** [jonafanho/Minecraft-Transit-Railway#554]
Hello MTR Mod,
When using Forge 1.18.2 version of 3.1.9, the game crashes every time when launching with Forge.

Minecraft Version:
ForgeOptifine 1.18.2
MTR Mod Version:
Forge 1.18.2 - mod version 3.19

The Mod list is in the crash reports
CRASH REPORTS:
[crash-2022-11-18_21.45.48-client.txt](https://github.com/jonafanho/Minecraft-Transit-Railway/files/10080899/crash-2022-11-18_21.45.48-client.txt)
[crash-2022-11-24_11.46.06-client.txt](https://github.com/jonafanho/Minecraft-Transit-Railway/files/10080900/crash-2022-11-24_11.46.06-client.txt)

Please fix this issue. Thank you!

**Comment by jonafanho** [comment]
Please update all mods, especially the Joban Client Mod.

**Comment by chortle3** [comment]
https://github.com/jonafanho/Minecraft-Transit-Railway/issues/559
