### ISSUE TITLE
Issue with losing the button to confirm settings when changing the Minecraft screen size when setting up a route in the Railroad Dashboard in windows.

### ISSUE THREAD

**Issue by mull1111** [jonafanho/Minecraft-Transit-Railway#557]
**Expected Behaviour**
If you resize the Minecraft screen, the buttons should remain visible.

**Actual Behaviour**
The done button disappears when resizing the Minecraft screen

**Reproduction Steps**
Steps to reproduce the behaviour:

1.From the railroad dashboard, open a screen called routes.
2.Resize the Minecraft screen (e.g., multitasking)

**Crash Report**
None

**Screenshots**
(https://user-images.githubusercontent.com/119109827/204086509-7c53df0a-d6c0-4746-94c2-40815221c3d1.png)

**Environment**

- Minecraft Version:1.19.2 forge43.1
- Installed Mods:minecraft transit rairway,[Architectury],WorldEdit

**Comment by mull1111** [comment]
I can deal with it by using the esc key, but it is inconvenient to have to re-set it if this happens the first time it is set up. Also, updating the minecraft transit rairway to the latest version (3.1.10) does not solve this problem. Also, even after deleting worldedit, the problem persists, so I assumed it was a minecraft transit rairway issue.

**Comment by saleem0915** [comment]
@jonafanho
Do you know what's going on?

**Comment by mull1111** [comment]
Sorry, but I am not sure.
What information do I need?

**Comment by mull1111** [comment]
Thank you for the correction.
