### ISSUE TITLE
Game crashes when launching Minecraft with 1.18.2 Forge 3.1.9 (FOLLOW-UP) #554

### ISSUE THREAD

**Issue by chortle3** [jonafanho/Minecraft-Transit-Railway#559]
**Expected Behaviour**
The Game will run smoothly and is able to play.

**Actual Behaviour**
The game crashes when launching. I have updated every outdated mod I can find, **Including the Joban Cilent Mod, Architectury, and London Underground, to the latest version.** Without MTR Mod 3.1.9, the game runs smoothly and doesn't crash. But With MTR Mod 3.1.9, the game crashes.

How to reproduce the behaviour:
1. Download Forge MTR 3.1.9 and Architectury
2. Load ForgeOptifine 1.18.2
3. Game crashes

**Crash Report**
[crash-2022-11-28_07.45.13-client.txt](https://github.com/jonafanho/Minecraft-Transit-Railway/files/10099590/crash-2022-11-28_07.45.13-client.txt)

**Environment**

- Minecraft Version: Forge Optifine 1.18.2
- Installed Mods: 
![Screenshot 2022-11-28 075144](https://user-images.githubusercontent.com/94771839/204169947-a1ef2266-420e-48a3-9c45-f7a1a0232d42.png)

**Additional Information**
1. Either make another version of Forge and update it or make 3.2.0 as a more enhanced and fixed version, with NO BUGS.
2. Please put this label as "Bug"

**Comment by chortle3** [comment]
https://github.com/jonafanho/Minecraft-Transit-Railway/issues/554

**Comment by jonafanho** [comment]
This is a crash with Macaw's Doors and has nothing to do with the Minecraft Transit Railway mod. Please use the 1.18.2 version instead of 1.19.2.
