### ISSUE TITLE
[Feature Request] Add planes

### ISSUE THREAD

**Issue by zurgeg** [jonafanho/Minecraft-Transit-Railway#562]
**Is your feature request related to a problem? Please describe.**
We have land transport (trains), water transport (boats), and air transport (kinda, with cable cars). I feel like air transport could be expanded on with planes. Also, it helps with the progression of transportation (walking, boats, horses, trains, planes)

**Describe the solution you'd like**
We should add planes too!

**Additional Information**
N/A

**Comment by Ultimate-USA-YT** [comment]
Already Done

**Comment by zurgeg** [comment]
> Already Done

When was the update including this released? I don't seem to have it.

**Comment by zurgeg** [comment]
Ah, I found it, thanks!
