### ISSUE TITLE
Player heads in Dynamic Railway Map failed to load in China Mainland

### ISSUE THREAD

**Issue by Big-Cake-jpg** [jonafanho/Minecraft-Transit-Railway#565]
**Expected Behaviour**
Player heads should be loaded properly.

**Actual Behaviour**
Player heads failed to load with HTTP Error code 403.
It must be caused by `mc-heads.net` blocked IPs in China Mainland.

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Start a server / game with MTR-3.1.10.
2. Open Dynamic Railway Map in Microsoft Edge in China Mainland.
3. Click settings button.
4. See problem.

**Crash Report**
No any crash report. The game / server didn't crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/76810494/205905365-1365fa5b-801a-447c-9a17-673e0a787698.png)

**Environment**

- Minecraft Version: 1.17.1 on Fabric Loader 0.14.11
- Installed Mods: MTR, MTR-LU-Addons, MTR-NTE

**Comment by jonafanho** [comment]
I'm not sure how I will resolve this. Is there another API for player head images that works in China?

**Comment by Big-Cake-jpg** [comment]
> I'm not sure how I will resolve this. Is there another API for player head images that works in China?

https://minotar.net
> UUID & Username, can set avatar size

https://crafatar.com
> UUID only

These 2 APIs are available in China Mainland. They can also be accessed smoothly in Mainlan China's network.

（这两个 API 都可以在中国大陆地区正常且快速的访问）

**Comment by jonafanho** [comment]
Thank you, I will update the website.
