### ISSUE TITLE
Planes not turning around on Turn Back Rail

### ISSUE THREAD

**Issue by Splatracer** [jonafanho/Minecraft-Transit-Railway#566]
**Expected Behaviour**
The plane should turn around and drive forwards.

**Actual Behaviour**
The plane stays in its current rotation and drives in reverse. This can cause the plane to take off from a runway in reverse too. 

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Build 2 basic setups of a runway and platform each, with one also having a siding.
2. Connect a Turn Back Rail to the platform on the second airport.
3. Create a route between both airports.
4. Let the plane fly. When departing the platform at the second airport, it should use the Turn Back Rail but not turn around. 

**Crash Report**
This bug/issue causes no crash.

**Screenshots**
I made a video of it flying in reverse
https://youtu.be/8Fx6bU52-Uo

**Environment**

- Minecraft Version: Fabric 1.19.2
- Installed Mods: MTR, Architerctury, Cloth Config, Fabric API, Litematica, Malilib

**Additional Information**
This is a visual glitch only but obviously doesn't make sense. Maybe it could be a funny easter egg though.

**Comment by jonafanho** [comment]
I recommend setting up an airport like this, so the plane can reverse out of the gate (platform), enter the turnback rail, and face forward again.

![image](https://cdn.discordapp.com/attachments/1012741175855296542/1047905633770422282/image.png)
