### ISSUE TITLE
Can't open www.patreon.com in China Mainland

### ISSUE THREAD

**Issue by CokeStudios** [jonafanho/Minecraft-Transit-Railway#568]
The game starts slowly because i can't open www.patreon.com. (Connection Time Out)

**Comment by gdshu1337** [comment]
其实您是否能够正常打开patreon网页与启动速度无关。我经常在没有联网（什么网页都不能上）的情况下玩MTR模组，也没见启动变慢。让启动变慢了，是在你电脑端其他的问题，例如可能有其它模组影响启动速度？还是开着游览器没关？还是电脑太旧不能流畅玩模组？但是作为一个经常断网玩mtr的人，我相信启动速度慢与是否能连到patreon没关系
