### ISSUE TITLE
Chinese mainland players can not load Patreon API normally

### ISSUE THREAD

**Issue by xiaotang27** [jonafanho/Minecraft-Transit-Railway#569]
Just like title. For network reasons, Chinese mainland players can not load Patreon API normally, so Minecraft always stuck in Mojang loading screen.

如题，因为网络原因，中国内地玩家无法正常加载Patreon API，所以Minecraft会一直卡顿在Mojang加载页面。

**Comment by Big-Cake-jpg** [comment]
A possible solution is click Minecraft window for many times when it's not responding, then click "Recovery this program".

一个可能的解决方案是多次点击未响应的 Minecraft 窗口，然后在弹出的窗口中选择“尝试还原此程序”

**Comment by CokeStudios** [comment]
我这边是mc窗口还没出现就停住了

**Comment by XHG78999** [comment]
这边认为比较好的方案是搭个大陆正常访问patreon的反代
I think setup a reverse proxy to patreon is well.

**Comment by jonafanho** [comment]
Duplicate of #568
