### ISSUE TITLE
Some questions about the mtr:seat

### ISSUE THREAD

**Issue by NiuBoss123** [jonafanho/Minecraft-Transit-Railway#570]
After using MTRmod's archive & server will appear unknown entity, also can't tp to this entity above, but has been attached to the player, after looking up and found to be mtr:seat, please ask this entity has not been removed, why still exist?

**Comment by Big-Cake-jpg** [comment]
More info: `met:seat` may spawn a pig around player, and many servers and players mentioned this issue.

**Comment by NiuBoss123** [comment]
![7741 9~L)`IIA{(FS`BCRJ1](https://user-images.githubusercontent.com/62463715/206862225-99504b3b-1c25-4323-b47c-319b4411a1b9.png)

**Comment by kettle-7** [comment]
> After using MTRmod's archive & server will appear unknown entity, also can't tp to this entity above, but has been attached to the player, after looking up and found to be mtr:seat, please ask this entity has not been removed, why still exist?

it's used for rendering the trains, there's not really much you can do about it

**Comment by jonafanho** [comment]
Please see #341
