### ISSUE TITLE
Better Broadcasting

### ISSUE THREAD

**Issue by mull1111** [jonafanho/Minecraft-Transit-Railway#578]
**Is your feature request related to a problem? Please describe.**
At this time, in-car announcements cannot be made without the use of a block.
That is a hassle because you have to go to the location. (I also don't really want to use the teleport command if I can help it, and it's a pain to remember the coordinates every time.)
Also, at the moment, I cannot change the broadcast that comes out immediately after the train departs, so I cannot arrange it in my own way. Furthermore, I can't even broadcast at stations, and I can't even broadcast with music because I can't easily put up audio in mp4 or ogg files.

**Describe the solution you'd like**
So, we would like to be able to easily add in-train announcements on the train dashboard.
Specifically, I would like to be able to easily play mp3 or ogg imported songs for in-train announcements, and I would like to be able to change the in-train announcements for each and every train line from the train depot settings so that I can change them between each and every station.
I would like to be able to change the broadcasts all at once, or in the advanced settings, for each station, one by one.
Also, currently, the system only broadcasts immediately after departure, but I would like it to be possible to add a song broadcast as many times as necessary.
I would also like to be able to specify how many seconds after departure the announcement will be made.
As an addition, I would like to see the creation of some sort of variable that can be used to create broadcasts. This would allow us to set up all broadcasts at once without having to create them all at once.
For example
Next station = @nextstation"
Previous Station = @PreviousStation"
Current station = @CurrentStation"
System number = @systemnumber"
Inner ring road = @Innerringroad"
Outer ring road = @Outerringroad"
Outer ring road = @Outerringroad, etc.
By adding a trailing delimiter and a preceding @, we can distinguish broadcasts from those that are variable.
Furthermore, the broadcast should be played at the station and where it is designated on the dashboard so that it can be played in the same way at the station.

**Additional Information**
I would be happy to keep the current broadcast block as it is and develop the features I have written about.
I know some people prefer the old block and have developed trains with it.

**Comment by 52PD** [comment]
You need to know you can actually achieve these by using announcements block or using train schedule block+command block😓

**Comment by 52PD** [comment]
Actually most feature you mentioned can achieve by using train schedule block with command block l.

Also since there are too many features you mentioned in your request, I feel Jonathan may not accept at this time just like any train type requests.😓

**Comment by 52PD** [comment]
Also there are some error in your requests😂:

> I would like to be able to easily play mp3
> I can't easily put up audio in mp4

Minecraft doesn’t support any mp4 and mp3 files, so just think about ogg files.

> As an addition, I would like to see the creation of some sort of variable that can be used to create broadcasts

You really need to look for how Minecraft commands looks like. All commands in you suggestion are incorrect😂

**Comment by mull1111** [comment]
It was indeed too long. Sorry.
Also, as for the mp3, I was hoping it would be an added bonus, so the ogg file is fine.

**Comment by mull1111** [comment]
Also, you don't have to put everything in at once, so in order of priority, you can
1. Allow for fine-tuning of broadcasts between all stations.
2. add a useful variable to allow changing the broadcasts at all stations at once from the train dashboard (without this, it would be difficult to change the broadcasts at once).
3. to be able to easily import ogg files so that they can be used for broadcasts.
4. use a block or dashboard to broadcast in the area designated for the station.
This is a good way to do this.
It would be difficult to create it all at once, so it would be easier for us to understand if it is created step by step.

Translated with www.DeepL.com/Translator (free version)

**Comment by mull1111** [comment]
By the way, I am a Japanese who is probably one of the few ethnic groups that use it, so I would like to spread the word on youtube and elsewhere.
I hope it will become a more and more wonderful tool in the future.
Also, is it OK if I write in Japanese? (By the way, I used deepl until now.)
Sorry for getting off topic. I don't want you to hurry to create the function, so please do it.

**Comment by 52PD** [comment]
> Allow for fine-tuning of broadcasts between all stations.
> add a useful variable to allow changing the broadcasts at all stations at once from the train dashboard (without this, it would be difficult to change the broadcasts at once).

I just think these for a while, I feel this will only make the mod hard to use (since it need need use to think about how to make the announcement can automatically detect next station’s name, and it may also have glitch when there are too many station and lines especially with shareable lines and loop lines). So forget these, these will not happen.

> to be able to easily import ogg files so that they can be used for broadcasts.

Again, go to YouTube to learn how to make a resource Pack.

> use a block or dashboard to broadcast in the area designated for the station. This is a good way to do this. It would be difficult to create it all at once, so it would be easier for us to understand if it is created step by step.

This is definitely impossible, and it will only make the announcement played in wrong area (like play in wrong platform snd in the hall).

> is it OK if I write in Japanese?

Since Jonathan lives in Hong Kong, please consider Chinese and English first.

**Comment by 52PD** [comment]
Also, here are two suggestions:

1. Since Jonathan lives in Hong Kong and this mod is based on Hong Kong’s Subway system named MTR, don’t ask feature that only appear in your local metro system but not available in MTR. Asking feature that Jonathan not familiar with can only be harder to make or give too many glitches. If you want adding some your local feature (like trains and announcements), make a resource pack by yourself.
2. Do not add too issue at same time, this will make you looks like doing vandalism and for most serious result, you may be banned from this repository.

**Comment by mull1111** [comment]
We are very sorry.
This is going to be difficult, so I will delete your post.
Thank you very much.
