### ISSUE TITLE
The buses don't show up 

### ISSUE THREAD

**Issue by Jeromey092** [jonafanho/Minecraft-Transit-Railway#579]
The buses do not appear, what do I do to make them appear?

**Comment by jonathanqwq** [comment]
I think that MTR has no buses?

**Comment by Jeromey092** [comment]
En el canal de Youtube han publicado que si los hay

**Comment by jonathanqwq** [comment]
Este debería ser el paquete de recursos del autobús, que se descarga en la comunidad de discord

> En el canal de Youtube han publicado que si los hay

**Comment by Jeromey092** [comment]
Me puedes dar el link de descarga, no encuentro ese paquete en discord

**Comment by jonathanqwq** [comment]
> Me puedes dar el link de descarga, no encuentro ese paquete en discord

Lo siento, no puedo hacer esto.
Pero puedo darle un enlace de mensajes
Después de abrir el enlace, debería poder ver la forma de descargar.
https://discord.com/channels/763273460465270816/953329579567767572/1034144797201539142

**Comment by saleem0915** [comment]
> I think that MTR has no buses?

MTR does have buses, they were introduced about 3 months ago

**Comment by saleem0915** [comment]
> The buses do not appear, what do I do to make them appear?

Please send as many details as possible. Have you set your siding up correctly?
