### ISSUE TITLE
Walk on the train without standing on a platform block

### ISSUE THREAD

**Issue by fallingx** [jonafanho/Minecraft-Transit-Railway#58]
On beta-6 I can only get on a train when standing on a platform block. That makes sense but I have lots of platforms built on deserts, forests, etc. and the row of blocks one block from the train which should be platform blocks were replaced by other blocks to match the environment. So now I can't walk onto a train on those platforms. Could you please add an option to let us decide whether players should be on a platform block to enter a train?

**Comment by JLC87** [comment]
for me, i use stone as floor or use carpets to cover the platform blocks 
you can just put psd/apgs, also the use of platform block is for train doors to open

**Comment by fallingx** [comment]
> for me, i use stone as floor or use carpets to cover the platform blocks
> you can just put psd/apgs, also the use of platform block is for train doors to open

Oh, you're right but I forgot to mention that those platform blocks were hidden one block under the platform to ensure train doors are open. A cross-section may look like this:
S S S W   R    S S
S S S P S S S S S 
where W is for wool, P is for platform block, and R is for rail. 
Yes the door will open in this way and that may be a bug but it does help to make the platform more customized.
Covering with carpets is a great solution in some cases. But humps on both sides of the platform still looks a bit strange.
Okay, I may be demanding here so it's only my ideas on the feature.

**Comment by jonafanho** [comment]
You can now place platform blocks on ground level and cover them up with one block.
