### ISSUE TITLE
 I would like to see Japanese railroads added.

### ISSUE THREAD

**Issue by mull1111** [jonafanho/Minecraft-Transit-Railway#581]
**Describe the solution you'd like**
I would like to see some Japanese railroads added.
For example, Shinkansen.
If it is not possible, I will delete this request.
Thank you.

**Comment by mull1111** [comment]
If I said that, it would mean other trains as well, but that would be a bad idea, so I am not sure about it, but I have decided to go ahead with it anyway.
I found a Japanese train on the author's youtube page, so I just sent it to him as a last resort.

**Comment by saleem0915** [comment]
I think it's possible, with using the resource pack creator

**Comment by 52PD** [comment]
> I think it's possible, with using the resource pack creator

Actually it is the only way to make JR trains in MTR Mod, since Jonathan no longer allow train requests unless supported him on Patreon.

**Comment by mull1111** [comment]
So we just need to support it with patron?
Also, I will delete the post.
Thank you very much.

**Comment by kettle-7** [comment]
> So we just need to support it with patron? Also, I will delete the post. Thank you very much.

no you can just make the train yourself

**Comment by mull1111** [comment]
understood.
I will do my best to make it.
Thank you very much.
I don't know if I can distribute the resource pack, but I will try to make it.
