### ISSUE TITLE
Better manual operation

### ISSUE THREAD

**Issue by mull1111** [jonafanho/Minecraft-Transit-Railway#583]
**Is your feature request related to a problem? Please describe.**
With the mass control key, you can only go to the location you specify.
Also, there is not much speed specification.

**Describe the solution you'd like**
With the mass control key, you can only go to the location you specify.
Also, there is not much speed specification.
However, I would like to be able to go anywhere immediately after the train appears, without having to specify a route.
Also, there should be a UI to handle switching rails.
Also, it would be good to increase the principle to 5 levels and the acceleration to about 5 levels.
Please.

**Comment by 52PD** [comment]
Think about other mods, please!

**Comment by mull1111** [comment]
We are very sorry.
I will delete your post.
Thank you very much.
