### ISSUE TITLE
I want cars. I also want all rails (planes, trains, cable cars) to be transparent.

### ISSUE THREAD

**Issue by mull1111** [jonafanho/Minecraft-Transit-Railway#584]
Cars must be reproduced on the current tracks, which are not realistic.
This will probably take as much effort as adding a plane, which can be slow.
I would also like to automate the cars and drive them manually.
Please.
(Perhaps we will need things like railroad tracks, so if we don't need those things, it is not a desire and we are fine with the status quo. But then, only certain rails, except when we have specific rails. It would be nice to have a setting to hide them. (This would apply to airplanes as well.)

**Comment by mull1111** [comment]
At the very least, I would like to be able to make the tracks transparent.

**Comment by 52PD** [comment]
Well, this one really will be refused.

Jonathan already said all requirements about new trains or other transportation tools will be rejected, unless you support him on Patreon.

Also, don’t send too many issue at same time. If Jonathan think you send too many spam content you may be banned from this GitHub repository.

Translate on Google: 
うーん、これはさすがに断られますね。

ジョナサンは、Patreonで彼をサポートしない限り、新しい電車やその他の輸送ツールに関するすべての要件が拒否されるとすでに述べています.

また、同時に多くの問題を送信しないでください。 Jonathan がスパム コンテンツを送信しすぎると判断した場合、この GitHub リポジトリから禁止される可能性があります。

**Comment by 52PD** [comment]
Well, this is definitely impossible.

Just think about why this mod is called Minecraft Transit **Railway**.

If you want tracks be hidden, please consider using resource pack.

Translated by Google:
うーん、これは絶対に無理です。

このモードが Minecraft Transit **Railway** と呼ばれる理由を考えてみてください。

トラックを非表示にしたい場合は、リソース パックの使用を検討してください。

**Comment by mull1111** [comment]
We are very sorry.
I will delete your post.
Thank you very much.

**Comment by mull1111** [comment]
Thank you very much.

**Comment by Ultimate-USA-YT** [comment]
As Said here, You must use a Resource Pack or modify the .jar to Hide the rails. And you can just bury the Rails underneath the road. And Jon has busses in the Works anyways

**Comment by mull1111** [comment]
Thanks for letting me know.
