### ISSUE TITLE
Problem of being dropped from a train by pressing the shift key briefly.

### ISSUE THREAD

**Issue by mull1111** [jonafanho/Minecraft-Transit-Railway#589]
**Expected Behaviour**
Crouching or standing up should be possible many times when the shift key is pressed briefly, and should not be shaken off unless you press it long enough.

**Actual Behaviour**
Even a short push may shake it off. (About 80% of the time.)

**Reproduction Steps**
1.Boarding the train
2.Press the Shift key briefly.

**Environment**

- Minecraft Version:1.19.3
- Installed Mods:See image
![スクリーンショット 2022-12-25 131545](https://user-images.githubusercontent.com/119109827/209456795-2a43c7ac-4e11-435a-892a-85cc0643ef67.png)

**Additional Information**
This bug occurs almost 100% of the time when the train is stopped.
The bug is also more likely to occur when crouching, trying to stand up, and pressing the shift key.
This bug has existed for a long time, even when playing with forge1.19.2 (mtr3.1.10 and the prerequisite mods only).
It was also present when I was playing with fabric and only MTR3.1.10.
(Incidentally, squatting is a very fun feature because it gives you a perspective as if you were sitting down. That said, I hope this glitch gets fixed.)

**Comment by jonafanho** [comment]
Please try using version 3.1.13, it should fix it.

**Comment by mull1111** [comment]
It has indeed been fixed, but I wanted to keep the ability to crouch in the car.
It gives the viewpoint as if you are sitting in a chair, and makes you feel more realistic.

**Comment by jonafanho** [comment]
Go to the Minecraft Transit Railway options menu and it's one of the settings to allow sitting when pressing shift.

**Comment by mull1111** [comment]
I was able to do it. Thank you very much.
