### ISSUE TITLE
Elevator crafting recipes?

### ISSUE THREAD

**Issue by someone649** [jonafanho/Minecraft-Transit-Railway#590]
Hello,

i was searching for elevator crafting recipes, but couldn't find them, neither in the wiki nor in the tutorial. Are elevator items currently only available in creator mode?

thanks for reply and a happy new year
t.

**Comment by jonafanho** [comment]
They are available in survival. The lift refresher can be crafted as such:
```
III
 P 
```
where `I` is an iron ingot and `P` is a piston. I recommend downloading a mod such as JEI or REI to help you search up recipes in-game.
