### ISSUE TITLE
Airplane Rail Speed

### ISSUE THREAD

**Issue by saleem0915** [jonafanho/Minecraft-Transit-Railway#592]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
No, it's not.
**Describe the solution you'd like**
Since there are now airplanes in the mod, there should be faster rail types, because 300 kilometers an hour isn't that realistic, not even for an A320, as they tend to cruise at about 800 kilometers.
**Additional Information**
That's all!

Thank you!

**Comment by Ultimate-USA-YT** [comment]
Wait, they can fly at 900 km/H if the Cruising Altitude is Higher than Buildlimit+64

**Comment by saleem0915** [comment]
Thank you for the information. In the meantime, I will close this as solved.
________________________________
