### ISSUE TITLE
Add station builders to MTR mod

### ISSUE THREAD

**Issue by chortle3** [jonafanho/Minecraft-Transit-Railway#594]
**INTRODUCTION**
Hello MTR Mod, I would like to add a suggestion to add station builders to Minecraft Transit Railway. 

**Is your feature request related to a problem? Please describe.**
I am very tired building a lot of stations, but I wanted to build it in a second! So, that's why you should add station builders to reduce time building train station for my lines!

**How will it work?**
This is similar to building in the Prefab mod. -> https://www.youtube.com/watch?v=h-4cxXSi20U 

**There are 5 types of blueprints:**
- Train Station blueprint
- Airport blueprint
- Boat Station blueprint
- Cable Car Station blueprint
- Depot blueprint

1. You just get/craft a **train station/airport/cable car station/boat station/depot** blueprint and place it whenever. Make sure you have space!

2A. If you choose a train station, you can choose to build it underground with stairs, the surface, or an elevated station at the top, with stairs.
3A: You can choose what theme for your station. Interchange, Terminus, normal station, and more!

2B: If you choose a train depot, you can choose to build it on the surface, or an elevated depot at the top, with stairs.
3B: You can choose what theme for your depot. Train depot, bus depot, and more!

4: There is a **preview** button that you can click. The yellow outline is the block you clicked on, and the green is the station/depot you want to build. Right click on any block to remove the preview.
5. Place it again if you already previewed, and click "Build Station". **It will go from 0% to 100% to build the station.**

I would be extremely appreciated if you add this feature to MTR Mod.

**Comment by quiteboring12121** [comment]
I simply **AGREE** with this suggestion. Station builders allow you to build stations in 1 click and not just hours. If you are tired and want a simple station, just use station builders! **Station builders deserves to be added to Minecraft Transit Railway!**

**Comment by cherbert** [comment]
Already exists. It's called Worldedit. Use it.

**Comment by chortle3** [comment]
> Already exists. It's called Worldedit schematics. Use it. The developer isn't going to waste his time on a huge time consuming feature like this. The whole point of Minecraft is to build and be creative.

Wow, where can I find an MTR station worldedit schematic?

**Comment by kettle-7** [comment]
> > Already exists. It's called Worldedit schematics. Use it. The developer isn't going to waste his time on a huge time consuming feature like this. The whole point of Minecraft is to build and be creative.
> 
> Wow, where can I find an MTR station worldedit schematic?

if you are lazy enough to not bother with making the stations, there's a worldedit schematic using the LU addon in the Tubeworld discord server, or you can just make a schematic yourself

**Comment by saleem0915** [comment]
> > > Already exists. It's called Worldedit schematics. Use it. The developer isn't going to waste his time on a huge time consuming feature like this. The whole point of Minecraft is to build and be creative.
> > 
> > 
> > Wow, where can I find an MTR station worldedit schematic?
> 
> if you are lazy enough to not bother with making the stations, there's a worldedit schematic using the LU addon in the Tubeworld discord server, or you can just make a schematic yourself

How do I make a schematic for WorldEdit?

**Comment by kettle-7** [comment]
Select an area, //copy then /schem save (name)

**Comment by saleem0915** [comment]
Thank you.
