### ISSUE TITLE
add q train

### ISSUE THREAD

**Issue by kester0312** [jonafanho/Minecraft-Transit-Railway#596]
**Is your feature request related to a problem? Please describe.**
I'm always want have a train can add in mtr mods and have the color simpling like r train also can use with k/c/m train.

**Describe the solution you'd like**
add a train at HK(q train)

**Additional Information**
[https://www.youtube.com/watch?v=yT6I7gZFtJI](url)
![112616331](https://user-images.githubusercontent.com/99643504/210140109-4553a7de-932a-43e1-b6ab-786de13cb2ce.jpg)
![041_4](https://user-images.githubusercontent.com/99643504/210140110-70c123f5-7041-49e4-a617-bbd1765d6d27.jpg)
![_2022090416000348199](https://user-images.githubusercontent.com/99643504/210140111-c8fe4803-b204-4dd0-b70d-4c0ff77ccb3b.png)
![file](https://user-images.githubusercontent.com/99643504/210140112-ee4e65c9-371d-467f-a7b8-85845f25c17a.jpg)
![original](https://user-images.githubusercontent.com/99643504/210140114-f4c5c857-8559-49ec-925a-b455b86844df.jpg)
![3fca1349c682452fdf70947d847cf236](https://user-images.githubusercontent.com/99643504/210140115-dc3bdf01-ce45-4680-9680-01a2b878d94f.jpeg)
![20221122164414contentPhoto1](https://user-images.githubusercontent.com/99643504/210140116-1d71a0fd-97b1-4094-9018-e466af555c4f.jpg)

**Comment by cherbert** [comment]
Stop asking for trains.

**Comment by jonafanho** [comment]
Duplicate of #371
