### ISSUE TITLE
添加MLR列车

### ISSUE THREAD

**Issue by 566666666666789** [jonafanho/Minecraft-Transit-Railway#60]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Example: I'm always frustrated when...
请添加MLR列车！
**Describe the solution you'd like**
添加MLR列车！
**Additional Information**
![GcWAw2Y](https://user-images.githubusercontent.com/80515666/121013485-74fda300-c7cb-11eb-92b4-e0a5363cfbbd.jpg)

**Comment by 16-squared** [comment]
It's already on the todo list

**Comment by Eric28020** [comment]
You know you shouldn't make an issue about more trains. AND it's already on the todo list.
