### ISSUE TITLE
New High Speed Train Models

### ISSUE THREAD

**Issue by CastorF1ber** [jonafanho/Minecraft-Transit-Railway#603]
Now there are few high speed train models in the mod. I think only BR Class 802. IRL its max speed is about 200 km/h but in the game it can travel at the speed of 300 km/h. I suggest to add some trains which go 300 irl, like: ICE-3 from Germany, Frecciarossa 1000 (ETR-400 or ETR-1000) from Italy, TGV from France or even Japanese Shinkansen.

**Comment by saleem0915** [comment]
Um... Are you subscribed to @jonafanho's Patreon? Because if you aren't, then I don't think that he'd accept it. But I like the idea, especially the Shinkansed.

**Comment by CastorF1ber** [comment]
No, I'm not subscribed. I started playing with this mod yesterday.

**Comment by saleem0915** [comment]
Oh, okay.
