### ISSUE TITLE
使用滑鼠點擊「添加車站出口」時 不能顯示出口編號輸入框

### ISSUE THREAD

**Issue by Plutonium-PENG** [jonafanho/Minecraft-Transit-Railway#605]
**Expected Behaviour**
使用滑鼠點擊「添加車站出口」時 正常情況下應該顯示出口編號輸入框

**Actual Behaviour**
但是現在我無法按出此輸入框
不過 使用 Tab 按鍵於元件之間移動 移動至「添加車站出口」按下 Enter  可使之正常顯示

**Crash Report**
此問題不會造成Crash

**Environment**

- Minecraft Version: 1.19.3 (server & client)
- Installed Mods: MTR-fabric-1.19.3-3.1.13
- OS: Windows 11 Pro  22621.963

**Additional Information**
自我將Minecraft(server & client)由1.19更新至1.19.3 同時將本Mod由MTR-fabric-1.19.2-3.1.7更新至MTR-fabric-1.19.3-3.1.12后 就出現此問題
嘗試更新至 MTR-fabric-1.19.3-3.1.13 依然無法解決此問題
期間OS沒有變化

當我游戲時 已將輸入法設為 英語-美國 美式鍵盤
除Minecraft Server 同游戲本身之外 沒有啓動其他程式
不知是否為本Mod之Bug？煩請調查~多謝！

**Comment by jonafanho** [comment]
Fixed in 3.2.0
