### ISSUE TITLE
Airport Utilities

### ISSUE THREAD

**Issue by saleem0915** [jonafanho/Minecraft-Transit-Railway#606]
**Is your feature request related to a problem? Please describe.**
Since there are planes now in MTR, there should be airport utilities available for the mod.

**Describe the solution you'd like**
There should be options to put airport utilities such as: Luggage carts, luggage, and security checkpoint items (this one isn't necessary because it may take a long time).
**Additional Information**
For the luggage carts and luggage, there should be an option to customize their textures.

**Comment by XHG78999** [comment]
The main idea of this mod is railway. Airlines are extend contents, and author said that except if there is a huge bug that can cause crash, he won't update this facility anymore.
You can make a mod about airport utilities by yourself.

**Comment by saleem0915** [comment]
Okay, thank you@
