### ISSUE TITLE
3.13.3的MTR無法載入自定義音頻

### ISSUE THREAD

**Issue by xiaobaimao233** [jonafanho/Minecraft-Transit-Railway#607]
**Expected Behaviour**
使用最新版MTR並刷新資源包後，無法播放之前加入的自定義音頻

**Actual Behaviour**
在之前是可以播放的
但是在刷新資源包後就播放不了了

**Crash Report**
不造成崩潰報告

**Environment**

- Minecraft Version: 1.17.1
- Installed Mods: MTR-fabric-1.17.3-3.1.13

**Additional Information**
我不確定這是否是因為MTR模組本身的Bug，但希望作者大大可以看一下怎麼回事，謝謝ww
tip: 我大概排除了是附加模組(addon)造成的問題了

**Comment by jonafanho** [comment]
這應該不是本模組的bug，請看看資源包有沒有問題。
