### ISSUE TITLE
Increase the number of grids that one train can carry. 增加一辆列车可以运送的物品栏格数。

### ISSUE THREAD

**Issue by hyhcrh** [jonafanho/Minecraft-Transit-Railway#615]
**Is your feature request related to a problem? Please describe.**
I think it's not a problem, but now the freight system is almost useless.
我认为它并不算一个问题，但是现在的货运系统确实没什么用。

**Describe the solution you'd like**
Now 1 train can carry 1 inventory grid of items.
It will be much better if the number of grids can be 27 or more.
It really made me crazy when I saw a train could only carry **_1_** lava bucket. 
现在一辆列车只能运送一格物品栏的物品。
如果格子的数量可以变为27格或更多，那将会变得更好。
当我看见一辆列车只能运送 **_1_** 个岩浆桶的时候，这让我很抓狂。

**Additional Information**
(It can also be an option that adding a new freight train.)
(新增一辆货运列车也是一个选择。)

**Comment by jonafanho** [comment]
Each train can hold one stack per car, so simply make the train longer and have more carriages.

**Comment by hyhcrh** [comment]
> Each train can hold one stack per car, so simply make the train longer and have more carriages.

Thanks for your answer. It works.
