### ISSUE TITLE
Trains don't spawn in beta-7

### ISSUE THREAD

**Issue by linuxkettle** [jonafanho/Minecraft-Transit-Railway#62]
**Expected Behaviour**
I would expect trains to arrive when the PIDS says they will.

**Actual Behaviour**
I'm not sure how exactly the depots work, but the PIDS said a train was to arrive in 5 seconds and 5 seconds later, the timer disappeared, so the PIDS looked like this:
```
Kennedy town       (no time here)
Kennedy town       50 sec
Kennedy town       1 min
```
No train arrived. There are none on the entire network.

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Create a world in beta-6 with 2 stations. Link them with a route and trains every 50 seconds.
2. Remove beta-6 from the mods folder, replacing it with beta-7
3. Join the world, create a depot with rail links to all of the platforms (not that that part matters but I did it)
4. No trains exist anywhere, despite what the PIDS says.

**Crash Report**
none

**Screenshots**
![Screenshot from 2021-06-11 16-43-57](https://user-images.githubusercontent.com/64388266/121632009-4b4ac180-cad4-11eb-90c8-d9572c3e4940.png)

**Environment**

- Minecraft Version: 1.16.5
- Installed Mods: Fabric API (fabric-api-0.34.6+1.16), MTR from beta-7 branch as of yesterday (10 June).

**Additional Information**
Nothing to see here.

**Comment by jonafanho** [comment]
Hello, thank you for reporting this. The depot update is a snapshot, so bugs are expected. Also, on Discord I have mentioned that the PIDS do not work properly yet at this point.

**Comment by linuxkettle** [comment]
Okay, thanks. I have rolled back to beta-6 for now.

**Comment by 16-squared** [comment]
have you tried refreshing all lines (if refresh feature is in beta-7)?

**Comment by linuxkettle** [comment]
Yes, but the lines don't have the little clock icons to time them, you do that with the depot GUI, which I don't really understand, but the PIDS seems to be going off the beta-6 data.
