### ISSUE TITLE
Add non-service time

### ISSUE THREAD

**Issue by CokeStudios** [jonafanho/Minecraft-Transit-Railway#624]
**Is your feature request related to a problem? Please describe.**
I can't make a train running on a route forever but stop running at night.

**Describe the solution you'd like**
We can set 'non-service time' for each depot.
During this time period, when a train finished its route, it went back to the depot.
During this time period, trains could't depart from the depot.
After this time period, trains could depart from the depot.

**Comment by jonafanho** [comment]
Can you achieve the same result using real-time scheduling in the depot?

**Comment by CokeStudios** [comment]
It seems I can't. The train will go back to depot when it finished its route, but I want the train to run forever, only go back to depot at night.
