### ISSUE TITLE
The wiki has been out of date for a long time, would you like to consider updating it?

### ISSUE THREAD

**Issue by WNCX** [jonafanho/Minecraft-Transit-Railway#625]
I wanna make a custom resourcepack for train but I can't find how to add the sound to my custom train. The wiki on github may need to be updated

**Comment by jonafanho** [comment]
Thank you for your suggestion! A new wiki is being worked on currently, we will let the community know when it's ready.

**Comment by WNCX** [comment]
> Thank you for your suggestion! A new wiki is being worked on currently, we will let the community know when it's ready.

Thank you so much and I'll respect it!
