### ISSUE TITLE
Train stop on the track

### ISSUE THREAD

**Issue by RomainC2421** [jonafanho/Minecraft-Transit-Railway#628]
**Actual Behaviour**
I have a line with 4 underground train, but between two stations the train stop and the 3 other will stop just behind it, it does it every times.
it look like the train just go back in the line, in the wrong way.

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Just launch the train

**Crash Report**
Attach a crash report to the issue.

**Environment**

- Minecraft Version: 1.19.2

**Comment by Ultimate-USA-YT** [comment]
I think the Signal Block Ahead is Occupied

**Comment by RomainC2421** [comment]
> I think the Signal Block Ahead is Occupied

Do you know how i can resolve that ? Sorry i'm new to this

**Comment by RomainC2421** [comment]
i think it's maybe the chunk load, what do you think about ?

**Comment by kettle-7** [comment]
No, the issue is that you have trains like this
```
-->  - - >  <--  <--
```
I suggest using two one-way tracks so that the trains aren't going towards each other, as they stop to wait for the track in front to empty.

**Comment by kettle-7** [comment]
It may also be a good idea to install signaling (there's a YouTube tutorial on this, it's a bit complicated to explain here) at any signal track sections, and stations where trains turn back, as well as decreasing how often the trains are so that they actually have time to get out of the station before the next one comes.

**Comment by RomainC2421** [comment]
> It may also be a good idea to install signaling (there's a YouTube tutorial on this, it's a bit complicated to explain here) at any signal track sections, and stations where trains turn back, as well as decreasing how often the trains are so that they actually have time to get out of the station before the next one comes.

i'm going to do this ! Thank you :D
