### ISSUE TITLE
[bug/enhancment, idk] peformance issues with MTR and addons

### ISSUE THREAD

**Issue by Globalfirestorm10** [jonafanho/Minecraft-Transit-Railway#629]
**Expected Behaviour**
When I load up a world with MTR (the world has no assets related to the mod in it), I shouldn't see any major fps differences

**Actual Behaviour**
Instead, I notice about a 35-60 fps drop, along with lag spikes from chunk updates

**Reproduction Steps**
Steps to reproduce the behaviour:
disclaimer: I doubt these steps will work, as I have no idea how to accurately reproduce this bug. However, I will be providing my mod list, shader used, and resource packs used

1. Simply launch mc with my mods (with the exception of Ultimate immersion, modernarch, physics mod pro, and legendary knight sci-fi mod, as these don't necessarily affect anything related to the mod). No need to use my resource packs either, just load up a world with the mods and MTR content I have (it must not have anything related to the mod in it).Also user seus hrr 2.1

2. see error

**Crash Report**
N/A

**Screenshots**
with MTR and the addons:
![2023-02-24_22 01 19](https://user-images.githubusercontent.com/102924027/221332843-0ff2a101-35c6-472a-b7f7-b3bc52a22499.png)
![2023-02-24_22 01 30](https://user-images.githubusercontent.com/102924027/221332844-d8377673-0ad2-467c-a0a7-d4dee7fd4a8d.png)
without: N/A, but I get around 110 fps

**Environment**

- Minecraft Version: forge 1.19.2 version 43.2.0
- Installed Mods:
![image](https://user-images.githubusercontent.com/102924027/221332490-2ac057eb-7402-4f7e-9a5d-3f704c702cb4.png)

**Additional Information**
Anything else you want to add?
I heavily doubt that this issue is with my other mods, as most of them are performance/QOL/bugfix mods, and the ones that aren't don't affect fps too much. MC used to be buttery smooth without MTR, but with MTR, the london railroad content pack, and a sign content pack, thats down to an average 56/14fps. I use seus hrr 2.1 shaders with custom emissive files, and two x256 resource packs for a mod (they assist in the loading of custom models, as they can't load without them, so I doubt that this would affect much). I'm also on a flat world with one man made structure (an airport, but it isn't even that big or resource intensive.

**Comment by kettle-7** [comment]
try remove the mtr addons, so jcm and lu addon, but keep mtr, and see what happens

**Comment by Globalfirestorm10** [comment]
Yeah ill try that

**Comment by Globalfirestorm10** [comment]
255 was my frame cap, and the 60fps thats shown in green in one of the screenshots is actually 60/21 fps, which may as well just mean that im getting <30fps

**Comment by Globalfirestorm10** [comment]
> Yeah ill try that

as stated before, I have the london underground addon, alongside the MTR sign addon.

**Comment by Globalfirestorm10** [comment]
@kettle-7 still getting horrible performance (about 52/12fps, which is essentially just 16fps)

**Comment by Globalfirestorm10** [comment]
found the problem, turns out a mod called modernarch (somehow), combined with MTR,=less performance
heres the link to the mod: https://www.designio.graphics/modernarch-mod#:~:text=ModernArch%20Mod%20was%20developed%20to,with%20the%20ModernArch%20Resource%20Pack.

heres the link to their discord if needed as well:https://discord.gg/DkNRnJ2M9U

**Comment by Globalfirestorm10** [comment]
> try remove the mtr addons, so jcm and lu addon, but keep mtr, and see what happens

hey, mind taking a look at my other responses? Im at a loss as of how this mod conflicts with mtr

**Comment by kettle-7** [comment]
What I'd say is happening is that the game is using nearly all of its ram, which is causing it to lag, likely as a result of having the extremely detailed modernarch textures (which use a lot of memory on their own) and the mtr trains which also have, although not quite as detailed, still pretty detailed textures. My suggestion would be to try allocating more memory to the game (with a modset like that you may need 6-8 GB) and see if it's any better

**Comment by kettle-7** [comment]
Wait no having scrolled up to the screenshot I see you already have 10GB allocated, maybe try a bit more ?

**Comment by Globalfirestorm10** [comment]
> Wait no having scrolled up to the screenshot I see you already have 10GB allocated, maybe try a bit more ?

Well, figured out the issue. I spoke to the developer of modernarch (the mod that was causing this) and he  got the same issue as me. He replied to me saying that it because he uses some "tricks" (idk what he'a referring to here) to load his custom json models, which messes with the loading of all the mtr transport vehicles. He said that he's rewriting the mod to have only obj models to avoid these incompatibilities in the future, so yeah

**Comment by Globalfirestorm10** [comment]
This issue has been completely fixed, thank you for your assistance
