### ISSUE TITLE
Placing a Station Name item immediately hard crashes with no discernible Minecraft error.

### ISSUE THREAD

**Issue by noclueumbreon** [jonafanho/Minecraft-Transit-Railway#63]
**Expected Behaviour**
Placing the station sign down either throws an error or alternatively, does not let you place it.

**Actual Behaviour**
Hard crash to desktop. No indication of what triggered it. Java crash log instead of Minecraft. 

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Install MTR.
2. Place a Station Name.

**Crash Report**
For personal reasons, I'm going to see whether I can remove any identifiable information from the crash log.

**Environment**

- Minecraft Version: 1.16.5
- Installed Mods: Almost too many to list. Around 270, but I can't see why most of them would interfere. I'll post a list of installed mods if needed, but the big ones are: 
MTR
Optifine/Optifabric
Borderless Mining

**Additional Information**
I have no idea why this happens. I'm not too well versed in modding, but I'd expect a crash to desktop with minecraft log, not a sudden crash to  desktop with a Java log- no clue what would cause it, past the apparent thread being labelled as a render thread.

I apologize if I am late to respond- I don't check my email or Github often.

**Comment by 566666666666789** [comment]
大哥这个已经有解决办法了！

**Comment by 566666666666789** [comment]
https://github.com/jonafanho/Minecraft-Transit-Railway/issues/24

**Comment by noclueumbreon** [comment]
I'm testing the fix right now. Sidenote- it also happened when attempting to name my station.

**Comment by 566666666666789** [comment]
What an automatic repair program, this is an MTR font problem!

**Comment by Eric28020** [comment]
Open a new world, open a dashboard, click options, and disable the MTR Font.

**Comment by noclueumbreon** [comment]
Testing right now.

**Comment by noclueumbreon** [comment]
Appears to be an issue with the fonts. Sorry for the trouble!

**Comment by linuxkettle** [comment]
Out of curiosity, and slightly related, what platform is this? (Windows / Mac OS / in my case Other)

**Comment by linuxkettle** [comment]
Wayland seems to have no problems, I haven't tried X11, and don't have access to Windows or Mac OS.

**Comment by noclueumbreon** [comment]
Windows 10. I've got an intensely screwed up computer, but it seems odd that it's a problem with the OS rather than with any given installation- and the problem is apparently with Java rendering it- so I'm not sure why it's happening. Maybe it's trying to access a given font that's installed by default on Linux and getting garbage data that screws it up until it crashes?

**Comment by Kenny-Hui** [comment]
Obviously it shouldn't be that big of a deal not being able to use MTR font, but I would really want to know the real source of crash:

From what I've known, this issue persist on Intel HD Graphics. Is your machine using Intel HD Graphics?

If it is, then it seems to have something to do with either Intel's display driver or Minecraft not being able to render it.

This mod uses a ttf font which is supported since 1.13(?). However it doesn't seems to like Intel's driver very much...

(I am able to reproduce the same crash by using a resource pack with a ttf font in it in vanilla Minecraft on Intel HD 630)

**Comment by linuxkettle** [comment]
It might have to do with the font backend that minecraft uses.

**Comment by Kenny-Hui** [comment]
Dunno, but my game no longer crashes on 1.17 release, so they might've fixed it.

We'll see how this goes when the mod is ported to 1.17 later on

**Comment by linuxkettle** [comment]
Maybe it has to do with the Windows API talking to OpenGL, but it's nothing higher level than OpenGL because all the code above that is the same on all platforms.

**Comment by linuxkettle** [comment]
Let me try with a Windows VM and VirtualBox graphics drivers, that will show me if it's a graphics card problem. Otherwise it's either OS or something else if the same issue occurs on macs (intel or m1)

**Comment by noclueumbreon** [comment]
> Obviously it shouldn't be that big of a deal not being able to use MTR font, but I would really want to know the real source of crash:
> 
> From what I've known, this issue persist on Intel HD Graphics. Is your machine using Intel HD Graphics?
> 
> If it is, then it seems to have something to do with either Intel's display driver or Minecraft not being able to render it.
> 
> This mod uses a ttf font which is supported since 1.13(?). However it doesn't seems to like Intel's driver very much...
> 
> (I am able to reproduce the same crash by using a resource pack with a ttf font in it in vanilla Minecraft on Intel HD 630)

I do use IHD graphics, yeah.

**Comment by linuxkettle** [comment]
Hmmmmm. I'll see if the same issue occurs on my friend's nVidia.
