### ISSUE TITLE
請求縮短跑道長度

### ISSUE THREAD

**Issue by pokOSlanx** [jonafanho/Minecraft-Transit-Railway#630]
**Is your feature request related to a problem? Please describe.**
我們的Minecraft服務器機場位置不大，要建機場，結果跑道需要1000格，這對於Minecraft來說太長了，很多服務器都騰不出那麼多空間。

**Describe the solution you'd like**
縮短所需長度到100左右

**Additional Information**
無 
@jonafanho

**Comment by jonafanho** [comment]
I don't really understand what you are asking from me, do you mind rephrasing it? Runway rails don't have to be very long, although not realistic, they can just be one block long.
