### ISSUE TITLE
[1.19.3] Unable to use with a monitor that is 1680x1050- Unable to fit: mtr:entity/light_rail_3_orange - size: 1472x1472 - Maybe try a lower resolution resourcepack?

### ISSUE THREAD

**Issue by ProsperCraft** [jonafanho/Minecraft-Transit-Railway#633]
**Expected Behaviour**
Load

**Actual Behaviour**
Crashed

**Reproduction Steps**
Steps to reproduce the behaviour:

1.Start the mod on a monitor that is less then 1472x1472

**Crash Report**
[Attach a crash report to the issue.](https://gist.github.com/ProsperCraft/080d89b49b38b6571c33a9dd60b361ad)

**Environment**

- Minecraft Version: 1.19.3
- Installed Mods: TownCraft For 1.19.3 it is in the crash report.

**Comment by kettle-7** [comment]
As the title of your issue suggests it seems it's an issue with resource
packs. I can confirm the mod works fine at 1024x768.

**Comment by ProsperCraft** [comment]
We don't have any resource packs, only programmer art.
