### ISSUE TITLE
Elevator 'spawn block' in menu does not appear (2x4, 3x3, etc.)

### ISSUE THREAD

**Issue by Z01NK3R20** [jonafanho/Minecraft-Transit-Railway#635]
**Expected Behaviour**
Elevator spawn blocks in the creative menu

**Actual Behaviour**
In the Creative menu, it is not evident that the '2x4' spawn blocks are there. There is only the refresh elevator block
**Reproduction Steps**
_Steps to reproduce the behaviour:_

1. Open Creative menu (or survival if craftable. Not sure if it is or not.) 
2. Go to the _Escalators and Lifts/Elevators_ tab on the second page. Attempt to find the spawn block. Pray that its there for you

**Crash Report**
Nil. No crashes has happened.

**Screenshots**
![2023-03-01_20 26 35](https://user-images.githubusercontent.com/126664597/222118352-f800733c-ce3d-4198-9002-02d765313899.png)

**Environment**
Minecraft Fabric 1.19.3
Curseforge application launcher

- Minecraft Version: 1.19.3
- Installed Mods:
As of typing of this report, all listed and installed mods are: Architectury API (Fabric/Forge), AzureLib (I have checked if it has done anything and nothing has changed), Cloth Config API (Fabric/Forge), ESSENTIAL Mod, Fabric API, Happiness (is a) Warm Gun [Gun mod], Iris Shaders, Paladin's Furniture, Plasmo Voice, Sodium, and UTfM. (Ultimate Transport) 

**Additional Information**
Additional notes: 
I have tried to install the Beta versions, both of them (1.19.3). 
I have tried having the Ultimate Transport mod installed on its own. 
I am running the Curseforge app launcher. 

My main focus is the elevators. That is purely what I have installed the mod for, and everything included looks stunning for Minecraft especially. Thanks in advance for replying to this post.

**Comment by kettle-7** [comment]
These were intentionally removed a while ago, there's a few newer tutorials on how to use the new elevator system

**Comment by jonafanho** [comment]
https://youtu.be/vhTKectuIbg
