### ISSUE TITLE
Minecraft Crashing Error due to the Minidumps not Enabled

### ISSUE THREAD

**Issue by SethPederito2023** [jonafanho/Minecraft-Transit-Railway#638]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff948ff3490, pid=116, tid=9584
#
# JRE version: OpenJDK Runtime Environment Microsoft-28056 (17.0.1+12) (build 17.0.1+12-LTS)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-28056 (17.0.1+12-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [ig9icd64.dll+0x1b3490]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows

**Comment by SethPederito2023** [comment]
Please write me the Comments how to Enable minidumps and GL!

**Comment by kettle-7** [comment]
The game does not crash because of disabled minidumps, the issues like this are usually caused by a broken java install, so please uninstall java and then re-download it, making sure to get java 17.

**Comment by jonafanho** [comment]
Please try reinstalling Java as kettle mentioned.
