### ISSUE TITLE
The Javascript is Not Working! due to the Website Error!

### ISSUE THREAD

**Issue by SethPederito2023** [jonafanho/Minecraft-Transit-Railway#639]
![Web capture_5-3-2023_94114_](https://user-images.githubusercontent.com/127005043/222973747-41e1b69e-1f21-4034-aafe-1fff9e80e80b.jpeg)

**Comment by Ultimate-USA-YT** [comment]
This looks like a Normal Screen. Make shure you have your World open and Refresh the Page

**Comment by kettle-7** [comment]
try push <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd> and click the Inspect tab

**Comment by SethPederito2023** [comment]
> try push Ctrl+Shift+I and click the Inspect tab

But the Javascript is Not Enabled!

**Comment by kettle-7** [comment]
Do it anyway
And web browser that doesn't support javascript is at least 25 years old or a very bad browser

**Comment by jonafanho** [comment]
Has this been resolved? If not, please reopen this issue.
