### ISSUE TITLE
Mini train cars have only one bogie when not paired with another car

### ISSUE THREAD

**Issue by turtlegarden** [jonafanho/Minecraft-Transit-Railway#643]
当在侧线上创建一列只有一节 "迷你 "火车车厢的火车时，它只有一个转向架，这看起来相当奇怪，因为另一边是浮动的。

![The "Mini" car with only one bogie and floating on one side/](https://user-images.githubusercontent.com/52264162/224489483-69d89fa5-128f-4cc0-997e-8fdc47f587eb.png)

然而，一旦火车车厢成对，这个问题可以通过使用铰接式转向架来解决。这个问题也不会发生在非 "迷你 "尺寸的汽车上。

![Paired "Mini" cars using Jacobs bogies and resolving the issue](https://user-images.githubusercontent.com/52264162/224489614-ad1fe0ed-78a8-442a-9aac-ae04d61e51e8.png)

一个可能的解决方案是，在不包含转向架的汽车一侧设置一个单轴（而不是整个转向架）。

***

When creating a train with only one "mini" train car on the siding, it has only one bogie, which looks rather odd since the other side is floating. However, once the train cars are paired, this problem can be solved by using articulated bogies. This problem also does not occur if the car is not a Mini car. One possible solution is to have a single axle on the side of the car that does not contain the bogie (instead of the entire bogie).

***

När man skapar ett tåg med bara en "mini"-vagn på sidospåret har det bara en boggi, vilket ser ganska konstigt ut eftersom den andra sidan är flytande. När tågvagnarna väl är parade kan detta problem dock lösas genom att använda ledade boggier. Detta problem uppstår inte heller om vagnen inte är en minivagn. En möjlig lösning är att ha en enda axel på den sida av bilen som inte innehåller boggin (i stället för hela boggin).

**Comment by kettle-7** [comment]
Personally I would have considered this a feature. It may not be realistic but neither is single car mini trains.

**Comment by jonafanho** [comment]
This should be fixed in the latest update.
