### ISSUE TITLE
resource pack creator is unable to be add sound

### ISSUE THREAD

**Issue by kester0312** [jonafanho/Minecraft-Transit-Railway#653]
*Expected Behaviour**
resource pack creator is enable to be add sound

**Actual Behaviour**
resource pack creator is unable to be add sound

**Reproduction Steps**
N/A

**Crash Report**
N/A

**Screenshots**
N/

**Environment**

- Minecraft Version:
1.19.3
- Installed Mods:
3.2.0

**Additional Information**
N/A

**Comment by jonafanho** [comment]
The Resource Pack Creator item is not designed for adding in custom sounds. Please refer to the Minecraft Wiki for detailed instructions.

**Comment by kester0312** [comment]
Thx
