### ISSUE TITLE
Serious issue when traveling long distances on a server.

### ISSUE THREAD

**Issue by bauerbach** [jonafanho/Minecraft-Transit-Railway#655]
**Expected Behaviour**
Trains running through long distances should run smoothly and load all chunks properly.

**Actual Behaviour**
When I have a train running using a Diamond rail on a server, sometimes the chunks don't load properlly and I get stuvk. Even disconnecting and rejoining doesn't fix the issue, and I have to delete all of my playerdata.

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Create a two or more stations at least 1000 blocks apart.
2. Use Diamond rails in the route.
3. Attempt to ride the train. There is a chance that the chunks don't render and you get permanently stuck.

**Crash Report**
N/A

**Screenshots**
N/A

**Environment**

- Minecraft Version: 1.16.5
- Installed Mods: Immersive Portals, ImmersiveEngineering, TConstruct, and many others.

**Additional Information**
I don't know if it's a compatibility issue or maybe not enough memory from all of those mods (more than 100).

**Comment by jonafanho** [comment]
Unfortunately, this is a Minecraft chunkloading problem. Try setting `allow-flight` to true or install other mods like Carpet to fix rubberbanding.

**Comment by bauerbach** [comment]
allow-flight is already on and Carpet is Fabric-only (I use Forge).
