### ISSUE TITLE
Doors Not Working

### ISSUE THREAD

**Issue by DDX5** [jonafanho/Minecraft-Transit-Railway#657]
**Expected Behaviour**
When the lift reaches the floor the doors open and close when you either select a floor or a call is placed

**Actual Behaviour**
The doors do nothing.

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Create the lift as expected
2. Add doors, both odd and even styles have the problem.
3. Issue encountered.

**Crash Report**
Attach a crash report to the issue.

**Screenshots**

**Environment**

- Minecraft Version: 1.19.2
- Forge Version: 1.19.2 42.3.4
- Installed Mods: listed below

1.  create
2. immersive engineering
3. applied energistics 2
4. mcw bridges
5. mcw doors
6. mcw furniture
7. mcw lights
8. mcw roof
9. mcw trapdoors
10. mcw windows
11. Mekanism
12. pneumaticcraft repressurized
13. rubidium
14. thermal series
15. simple light
16. world edit.
17. mtr

**Additional Information**
Mod Version: 1.19.2-3.2.1

**Comment by jonafanho** [comment]
What is your setup like? Can you please attach some screenshots or videos? That would help. Thanks.

**Comment by CokeStudios** [comment]
Update the mod to 3.2.1-hotfix-1, then the doors will work.

**Comment by DDX5** [comment]
Excellent the issue has been resolved
