### ISSUE TITLE
Show me your work of the Thank you MLR

### ISSUE THREAD

**Issue by SethPederito2023** [jonafanho/Minecraft-Transit-Railway#660]
![2022-11-16_22](https://user-images.githubusercontent.com/127005043/230788621-b0b3c81d-21a3-416b-a31f-dbdec63b3d2c.jpg)

**Comment by SethPederito2023** [comment]
Make it Perfect!

**Comment by Ultimate-USA-YT** [comment]
Do you have an Issue with the Mod?

**Comment by SethPederito2023** [comment]
> Do you have an Issue with the Mod?

yes

**Comment by Ultimate-USA-YT** [comment]
> > Do you have an Issue with the Mod?
> 
> yes

What is It?
