### ISSUE TITLE
Elevator confusion

### ISSUE THREAD

**Issue by PenguinMan-1219** [jonafanho/Minecraft-Transit-Railway#662]
**Expected Behaviour**
Place the elevator, use an item to move it.

**Actual Behaviour**
Places elevator in weird position, seems impossible to change.

**Reproduction Steps**

1. Place an elevator on an Elevator Floor Track

**Crash Report**
N/A

**Screenshots/Video**

https://user-images.githubusercontent.com/130403950/230989388-5777c5cb-7f35-4b85-b294-b8fac60db5ff.mov

**Environment**
MacOS, M1
- Minecraft Version: 1.18.2 Fabric

**Comment by PenguinMan-1219** [comment]
sorry if this is kinda stupid, haven't used the mod in a while

**Comment by jonafanho** [comment]
Right click the elevator tracks again to bring up the configuration menu.

Please watch the [latest tutorial](https://www.youtube.com/watch?v=vhTKectuIbg) about elevators.
