### ISSUE TITLE
Faster bridging and tunneling

### ISSUE THREAD

**Issue by elmwycke** [jonafanho/Minecraft-Transit-Railway#669]
**Is your feature request related to a problem? Please describe.**
When using Creative mode, bridging and tunnelling is excruciatingly slow over large distances.

**Describe the solution you'd like**
A setting inside "Options" that allows one to adjust the speed at which tunnelling and bridging happens.

**Comment by Maxwenyan** [comment]
First,this speed looks like restricted by CPU speed?My CPU is i5,so this speed very fast,then I was in a server,the building speed is slow.so I think this speed Equipment related.

**Comment by elmwycke** [comment]
Looking into it further, it does indeed seem that bridging is faster at some points than others, indicating that this is probably an issue with my computer's performance - I'm running an Intel Core i7 8th gen, but with no dedicated GPU. I might be better off using WorldEdit in the future for this then.

**Comment by Maxwenyan** [comment]
but some WorldEdit script need 1 block width lines,so I think this mod need a 1 block width bridge building?
