### ISSUE TITLE
Ticket Processors letting players with 0 $ through, leading to a balance of -1

### ISSUE THREAD

**Issue by Alidonis** [jonafanho/Minecraft-Transit-Railway#676]
**Expected Behaviour**
Ticket processors refuse to let a player with 0$ or less through.

**Actual Behaviour**
Ticket processors only refuse players with -1$ or less.

**Reproduction Steps**
Steps to reproduce the behaviour:
 - place a ticket processor in a train station.
 - Click the block with 0$ on your account
 - The processor will let you through.

1.

**Crash Report**
Not Applicable. This is not a crash.

**Environment**

- Minecraft Version: 1.19.4, Fabric Modloader
- Installed Mods: MTR, MTR-NTE

**Additional Information**
Could be simply fixed by remplacing the condition ">=" with ">" on line 88 of TicketSystem.java
https://github.com/jonafanho/Minecraft-Transit-Railway/blob/87c987f660dac35832bb9373c7d7da8bd31e2abc/common/src/main/java/mtr/data/TicketSystem.java#LL88C1-L88C1

**Comment by jonafanho** [comment]
This is intentional. This is the behaviour in real life as well.
