### ISSUE TITLE
Crash: CTD Minecraft 1.19.2; Quilt 0.18.10

### ISSUE THREAD

**Issue by LunarPidgeon** [jonafanho/Minecraft-Transit-Railway#681]
**Expected Behaviour**
Game launches as normal

**Actual Behaviour**
Game crashes to desktop

**Crash Log**
Unable to be loaded directly, heres a link:
[https://gist.github.com/LunarPidgeon/5d44c10a32a252c90f1f381bff665d60](https://gist.github.com/LunarPidgeon/5d44c10a32a252c90f1f381bff665d60) 

**Environment**

Minecraft v1.19.2
Quilt v0.18.10

Mod list:
  [✔] 3dskinlayers-fabric-1.5.2-mc1.19.1
  [✔] accurate-maps-1.0-BETA 1.19
  [✔] AdaptiveTooltips-1.0.1-fabric-1.19.2
  [✔] alternate-current-mc1.19-1.5.0
  [✔] amecs-1.3.8 mc.1.19-rc2
  [✔] appleskin-fabric-mc1.19-2.4.1
  [✔] aquatictorches-1.19-fabric-1.0.0
  [✔] arcanus-1.30
  [✔] architectury-6.5.82-fabric
  [✔] audio_engine_tweaks-1.2.2-1.19.3 build 4
  [✔] auditory-0.0.4-1.19.x
  [✘] better-enchanted-books-1.19.4-1.4.2.jar (disabled)
  [✔] bettercombat-fabric-1.7.1 1.19
  [✔] BetterF3-4.0.0-Fabric-1.19.2
  [✔] betterleads-1.0.2 1.19.2
  [✔] blahaj-quilt-1.19-0.2.1
  [✔] blur-2.6.0
  [✔] borderless-mining-1.1.5 1.19
  [✔] c2me-fabric-mc1.19.2-0.2.0 alpha.9.9
  [✔] CameraOverhaul-1.4.0-fabric-universal
  [✔] carryon-fabric-1.19.2-2.0.5.11
  [✔] charm_fixer-1.0.0
  [✔] charm-fabric-1.19.2-4.4.4
  [✔] charmonium-fabric-1.19.2-4.2.1
  [✔] chatcalc-3.0.14
  [✘] cinderscapes-3.0.3.jar (disabled)
  [✔] clickthrough-1.19.1-fabric0.58.5-0.4
  [✔] collective-1.19.2-6.53
  [✔] continuity-2.0.2 1.19
  [✔] copperhopper-0.0.12 1.19.2
  [✔] crops_love_rain-1.3.0
  [✔] ctov-3.2.1
  [✔] custom-lan-1.19.1-v2.2.0
  [✔] customizableelytra-fabric-1.6.4-1.19
  [✔] darkness-fabric-mc119-2.0.101
  [✔] Debugify-2.8.0
  [✔] DiagonalFences-v4.2.4-1.19.2-Fabric
  [✔] do-a-barrel-roll-2.6.2 1.19.2-fabric
  [✔] DungeonsArise-1.19.2-2.1.54-fabric
  [✔] dynamic-fps-2.2.0
  [✔] dynamiccrosshair-5.4 1.19.2-fabric
  [✔] dynamiccrosshair-compat-3.3.1 1.19.2
  [✔] easiervillagertrading-1.19.1-fabric0.58.5-1.5.4
  [✔] elytraslot-fabric-6.1.1 1.19.2
  [✔] emi-0.7.3 1.19.2
  [✔] entityculling-fabric-1.6.1-mc1.19.2
  [✔] exordium-fabric-1.0.2-mc1.19.2
  [✔] explorify-fabric-1.19-1.3.0
  [✔] extremesoundmuffler-3.37-fabric-1.19.2
  [✔] fabric-diagonal-panes-0.6.4
  [✔] fabric-language-kotlin-1.9.4 kotlin.1.8.21
  [✔] fabric-seasons-2.1 1.19
  [✔] fabric-seasons-extras-1.2-BETA 1.19
  [✔] fabric-seasons-terralith-2.3.7-compat-1.0
  [✔] FabricShieldLib-1.7-1.19.2
  [✔] FallingTree-1.19.2-3.10.0
  [✔] Female-Gender-Mod-fabric-1.19.2-3.0.1(1)
  [✔] ferritecore-5.0.3-fabric
  [✔] firstperson-fabric-2.2.2-mc1.19.2
  [✔] FlowerPatch-fabric-1.19.2-2.0.1
  [✔] ForgeConfigAPIPort-v4.2.11-1.19.2-Fabric
  [✔] grassseeds-1.19.2-3.0
  [✔] grind-enchantments-3.0.0-beta.1 1.19.2
  [✔] half-doors-1.3.9 1.19.x
  [✔] headindex-1.0.9
  [✔] highspeed-rail-0.0.3 1.19.2
  [✔] IKnowWhatImDoing-4.1.1-fabric
  [✔] immersive_armors-1.5.5 1.19.2-fabric
  [✔] immersivesnow-1.19.2-1.2.0
  [✔] indium-1.0.9 mc1.19.2
  [✔] infinityandmending-1.0.0 1.19.3
  [✔] infinityfix-1.19.x-1.0.3 1.19.3
  [✔] interactic-0.1.11 1.19
  [✔] InventorySorter-1.8.10-1.19
  [✔] iris-mc1.19.2-1.6.2
  [✔] itemalchemy-0.5.6
  [✔] lambdabettergrass-1.3.0 1.19
  [✔] lambdynamiclights-2.2.0 1.19.2
  [✔] lanterns-belong-on-walls-1.4.0-1.19
  [✔] light-overlay-7.0.0
  [✔] limits_grapple-0.6.3-1.19
  [✔] lithium-fabric-mc1.19.2-0.11.1
  [✔] mcpitanlibarch-1.6.3-1.19.2-fabric
  [✔] memoryleakfix-fabric-1.17 -1.0.0
  [✔] midnightlib-quilt-1.0.0-patch1
  [✔] mineralchance-1.19.2-3.1
  [✔] modmenu-4.2.0-beta.2
  [✔] MoreBows-1.0.10 1.19.2
  [✘] MTR-fabric-1.19.2-3.2.2-hotfix-1.jar (disabled)
  [✔] nicer-skies-1.2.0 1.19.2
  [✔] no-more-purple-1.0.1 1.19
  [✔] no-shield-delay-1.0.0
  [✔] no-telemetry-1.7.0
  [✔] NoChatReports-FABRIC-1.19.2-v1.13.12
  [✔] nostrip-1.2.3-1.19 
  [✔] Nullscape_1.19.3_v1.2.1
  [✔] numeralping-1.1.0
  [✔] numismatic-overhaul-0.2.8 1.19
  [✔] omnihopper-2.0.0 1.19
  [✔] onebar-3.3.4
  [✔] ostOverhaul-0.2.6-1.19
  [✔] OverpoweredMending-1.19.2-2.8.2
  [✔] owo-lib-0.9.3 1.19
  [✔] paradise-lost-2.1.0-beta 1.19.2
  [✔] Ping-Wheel-1.3.0-fabric-1.19.2
  [✔] placeableblazerods-1.19.2-3.0
  [✔] player-animation-lib-fabric-1.0.2
  [✔] PresenceFootsteps-1.6.4
  [✔] puzzle-1.4.2-1.19
  [✔] PuzzlesLib-v4.4.0-1.19.2-Fabric
  [✔] qfapi-4.0.0-beta.30_qsl-3.0.0-beta.29_fapi-0.76.0_mc-1.19.2
  [✔] quilt_loading_screen-4.0.0 1.19
  [✔] randombonemealflowers-1.19.2-4.1
  [✔] realisticsleep-1.7.0
  [✔] reinforced-barrels-2.3.0 1.19
  [✔] reinforced-chests-2.2.0 1.19
  [✔] reinforced-shulker-boxes-2.2.0 1.19
  [✔] Retraining-fabric-1.19-1.2.0
  [✔] rottenflesh-to-leather_1-19
  [✔] rsls-1.0.1
  [✔] seasonhud-fabric-1.19.2-1.1.0
  [✔] simplyswords-fabric-1.43.0-1.19.2
  [✔] smallernetherportals-1.19.2-3.4
  [✔] sodium-fabric-mc1.19.2-0.4.4 build.18
  [✔] soundphysics-fabric-1.19.2-1.0.18
  [✔] stack-to-nearby-chests-mc1.19.2-0.2.7
  [✔] statuseffecttimer-1.1.1 1.19
  [✔] stendhal-1.3.5-1.19
  [✔] subterrestrial-fabric-1.19.2-2.0.0
  [✔] TaxFreeLevels-1.3.3-fabric-1.19
  [✔] tectonic-mod-mc1.19.2-v1.1.10
  [✔] Terralith_1.19.3_v2.3.7b
  [✘] terrestria-5.0.8.jar (disabled)
  [✔] travelers-backpack-1.19.2-8.2.22
  [✔] TravelersTitles-1.19.2-Fabric-3.1.0
  [✘] traverse-6.0.6.jar (disabled)
  [✔] trinkets-3.4.2
  [✔] underwaterenchanting-1.19.2-2.2
  [✔] VanitySlots-1.2.6
  [✔] villagespawnpoint-1.19.2-4.0
  [✔] Void-Fog-2.7.1
  [✔] wso16-fabric-1.1
  [✔] xaeroarrowfix-fabric-1.1 1.16
  [✔] Xaeros_Minimap_23.4.3_Fabric_1.19.1
  [✔] XaerosWorldMap_1.30.2_Fabric_1.19.1
  [✔] YetAnotherConfigLib-2.2.0-for-1.19.2
  [✔] YungsApi-1.19.2-Fabric-3.8.9
  [✔] YungsBetterDesertTemples-1.19.2-Fabric-2.2.2
  [✔] YungsBetterMineshafts-1.19.2-Fabric-3.2.0
  [✔] YungsBetterNetherFortresses-1.19.2-Fabric-1.0.5
  [✔] YungsBetterOceanMonuments-1.19.2-Fabric-2.1.0
  [✔] YungsBetterStrongholds-1.19.2-Fabric-3.2.0
  [✔] YungsExtras-1.19.2-Fabric-3.1.0
  [✔] Zoomify-2.9.0

**Additional Information**
Anything else you want to add?

**Comment by kettle-7** [comment]
MTR is known to not work with Quilt at the moment so you'll just have to use the regular Fabric loader.

**Comment by LunarPidgeon** [comment]
damn, that sucks :(
thanks for the quick reply
