### ISSUE TITLE
My Train passes almost all stations except one and in that the train wont depart

### ISSUE THREAD

**Issue by FewCurve** [jonafanho/Minecraft-Transit-Railway#682]
**Expected Behaviour**
Trains are supposed to stop at all stations and depart according to the instructed time.

**Actual Behaviour**
The train passes all stations after exiting the depot except one where it won't depart the station.

**Reproduction Steps**

1. None

**Crash Report**
Could you attach a crash report to the issue?

**Screenshots**
If applicable, could you add screenshots to help explain your problem?
![image](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/133969909/3509bac0-2bc9-4576-94e7-1ffab543a85f)

**Environment**

- Minecraft Version:
- Installed Mods:

**Additional Information**
Is there anything else you'd like to add?
no.

**Comment by sasay21** [comment]
+++
