### ISSUE TITLE
卡在正在刷新线路不动

### ISSUE THREAD

**Issue by sssysy** [jonafanho/Minecraft-Transit-Railway#683]
**Expected Behaviour**
刷新完路线应当快速处理完成

**Actual Behaviour**
线路过多或轨道过长后重进游戏不管哪条线路重新刷新都一直显示"正在刷新线路"，在初期建设时线路是可以秒刷新的，但是最近刷新后等了5min+还是一样正在刷新

**Environment**

- Minecraft Version:1.19.3
- Installed Mods:3.2.2-hotfix-1

**Comment by jonafanho** [comment]
Duplicate of #352
