### ISSUE TITLE
MTR hosted on server has an issue of 3 minutes delay on the timeboard.

### ISSUE THREAD

**Issue by Jacky0987** [jonafanho/Minecraft-Transit-Railway#688]
Hosted by Arclight 1.19.2 with MTR has an issue.
The arrival screen (i dont know the exact name, its the thing which shows the estimated arrival time of train)
always has a 3-minute delay.
When the train arrives, the screen still indicates 3 minutes and seems never refresh.
On all size of the screen the problem exists.
How should I fix it? It appears to be working fine on my local server.

**Comment by Jacky0987** [comment]
MTR Forge Version. 3.2.0.

**Comment by jonafanho** [comment]
Check that the computer system times are synced properly on both the client and server.
