### ISSUE TITLE
Airplane Bug

### ISSUE THREAD

**Issue by Thekielgamer** [jonafanho/Minecraft-Transit-Railway#694]
**Expected Behaviour**
The "This station is" Shows only 1 line/Sentence, and says the next station in 1 sentence
**Actual Behaviour**
Shows/Says Or Duplicates

**Crash Report**
No file rlly

**Screenshots**
Reply

**Environment**

- Minecraft Version: 1.19.3
- Installed Mods:MTR 3.2.2 Fabric, Joban Client, fabric api, dynamic Sound Filters, Optifabric

**Additional Information**
Anything else you want to add?
None

**Comment by Thekielgamer** [comment]
![2023-06-09_20 33 37](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/114273595/df407a76-cedd-4109-a3d9-514275c6c826)
![2023-06-09_20 33 36](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/114273595/c0c016d5-dd5d-4212-a63e-b9cd73f3c04a)

**Comment by kettle-7** [comment]
umm can you send a screenshot of editing the station in the railway dashboard ?
