### ISSUE TITLE
Elevator Doors make blocks around it unbreakable until server syncs with client

### ISSUE THREAD

**Issue by bernzrdo** [jonafanho/Minecraft-Transit-Railway#695]
**Expected Behaviour**
Normally break the elevator door and the blocks around it.

**Actual Behaviour**
After placing the elevator door, the blocks become unbreakable until right-clicked with the elevator refresher, or closing the world and opening again

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Place a elevator door
2. Try to break it
3. Try to break the blocks around it
4. Right-click the blocks you broke with the elevator refresher
5. Close the world
6. Open it again

**Screenshots**
https://youtu.be/ZK2uHab29SU

**Environment**

- Minecraft Version: 1.20
- Installed Mods: MTR-fabric-1.20-3.2.2-hotfix-1.jar

**Comment by N0aW** [comment]
Experiencing the same problem.

Using Minecraft 1.20 with MTR-fabric-1.20-3.2.2-hotfix-1.jar

**Comment by N0aW** [comment]
Using `/reload` doesn't do anything.

**Comment by bernzrdo** [comment]
@N0aW isn't reload just to for datapacks? i don't think it is for server and client synchronization

**Comment by N0aW** [comment]
I forgot

**Comment by jonafanho** [comment]
Related to #705
