### ISSUE TITLE
Decoration Addon loading error

### ISSUE THREAD

**Issue by BoborMBI2** [jonafanho/Minecraft-Transit-Railway#698]
Everytime I start mc in the 1.18.2 it says that the MTR decoration addon isn't well loaded.
![Bild_2023-06-14_145353649](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/136601467/e115b2e3-4ec3-4830-92df-ee339b142133)

**Comment by Ultimate-USA-YT** [comment]
Make shure your Mods are ALL Updated
