### ISSUE TITLE
Crash with tweakaroo

### ISSUE THREAD

**Issue by Anders-AAU** [jonafanho/Minecraft-Transit-Railway#7]
It seems like there is an issue with tweakeroo when i place an escalator

[crash-2021-01-19_13.52.22-client.txt](https://github.com/jonafanho/Minecraft-Transit-Railway/files/5835932/crash-2021-01-19_13.52.22-client.txt)

**Comment by jonafanho** [comment]
Hello, thank you for your crash report. I have tried running tweakeroo of the same version in Minecraft but I had no issues when placing down escalators. I wasn't able to reproduce your crash.

Would you mind sharing which tweakeroo settings you had enabled? I think I tried fast right click and fast block placing, both of which did not have issues.

**Comment by Anders-AAU** [comment]
Yeah here you go. had to zip it. I have been placing some routes down to test and the mod looks AWESOME!

[tweakeroo.zip](https://github.com/jonafanho/Minecraft-Transit-Railway/files/5838668/tweakeroo.zip)

**Comment by jonafanho** [comment]
Fixed in version beta-2 of the mod. Take a look and let me know if the issue persists. Thanks!
