### ISSUE TITLE
Problem with Passenger Information Display System

### ISSUE THREAD

**Issue by JohnDeereLiebhaber** [jonafanho/Minecraft-Transit-Railway#704]
Hello I have a problem with the Passenger Information Display System when I place this it also shows the name of the first station at the first station. If I place this at the 2nd station, the name of the first station is displayed, the time behind it is correct, but both as well as the 3rd station name of the first station is displayed, time is correct, this is continuous, why is that?

MC version: 1.19.2

Thanks in advance

**Comment by kettle-7** [comment]
Could you send a screenshot of the route that the PIDS are displaying ?

**Comment by JohnDeereLiebhaber** [comment]
hello, yes i can pictures are attached 
the first picture shows the second station i.e. Emperor City

the second picture the first station CreepCity Station

I right-click with the brush item and go to Edit there I can only select CreepCity Station, as I said, the time is correct for all stations

thanks in advance


![Screenshot 2023-06-26 160215](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/82206068/0b1d5e62-9235-41f4-a302-1475a30b733e)
![Screenshot 2023-06-26 153133](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/82206068/10c99bde-8aaa-4ba3-ba95-f89fae41bdde)
![Screenshot 2023-06-26 153027](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/82206068/51e66df2-c676-4cd8-9c19-17fcf8254ff2)

**Comment by jonafanho** [comment]
You should split the route into two routes with the same colour, one route for each direction.
