### ISSUE TITLE
[Bug report] Game crashing unexpectedly

### ISSUE THREAD

**Issue by TheFighter137** [jonafanho/Minecraft-Transit-Railway#751]
**Expected Behaviour**
Game still running.
**Actual Behaviour**
The game freezes for a few seconds, then crashes.
**Reproduction Steps**
No idea, it is fully random.
**Crash Report**
https://mclo.gs/PQJlmDy
**Environment**
- Fabric Version : 0.14.21
- Minecraft Version: 1.18.2
- Installed Mods: (see image)
![prismlauncher_2023-09-17_15 16 10](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/116449714/1d3cc0c2-e06e-4295-be4d-8fa9f9228359)

**Comment by DreamUniverse843** [comment]
It seems that the problem related to railway sign rendering.
Try to reduce the "Dynamic texture resolution"?
![image](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/53889721/4b62c5ce-e148-4f42-be75-67c9cd51d7d3)


```
[15:07:01] [Render thread/INFO]: [CHAT] [TheFighter137: Played sound minecraft:na.train_approaching_male to TheFighter137]
--
769 | #
770 | # A fatal error has been detected by the Java Runtime Environment:
771 | #
772 | #  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000029973f1f34c, pid=8648, tid=10952
773 | #
774 | # JRE version: Java(TM) SE Runtime Environment (17.0.8 9) (build 17.0.8 9-LTS-211)
775 | # Java VM: Java HotSpot(TM) 64-Bit Server VM (17.0.8 9-LTS-211, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
776 | # Problematic frame:
777 | # J 33333 c2 mtr.render.RenderRailwaySign.render(Lmtr/block/BlockRailwaySign$TileEntityRailwaySign;FLnet/minecraft/class_4587;Lnet/minecraft/class_4597;II)V (376 bytes) @ 0x0000029973f1f34c [0x0000029973f1ea40 0x000000000000090c]
778 | #
779 | # No core dump will be written. Minidumps are not enabled by default on client versions of Windows
780 | #
781 | # An error report file with more information is saved as:
782 | # C:\Users\********\AppData\Roaming\PrismLauncher\instances\Test 1.18.2\.minecraft\hs_err_pid8648.log

```

**Comment by TheFighter137** [comment]
> It seems that the problem related to railway sign rendering. Try to reduce the "Dynamic texture resolution"? ![image](https://user-images.githubusercontent.com/53889721/274512531-4b62c5ce-e148-4f42-be75-67c9cd51d7d3.png)
> 
> ```
> [15:07:01] [Render thread/INFO]: [CHAT] [TheFighter137: Played sound minecraft:na.train_approaching_male to TheFighter137]
> --
> 769 | #
> 770 | # A fatal error has been detected by the Java Runtime Environment:
> 771 | #
> 772 | #  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000029973f1f34c, pid=8648, tid=10952
> 773 | #
> 774 | # JRE version: Java(TM) SE Runtime Environment (17.0.8 9) (build 17.0.8 9-LTS-211)
> 775 | # Java VM: Java HotSpot(TM) 64-Bit Server VM (17.0.8 9-LTS-211, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
> 776 | # Problematic frame:
> 777 | # J 33333 c2 mtr.render.RenderRailwaySign.render(Lmtr/block/BlockRailwaySign$TileEntityRailwaySign;FLnet/minecraft/class_4587;Lnet/minecraft/class_4597;II)V (376 bytes) @ 0x0000029973f1f34c [0x0000029973f1ea40 0x000000000000090c]
> 778 | #
> 779 | # No core dump will be written. Minidumps are not enabled by default on client versions of Windows
> 780 | #
> 781 | # An error report file with more information is saved as:
> 782 | # C:\Users\********\AppData\Roaming\PrismLauncher\instances\Test 1.18.2\.minecraft\hs_err_pid8648.log
> ```

Issue fixed

It wasn't a bug related to Minecraft, it was an issue with my RAM, as apparently, combining 3200 MHz and 4 RAM sticks on a Ryzen 2700X doesn't make a good recipe
