### ISSUE TITLE
请求更新新版

### ISSUE THREAD

**Issue by SadEPa0628** [jonafanho/Minecraft-Transit-Railway#760]
**Expected Behaviour**
I changed 1.20.2 recently, but there is no version of 1.20.2 in MTR
我最近更换了1.20.2，但是MTR没有1.20.2的版本

**Describe the solution you'd like**
Update support version 1.20.2
更新支持1.20.2的版本

**Additional Information**
![image](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/120295331/c8514dd9-7a47-4f69-8777-568c0a7a8b73)

**Comment by DreamUniverse843** [comment]
Actions 自动构建内已包含 1.20.2 的 jar 文件（找对应 4.0.0 分支的自动构建），但 jonafanho 在 commit 上写了自动构建只保证能构建成功，不保证游戏内完全可用。
~~而且 1.20 系版本支持本来就是打算等 4.0.0 发版才有的，发一个半成品也没有意义~~
![image](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/53889721/7399b089-c632-4e5a-a2a3-c1cf8aa842e3)
![image](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/53889721/7084ce60-d7a6-4043-8d25-ef3fb700cf57)

**Comment by SadEPa0628** [comment]
谢谢，因为我需要用到它，请快点

**Comment by DreamUniverse843** [comment]
你可以去 Actions 自取 Artifacts 构建
至于正式发版请等待 jonafanho 完成对 4.0.0 的完善



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月12日(周四) 下午3:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jonafanho/Minecraft-Transit-Railway] 请求更新新版 (Issue #760)




 
谢谢，因为我需要用到它，请快点

**Comment by SadEPa0628** [comment]
那个加了不被加载的，我就等正式版吧

**Comment by Ultimate-USA-YT** [comment]
The 4.0.0 Beta is Unstable. The Full Releace is Projected for December or January. It may change though

**Comment by SadEPa0628** [comment]
Thank you!

**Comment by SadEPa0628** [comment]
呃这算是解决了还是没解决呢，要不要关闭议题啊...
Well, is that solved or not solved? Should we close the issue...

**Comment by DreamUniverse843** [comment]
关闭吧，因为反正也要等 4.0.0 发布。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月14日(周六) 下午2:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jonafanho/Minecraft-Transit-Railway] 请求更新新版 (Issue #760)




 
呃这算是解决了还是没解决呢，要不要关闭议题啊...
 Well, is that solved or not solved? Should we close the issue...

**Comment by SadEPa0628** [comment]
OK
