### ISSUE TITLE
Game crashes when I refresh elevator tracks or edit signs

### ISSUE THREAD

**Issue by Trendysaucer795** [jonafanho/Minecraft-Transit-Railway#761]
I expected to be able to edit the sign or to refresh the floor tracks without the game crashing

But when I tried to click the edit button on the sign or refresh the elevator, the game crashed with error code 1

1. Click on the sign or elevator with the brush
2. If it is an elevator, the game crashes immediately. When I click on the sign, I can get to the edit screen but no further than that.
3. The game crashes with error code 1

- Minecraft Version: 1.16.5 forge 36.2.39
- Installed Mods: Too many to name but some main ones are flywheel, oculus, rubidium, starlight, geckolib, and lazy dfu (there are 41 in total)

**Comment by DreamUniverse843** [comment]
plz provide your crash report (file or online pastebin)

**Comment by Trendysaucer795** [comment]
There is no view crash report option when I get the crash. It just says exit code 1. But here's a full list of the mods  and other stuff from an older crash report

forge-1.16.5-36.2.34-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		MTS+Official+Pack-1.16.5-V25.jar                  |Immersive Vehicles (MTS/IV) - |mtsofficialpack               |V24                 |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-eyemod-v2.3.2a.jar                   |Eye Mod                       |eyemod                        |1.0                 |DONE      |Manifest: NOSIGNATURE
		FCB-1.1.jar                                       |Flat Colored Blocks Mod       |fcb                           |1.0                 |DONE      |Manifest: NOSIGNATURE
		ColorUtility-[1.16.5]-forge-2.0.1serverfix.jar    |ColorUtility                  |colorutility                  |2.0.1               |DONE      |Manifest: NOSIGNATURE
		Trin+Civil+Pack-1.16.5-3.21.1.jar                 |Immersive Vehicles (MTS/IV) - |iv_tcp_v3                     |3.20.0              |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.8.0.1009.jar                         |Just Enough Items             |jei                           |7.8.0.1009          |DONE      |Manifest: NOSIGNATURE
		smoothboot-forge-1.16.4-1.2.2.jar                 |Smooth Boot                   |smoothboot                    |1.16.4-1.2.2        |DONE      |Manifest: NOSIGNATURE
		Architects-Palette-1.16.4-1.1.5.jar               |Architect's Palette           |architects_palette            |1.1.2               |DONE      |Manifest: NOSIGNATURE
		UNU+Civilian+Pack+[MTS]+1.16.5-22.10.0-6.0.4.jar  |UNU Civilian Vehicles         |unucivil                      |6.0.4               |DONE      |Manifest: NOSIGNATURE
		TrackAPI-1.16.4-forge-1.2.1.jar                   |TrackAPI                      |trackapi                      |1.2                 |DONE      |Manifest: NOSIGNATURE
		rubidium-mc1.16.5-0.2.13.jar                      |Rubidium                      |rubidium                      |0.2.13              |DONE      |Manifest: NOSIGNATURE
		flywheel-1.16-0.2.5.jar                           |Flywheel                      |flywheel                      |1.16-0.2.5          |DONE      |Manifest: NOSIGNATURE
		chiseled0.4.3.jar                                 |Chiseled                      |chiseled                      |0.2.2               |DONE      |Manifest: NOSIGNATURE
		create-mc1.16.5_v0.3.2g.jar                       |Create                        |create                        |v0.3.2g             |DONE      |Manifest: NOSIGNATURE
		oculus-mc1.16.5-1.4.6.jar                         |Oculus                        |oculus                        |1.4.6               |DONE      |Manifest: NOSIGNATURE
		Croptopia-1.16.5-FORGE-2.0.5.jar                  |Croptopia                     |croptopia                     |2.0.5               |DONE      |Manifest: NOSIGNATURE
		CookingForBlockheads_1.16.5-9.3.4.jar             |Cooking for Blockheads        |cookingforblockheads          |9.3.4               |DONE      |Manifest: NOSIGNATURE
		Public+Transport+Mod+10.2-1.16.5.jar              |TransportMod                  |transportmod                  |10.2                |DONE      |Manifest: NOSIGNATURE
		FramedBlocks-2.16.3.jar                           |FramedBlocks                  |framedblocks                  |2.16.3              |DONE      |Manifest: NOSIGNATURE
		dbExtended-1.16.5-4.1.1.jar                       |Dave's Building Extended      |davebuildingmod               |4.1.1               |DONE      |Manifest: NOSIGNATURE
		Blocks+-1.16.5-1.2.jar                            |Blocks +                      |blocksplus                    |1.2                 |DONE      |Manifest: NOSIGNATURE
		worldedit-mod-7.2.5-dist.jar                      |WorldEdit                     |worldedit                     |7.2.5+57d5ac9       |DONE      |Manifest: NOSIGNATURE
		lazydfu-0.1.3.jar                                 |LazyDFU                       |lazydfu                       |0.1.3               |DONE      |Manifest: NOSIGNATURE
		starlight-1.2.jar                                 |Starlight                     |starlight                     |1.0.0-RC2           |DONE      |Manifest: NOSIGNATURE
		Traffic+Control+Ps+Roads+3.0.0+_1.16.5.jar        | Traffic control+Policestuff b|traffic_control_roadsmodbyteer|3.0.0               |DONE      |Manifest: NOSIGNATURE
		cfm-7.0.0pre22-1.16.3.jar                         |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre22         |DONE      |Manifest: NOSIGNATURE
		architectury-1.32.68.jar                          |Architectury                  |architectury                  |1.32.68             |DONE      |Manifest: NOSIGNATURE
		MTR-forge-1.16.5-3.2.0.jar                        |Minecraft Transit Railway     |mtr                           |1.16.5-3.2.0        |DONE      |Manifest: NOSIGNATURE
		ImmersiveRailroading-1.16.5-forge-1.9.1.jar       |Immersive Railroading         |immersiverailroading          |1.16.5-forge-1.9.1  |DONE      |Manifest: NOSIGNATURE
		ferritecore-2.1.1-forge.jar                       |Ferrite Core                  |ferritecore                   |2.1.1               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		Immersive+Vehicles-1.16.5-22.11.0.jar             |Immersive Vehicles (formerly M|mts                           |NONE                |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.34-universal.jar                |Forge                         |forge                         |36.2.34             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		chiselsandbits-1.0.63.jar                         |Chisels & bits                |chiselsandbits                |1.0.63              |DONE      |Manifest: NOSIGNATURE
		UNU+Parts+Pack+[MTS]+1.16.5-22.10.0-6.1.1.jar     |UNU Custom Parts Pack         |unucustom                     |6.0.0               |DONE      |Manifest: NOSIGNATURE
		Trin+Parts+Pack-1.16.5-2.23.1.jar                 |Immersive Vehicles (MTS/IV) - |iv_tpp                        |2.22.0              |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.106.jar                 |GeckoLib                      |geckolib3                     |3.0.106             |DONE      |Manifest: NOSIGNATURE
		UniversalModCore-1.16.5-forge-1.1.3 (1).jar       |Universal Mod Core            |universalmodcore              |1.1.3               |DONE      |Manifest: NOSIGNATURE

**Comment by DreamUniverse843** [comment]
or the log file produced when you crash is ok,like latest.log or previous log files
we have no idea if we dont know where the game crashes

**Comment by Trendysaucer795** [comment]
here is the latest.log file in pastebin

https://pastebin.com/UBf8kZLk

**Comment by Trendysaucer795** [comment]
Has there been any progress?

**Comment by DreamUniverse843** [comment]
I've read your log and i couldnt find any symbol related to crash...
and i noticed that your mtr mod is 3.2.0, try to update it? maybe newer version could solve it.

**Comment by Trendysaucer795** [comment]
Ok

**Comment by Trendysaucer795** [comment]
Nope, it did not work. here is another log https://pastebin.com/gcqw1Gu7

**Comment by Trendysaucer795** [comment]
NVM I just had custom fonts enabled. I turned it off and it works now
