### ISSUE TITLE
[1.20.1] WTHIT mod compatibility issue

### ISSUE THREAD

**Issue by ghost** [jonafanho/Minecraft-Transit-Railway#763]
**Behaviour**
Looking down can cause WTHIT to display like this...

**Screenshots**
![2023-10-21_07 20 23](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/107382349/827bf354-aade-4b58-9f03-b2e26b63d80d)

**Environment**

- Minecraft Version: 1.20.1
- Installed Mods: WTHIT & 99+ mods

**Comment by Ultimate-USA-YT** [comment]
1: MTR 1.20 is not Recommended
2: That us Likely `mtr:seat`
