### ISSUE TITLE
Exits train from the left every time

### ISSUE THREAD

**Issue by Toma2yourblock** [jonafanho/Minecraft-Transit-Railway#8]
I don't know if this is a bug or just the way it is coded, but I've realized the trains exit you 2 blocks to the left almost every time.  Sometimes it exits you right from the cart you're sitting in but most of the time it exits you 2 blocks left.   This is inconvenient if for example you have a platform in the sky to the right of the tracks.  The Train will just exit you to the left even if there is no block to land on so you will fall from the sky.  Another example is if there is a station with an exit intended to be on the right, with a wall to the left, the train will exit you through or into the wall anyway.  Regardless, this is so far a fantastic mod.  Please keep up the great work!

**Comment by jonafanho** [comment]
Fixed in version beta-2 of the mod. Take a look and let me know if the issue persists. Thanks!
